### ISSUE TITLE
Error In Console

### ISSUE THREAD

**Issue by AlexandruDinulescu** [SqrTT/prophet#104]
Why am I getting this error in the prophet uploader console? 
Error: Error: EPERM: operation not permitted, stat ? 
After that I have to restart VSC because even if I try to reupload the cartridges it still gives me an error and prevents the upload from completing.

**Comment by SqrTT** [comment]
Hi @AlexandruDinulescu 
Could you please some steps to reproduce? Your environments etc (OS version, the extension version).

**Comment by AlexandruDinulescu** [comment]
Unfortunately I am unable to reproduce this anymore :(
I am running Windows 10. Unfortunately I have no idea on how I can check what version of the extension I have.

**Comment by SqrTT** [comment]
closing... feel free to reopen once issue occur again with more details so I would be able to reproduce and fix the issue.
