### ISSUE TITLE
Setting breakpoint in controller but prophet tries to open same named file in a different cartridge

### ISSUE THREAD

**Issue by kshehadeh** [SqrTT/prophet#106]
I have set a breakpoint in the Wishlist.js controller of mystore_storefront cartridge (/mystore_storefront/cartridge/controllers/Wishlist.js) but when I trigger the breakpoint, the Prophet VSCode extension displays this error: 

     Unable to open 'Wishlist.js': File not found (file:///Users/myname/dev/demandware- 
     webstore/cartridges/other_myapp_storefront/cartridge/controllers/Wishlist.js). 

"other_myapp_storefront" cartridge does come *before* the myapp_storefront cartridge if that helps to know.  

So it seems to register the right breakpoint but is unable to show position and other information because it is looking for the wrong file.  

Thoughts?

**Comment by SqrTT** [comment]
Hi, @kshehadeh thanks for reporting.

Does `mystore_storefront` present in cartridges list?

![image](https://user-images.githubusercontent.com/1271300/39429698-5abcba90-4c94-11e8-83c4-06c6f9f0013e.png)

**Comment by SqrTT** [comment]
is thare a chance that `mystore_storefront` patrially matches a `other_myapp_storefront`?

https://github.com/SqrTT/prophet/blob/master/src/mockDebug.ts#L638

**Comment by SqrTT** [comment]
Hi, @kshehadeh.

Could you please check version 1.0.10? the issue should be fixed

**Comment by kshehadeh** [comment]
Worked perfectly.  Thanks!
