### ISSUE TITLE
debugger debug not working correctly on some variables.

### ISSUE THREAD

**Issue by MGloder** [SqrTT/prophet#108]
When the debugger connected to the sandbox in the debug mode, in the variables section, it cannot expand some variables. For example, the "req" variable. 

I tried in different OS and it has same issue
OS: Win10/Mac

**Comment by SqrTT** [comment]
Hi, @MGloder thanks for reporting.

Could you please check version `1.0.10`?

Note: properties defined via `Object.defineProperty` still will be invisible since they do not exist until called (will be visible if `enumerable: true`).

**Comment by MGloder** [comment]
Hi @SqrTT  Yes, I'm using the version 1.0.10 and I took a screenshot from vscode. Is it normal?

![image](https://user-images.githubusercontent.com/8831738/40092845-03ffe050-58f2-11e8-8d51-1c7c98bcd1c6.png)

**Comment by SqrTT** [comment]
this is weird.

Similar case works for me:

![image](https://user-images.githubusercontent.com/1271300/40104119-279fa6e8-58f8-11e8-8f63-ea38ae355cf7.png)

Could you please hover a mouse over `req` variable in variables list?
![image](https://user-images.githubusercontent.com/1271300/40104189-5312ecc2-58f8-11e8-8b53-aad3e89c22dc.png)

Does it show you `Request` type?
Is there chance that somebody put there string with content `[object Object]`?

Note: `res` variable is expandable while it is similar object.

**Comment by SqrTT** [comment]
Also please try to remove and install the extension.

**Comment by MGloder** [comment]
@SqrTT Thanks for your reply. Today, I'm using the debugger and the req variable seem working correctly. 
It's just weird. 
![image](https://user-images.githubusercontent.com/8831738/40155038-1ea13d6e-59c4-11e8-8b55-967cefcfad41.png)
