### ISSUE TITLE
Debug Problem

### ISSUE THREAD

**Issue by suaterken** [SqrTT/prophet#109]
Hello @SqrTT 

I have facing problem in debugger for a while,
Here is detailed picture and error log.

Thanks

![prophet_bug](https://user-images.githubusercontent.com/7967939/40173234-d0bf440e-59d9-11e8-9fa2-f19007229c4f.PNG)
[error.txt](https://github.com/SqrTT/prophet/files/2012864/error.txt)

**Comment by SqrTT** [comment]
Hi @suaterken 
Interesting. Looks like `.` (dot) in a property name breaks resolving.

Thanks. I'll take a look on this

**Comment by SqrTT** [comment]
Unfortunately, I'm not able to fix this issue. Looks like SFCC incorrectly handles `]` on their side.

**Comment by SqrTT** [comment]
seems this is the same issue like #95
Let's track there
