### ISSUE TITLE
Prophet's commands not found in VSC

### ISSUE THREAD

**Issue by davidwitt-demandpdx** [SqrTT/prophet#110]
My Prophet extension abruptly stopped working today.

- Cartridges pane no longer shows cartridge list
- Upload/Clean functions not recognized as commands by VSC
- Debug session won't kick off

My gut tells me the extension is corrupted on my machine. I've disabled/re-enabled and removed/re-installed and everything remains the same.
I've even removed the extension via CLI in the ~/.vscode/extensions/ folder
![screen shot 2018-05-21 at 9 51 42 am](https://user-images.githubusercontent.com/30838870/40314099-1e5190ea-5cdd-11e8-92d2-57853fa082eb.png)

Is there a better way to get a clean slate to get Prophet working again?

VSCode version: 1.23.1
Prophet Version: 1.0.10

**Comment by AlexandruDinulescu** [comment]
I have the same issue.
I've disabled/re-enabled installed/uninstalled the extension.

**Comment by AlexandruDinulescu** [comment]
@SqrTT have you had a chance to look at these issues?

**Comment by davidwitt-demandpdx** [comment]
I think I may have an answer. 

I deleted my project's jsconfig.json file, restarted, and the extension worked.

I re-added it after another reboot and it seems that it's still working. Maybe there was some error along the way with what Prophet does with code assist or something got corrupted in the update.

Here's the config file I used;
```
{
    "compilerOptions": {
        "noLib": true,
        "target": "es5",
        "baseUrl": "./",
        "paths": {
            "*" : ["./*", "modules/*", "./../dw-api-types/*"]
        }
    },
    "typeAcquisition": {
        "enable": true
    },
    "include": [
        "../dw-api-types/*.d.ts",
        "../dw-api-types/**/*.d.ts",
        "./*/cartridge/scripts/**/*.js",
        "./*/cartridge/controllers/**/*.js",
        "./modules/**/*.js"
    ]
}
```

**Comment by SqrTT** [comment]
May the issue be closed?
