### ISSUE TITLE
Debugger never stops in breakpoints

### ISSUE THREAD

**Issue by anaprata** [SqrTT/prophet#113]
Hi there,

I'm starting with VC + prophet, but I seam to have a problem. 
Apparently I have all configuration needed,  as my colleagues but I cannot break in the none of the same breakpoint that they can.
- dw.json - checked
- .project - checked (cartridge is detected)
- launch.json - checked

Debug initiates and stays waiting to hit breakpoint (in homepage)
I refresh and nothing happens.
What am I missing?
Thanks

**Comment by SqrTT** [comment]
Hi @anaprata 

Probably you are facing issue with extra `.project`. Please refer to https://github.com/SqrTT/prophet/issues/92#issuecomment-379307016

**Comment by anaprata** [comment]
Fantastic! Many thanks!
