### ISSUE TITLE
Can't add nor remove Breakpoints

### ISSUE THREAD

**Issue by MerlinPerrotLegler** [SqrTT/prophet#114]
Hello,

First thank for you work, I love it :)

Second since the 5 june 2018, I cant add nor remove breakpoint using Prophet but I can create or remove them using the [Script Debugger API](https://documentation.demandware.com/DOC2/topic/com.demandware.dochelp/ScriptDebuggerAPI/latest/usage/ScriptDebuggerAPI.html?cp=0_13) or using eclipse and than use them in Prophet.

So if you have any idea that could have cause this I'm all your :)

**Comment by fishme** [comment]
did you try to remove the plugin and reinstall again? I guess everything else was working and your debug configuration is also ok.

**Comment by SqrTT** [comment]
closing since no info during a while. Feel free to reopen
