### ISSUE TITLE
Prophet does a clean/upload too often

### ISSUE THREAD

**Issue by gabrielfreiberg** [SqrTT/prophet#117]
Everytime JS is compiled in my workspace, prophet does a clean instead of uploading just the delta. Is there some option or way to avoid this?

**Comment by SqrTT** [comment]
Could you please check logs? The extension use clean in two cases:
* editor start
* and in case error (3 times in a row) happen during upload files. Probably you are facing some network issues or  some error is happen on sandbox. More details you may find in logs.

**Comment by SqrTT** [comment]
![image](https://user-images.githubusercontent.com/1271300/43704942-e5c28670-9969-11e8-9dcb-4fdce9a8ae83.png)

**Comment by gabrielfreiberg** [comment]
@SqrTT -- I do see an error seems to happen every time JS gets compiled:

`
[C 08:03:19] /Users/gfreiberg/code/workspaces/demandware/CLIENT/CLIENT/gulp_builder/temp-js-CLIENT/storeinventory
[C 08:03:19] /Users/gfreiberg/code/workspaces/demandware/CLIENT/CLIENT/gulp_builder/temp-js-CLIENT/pages/checkout
Error: Error: Method Not Allowed
Trying to re-upload
Connection validated successfully
Current active version is: gfreiberg
Start uploading cartridges
Cleanup code version...
Deleted int_CLIENT_loadtest`

What could consistently cause the "Error: Error: Method Not Allowed"?

**Comment by SqrTT** [comment]
hi @gabrielfreiberg 
Seems your build tool is creating/removing a batch of temporaty folders, the extension watcher isn't too fast so looks like it's trying to upload into a folder on sandbox which doesn't exist yet. 

There are several ways to avoid this:
 - create temporary structure outside workspace (i.e. `/tmp`)
 - add `temp-js-CLIENT` to exclude list `files.exclude`

**Comment by gabrielfreiberg** [comment]
Thanks!! Is files.exclude is part of the VSC configuration for Prophet, or part of dw.json?

**Comment by SqrTT** [comment]
you are welcome.
Is your issue solved? If so, please close the ticket.

**Comment by gabrielfreiberg** [comment]
The upload utility in prophet is still seeing those files change after I adjusted files.exclude. I made sure to restart VSC after the change.

    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/temp-js-CLIENT" : true
    }

**Comment by SqrTT** [comment]
Sorry, looks I mixed up with config name, could you please try to use `files.watcherExclude`
