### ISSUE TITLE
Not really an issue....need some advice....

### ISSUE THREAD

**Issue by AcciaioDigitale** [SqrTT/prophet#118]
Hi!

I'm searching to debug frontend javascript files.....ex: billing.js

I think Prophet Debugger can only debug server side files.....someone know how to debug frontend files in sandbox from VSC?

**Comment by SqrTT** [comment]
Hi!
frontend files are executed in a browser so you may install an extension that connects to your browser and allow debug such files. Or simply used debug in DevTools of your browser.

**Comment by AcciaioDigitale** [comment]
Yes, I know that. But it seems that the files are minified and I can not set the breakpoints

**Comment by SqrTT** [comment]
you should use a source map for that.

PS. Closing since not related to the extension.
