### ISSUE TITLE
node_modules is excluded even if configured to be included

### ISSUE THREAD

**Issue by andrewgadziksonos** [SqrTT/prophet#120]
When configuring `extension.prophet.ignore.list` to include node_modules, it's getting ignored and `node_modules` is not being zipped and uploaded.  The issue is here,

https://github.com/SqrTT/prophet/blob/20611f80a83977c88c3764dfb1da443cd3ae2e7a/src/server/WebDav.ts#L236

Here's my current settings,

`"extension.prophet.ignore.list": ["\\.git", "\\.zip$"],`

Thanks,

Andrew

**Comment by SqrTT** [comment]
Why do you need `node_modules` on the server? this folder is too big to be uploaded there

**Comment by bahagiga** [comment]
Hi @SqrTT ,

I think there is a case for it.

For example one could use npm packages that are "pure" in the sense that they aren't using node platform specific features and don't have any dependencies.

I have also myself used npm packages and then tweaked them to not be "node" dependent and it's frustrating that when you do an upload it overwrites and thereby I have to manually upload the folder to the WebDav.

I agree that it doesn't make sense to debug or watch the folder but can we just remove the limitation and let it upload the folder? https://github.com/SqrTT/prophet/blob/master/src/providers/Uploader.ts#L62

// Baha

**Comment by andrewgadziksonos** [comment]
We are using `moment.js` on the server and have a build process to copy that module into the cartridge that uses it.  Internally, it has a `node_module` dir that references its dependencies. 

I'm open for other ideas on how to accomplish the same thing.

**Comment by andrewgadziksonos** [comment]
Just want to leave an update here - we were able to solve this by building a version of moment.js that bundles moment-timezone + moment together and copies that built asset into the `scripts/util` dir.  No need for node_modules anymore!

**Comment by SqrTT** [comment]
SFCC doesn't support `node_modules` because of resolves them totally different. So there no reason to have such modules on a server. If you want to use such module you must manually put it onto `modules` folder.

The issue may be fixed but seems it produce more issues than resolves.

**Comment by aduponchel** [comment]
I am in the same case.
Indeed, we don't use the common JS implementation of require.
Of course node_module is not resolved when using require, everybody is aware about it.
However SFCC supports directory called node_modules. There is no contrainst about this.

The main purpose of use node_modules is for maintenance purpose. By including a package.json in your source you could update it easily.

**Comment by SqrTT** [comment]
which `package.json`? SCFF doesn't support canonical `package.json`.
 Should it  be in "project level" or "cartridge level"?
If cartridge level how it should be handled during the build process?
SFCC works with enterprise level projects, so what about security?

(about security see: https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5)

**Comment by aduponchel** [comment]
`package.json` as mentionned here : https://documentation.demandware.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FSFRA%2FModuleLookup.html&resultof=%22module%22%20%22modul%22%20 

``` Path Lookup Relative to the Current Module

If the path argument starts with "./" or "../", then it loads relative to the current module. The module can be a file or a directory. A file extension is acknowledged, but not required. If it's a directory, a package.json or a main file is expected in the directory.

Note:
A main file is a file named main, with either a .js, .ds, or .json extension.

If the package.json file does not contain a main property, the script defaults to the main file in the directory, if one exists. Access to parent files can't go beyond the top-level version directory. Access to other cartridges is allowed.
```
We push the the built node module with all of theses dependencies packaged into a node_modules folder. We care about security and only use trusted node module.
Updates are done manually and we don't use theses modules in sensitive pages/data.

**Comment by lostPixels** [comment]
This is an issue which has made me leave this plugin. We are using lodash in .DS files, and every time I go to upload with VSCode it breaks my sandbox. Eclipse does not have this problem so I am not sure why there's so much hesitation to match the same ruleset of the tried and true IDE of SFCC.

**Comment by danechitoaie** [comment]
So you would want to upload the whole node_modules just for a lib or two? As not many libs work with server side sfcc. There's also the performance issue when using other JS libs in SFCC. I was asked by SFCC SAs doing SRA to remove lodash as it was affecting performance.

**Comment by nek4life** [comment]
We have a root node_modules folder for the client which doesn't need to be uploaded and a smaller 8mb node_modules file in our cartridge that has private npm modules for the server. The modules are installed in both places. The cartridge node_modules needs to be uploaded. Been doing this for a few years now.

**Comment by SqrTT** [comment]
@nek4life 
So basically you have `node_modules` which isn't managed by npm (hence don't use it's benefits) and you have manage it's content manually. That's correct? If so I see no reason to have it named `node_modules`, would be better to name it just `modules` to follow SFCC rules.

**Comment by SGD1953** [comment]
Why can we not make `node_modules` a default config so that users can override (but it would be excluded out of the box) instead of arguing back & forth about the usefulness of uploading it?

**Comment by SqrTT** [comment]
Because I find this useless and harmful which cultivate a bad practice. Having change this may bring potential issue for people with event don't aware about this problem. Those people will bring back here and will require me to invest more time here. `node_modules` already hardcoded because a such issue (IIRC).

I will be happy to see and merge well tested in different configuration (and different OS) Pull Request. But right now I'm not ready to invest time into this.

**Comment by SGD1953** [comment]
Openness to accept a PR is a good first step. To me a default config would be safe as you would have to consciously remove `node_modules` which is hard to do by accident.

**Comment by nek4life** [comment]
> @nek4life
> So basically you have `node_modules` which isn't managed by npm (hence don't use it's benefits) and you have manage it's content manually. That's correct? If so I see no reason to have it named `node_modules`, would be better to name it just `modules` to follow SFCC rules.

Hi @SqrTT let me explain a bit more. You seem to be making too many assumptions about how our code base is setup and perhaps that's why it's hard to understand our use case.

We have private npm modules carefully written to work on both the client and server. A good example of this is say for form validate.

@namespace/validation say.

- root package.json contains @namespace/validation and the rest of our client deps
-- cartridge also contains a package.json with only server deps

Root package has a post install script to npm install the cartridge packages

Both are managed by npm and no shared code is committed into our repo. Our server code is small as we are careful only to include libraries that can work in this way.

So we are in fact getting all the benefits of npm and private npm modules using this method as well as having a seamless install for the user.

We've been working this way for several years now likely before the modules folder was a thing. I don't remember seeing this modules folder before. When was this introduced as a convention?

**Comment by nek4life** [comment]
Also our server node_modules is rarely changed so watching shouldn't be an issue and it is only 8mb so initial upload would not be an issue either. Just to add some more context.

**Comment by SqrTT** [comment]
v1.1.0 respects "extension.prophet.ignore.list" now
