### ISSUE TITLE
attach the debugger issues

### ISSUE THREAD

**Issue by lm1435** [SqrTT/prophet#122]
anyone having issues with prophet debugger/VScode when trying to attach the debugger?

Today my whole team has this issue and we cant figure out how to get it to work.

{"name":"Error","message":"Unable to process commmand:DebuggerConfig"} is the error that pops up. \

THANKS!

**Comment by SqrTT** [comment]
Hi @lm1435 

thanks for reporting.  The issue is related to `Live Share` extension once removed/disabled debugger will work as before.

**Comment by lm1435** [comment]
you are the man!! 

Thanks!

**Comment by Strongground** [comment]
Hypothetically speaking: I don't have Live Share or anything remotely like that installed, and still have issues to connect with any instance (SIG/PIG) the whole day. Any other idea why?
Error description: I klick "Connect", it loads, and loads, and loads ... forever.

**Comment by SqrTT** [comment]
@Strongground 
so you don't have `Unable to process commmand:DebuggerConfig` message?  Probably you faced a different issue than this.

**Comment by SqrTT** [comment]
PS. in light of the issue: try to disable all other extensions and see if it helps

**Comment by Strongground** [comment]
I disabled all extensions except Prophet and restarted VSCode, and the machine itself, and the instance as well. Still no luck.
As no error message is shown, where do I find helpful log messages? Is there some way to increase verbosity?

**Comment by Strongground** [comment]
Apparently the problem exists for more people, I just heard from a colleague across the country that they have problems with the latest VSCode + Prophet and debugger. Uploading works fine. Will create a new issue.

**Comment by SqrTT** [comment]
root case https://github.com/MicrosoftDocs/live-share/issues/249

**Comment by chenchenalex** [comment]
@SqrTT amazing problem solver!
