### ISSUE TITLE
Pipeline support

### ISSUE THREAD

**Issue by Bbemol** [SqrTT/prophet#123]
Hi!
I love your plugin, I've been using it for the past weeks and it works well. I would hope one day to have the pipeline support. I know this should disappear, but unfortunately we're still using it and it takes time to migrate everything to controllers...;
Thx

**Comment by SqrTT** [comment]
Hi @Bbemol,
 unfortunately, I don't have time to add pipeline support. 

Anyway, I would be happy to see PR with such feature.

**Comment by Strongground** [comment]
Instead of dedicating time to support this dying abomination of a technology, just spend the time refactoring pipelines into code.

**Comment by SqrTT** [comment]
closing. duplicated #52
