### ISSUE TITLE
Attaching debugger not possible

### ISSUE THREAD

**Issue by Strongground** [SqrTT/prophet#124]
When trying to attach the debugger to any instance, with an untouched configuration that worked a few days ago, the operation does neither complete successfully nor times out. Instead it shows the loading bar forever, I tried for ~1.5h without any visible change, apart from the VSCode performance dropping like a rock in water.

Restarting instances (SIG, PIG), restarting the developers machine, restarting VSCode, disabling all plugins except Prophet, did not yield any results.

I don't get any error message, it just loads forever, trying to attach the debugger. The problem does not occur when using Bart (with Atom IDE) or Eclipse's built-in debugger.

**Comment by lm1435** [comment]
We noticed some changes when vscode updates too. we've stuck with 1.24 and prevent vscode from updating to prevent further issues.

**Comment by SqrTT** [comment]
VSCode team have a major update of Electron (to 3.0.0). Probably this is causing an issue. closing since this is not actual yet
