### ISSUE TITLE
Problem with Prophet Debugger

### ISSUE THREAD

**Issue by EwaSFCC** [SqrTT/prophet#127]
Prophet Debugger stoped working on 29/08/2018. Those are the screenshots with error messages i'm getting:
![screenshot 7](https://user-images.githubusercontent.com/42836538/44848807-6bc56c00-ac58-11e8-99ba-f9c18c424f9f.png)
![screenshot 6](https://user-images.githubusercontent.com/42836538/44848812-6e27c600-ac58-11e8-9a65-acf402fbaccb.png)
![screenshot 5](https://user-images.githubusercontent.com/42836538/44848818-6ff18980-ac58-11e8-8687-f761b66a28e1.png)

**Comment by SqrTT** [comment]
Could you please check if your issue is not similar to #122 ?

**Comment by EwaSFCC** [comment]
thx. it's working now.
