### ISSUE TITLE
Debugger won't start

### ISSUE THREAD

**Issue by nykolak** [SqrTT/prophet#128]
I'm having problems with Debbuger, it won't start/connect to the sandbox. Cartridges uploading is working fine, but for some reason, Debbuger is not working. This is my Debug config, I'm I missing something? When I press start nothing is happening.

![image](https://user-images.githubusercontent.com/18286669/45257642-f1a88c00-b3a9-11e8-8fa8-cd2164bebfc8.png)

**Comment by SqrTT** [comment]
Hi @nykolak 
Your config looks fine. 
Could you please try to disable other extensions and try if the prophet works alone?

**Comment by nykolak** [comment]
Yup, that did the trick! Thanks!

**Comment by nickcooley** [comment]
I've tried the same and while I see the "successfully connected" message, breakpoints in Controller files don't seem to get hit.  Are those excluded from debugger?

**Comment by SqrTT** [comment]
Hi @nickcooley 
https://github.com/SqrTT/prophet/issues/92#issuecomment-379307016 is this your case too?

PS. Controller are not excluded
