### ISSUE TITLE
Unexpected token error on expanding variable

### ISSUE THREAD

**Issue by suaterken** [SqrTT/prophet#13]
Hello,
I've faced bug on expanding variable on debug.
1. Put debug on line,
2. When i expand "product" variable in left panel, in both editors (javascript and dwscript) it blows, other variables don't cause any bug

Note: Same case, i can expand product variable in eclipse without errors.

Pictures below;

![error0](https://cloud.githubusercontent.com/assets/7967939/26341405/349ca498-3f9c-11e7-8736-f8201655e568.PNG)

![error](https://cloud.githubusercontent.com/assets/7967939/26341404/349701d2-3f9c-11e7-8707-6bb3732d4082.PNG)

**Comment by SqrTT** [comment]
thanks for the report. I'll try to reproduce.

**Comment by SqrTT** [comment]
Hi @suaterken ,

Finally, I've reproduced this issue and made a fix in v0.5.1. Could you please verify if this solves this issue for you?


Thank you.

**Comment by suaterken** [comment]
Hello @SqrTT ,

It seems works like a charm :) 

Thanks
