### ISSUE TITLE
Debug: objects not expanding in watch

### ISSUE THREAD

**Issue by poebrand** [SqrTT/prophet#134]
'req.form' object is not expanding in the watch list and neither is 'req'. Although 'req' is expanding in the variables list. Please see screenshot:

![image](https://user-images.githubusercontent.com/737504/45902432-46c9a200-bd9b-11e8-8772-fd7f8538e5f7.png)

**Comment by SqrTT** [comment]
hi @poebrand 

thanks for reporting

Could you please check if it is fixed for you in v1.0.18?

**Comment by poebrand** [comment]
Thanks @SqrTT. v1.0.18 definitely improved things in the watch. However, there appears to still be an issues with missing members on expand. Here's an example where 'req.form' exists but it doesn't show in the expansion of 'req'. Likewise with the members of 'req.form'.

![image](https://user-images.githubusercontent.com/737504/45966128-212cda80-bfdf-11e8-89fe-4663855a4e60.png)

**Comment by SqrTT** [comment]
this isn't an issue of extension, this is because `form` is defined via getter:
```
    Object.defineProperty(this, 'form', {
        get: function () {
            return getFormData(request.httpParameterMap, this.querystring);
        }
    });
```
property isn't enumerable so it's missing in list but avaliable if accesssed directly [(details).](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Description)

**Comment by SqrTT** [comment]
closing since initial issue is fixed

**Comment by SqrTT** [comment]
@poebrand  thanks for the info. Unfortunately, SFCC is not based on V8 (we have Rhino inside). Moreover, debugger API is proprietary (see docs for SDAPI). API doesn't have methods for watching variables, current (and previous) implementation is implemented in a hacky way...
