### ISSUE TITLE
Unable to debug 'Sites' scripts

### ISSUE THREAD

**Issue by k-jahn** [SqrTT/prophet#138]
First off, thanks for the great plugin!

As far I can Tell, the debugger does not hit breakpoints when the box runs a script on the 'Sites' scope (example: organisation-wide jobs).
For comparison, in UX-Studio, it is possible to specify the scope within the debug config.

**Comment by SqrTT** [comment]
Hi @k-jahn 

debugger hits organization jobs (well at least for me) and doesn't require to specify the scope.

**Comment by k-jahn** [comment]
Hey,

thanks for the quick response.
Restarting my sandbox cleared up the problem. :)
