### ISSUE TITLE
Incompatible Extensions

### ISSUE THREAD

**Issue by sm0k3yj03** [SqrTT/prophet#139]
So this is not really an issue than "a list" of Extensions which will not work with prophet.
for myself **VS Live Share** needs to be disabled (for workspace)

Please provide more if you know any and it would be nice if this could either be fixed or documented in the README

**Comment by SqrTT** [comment]
I don't have such list. Regarding `VS Live Share` this is a bug of VS Live Share and they will fix it soon, so it may change over time.

**Comment by SqrTT** [comment]
this should be fixed in VS Live Share, nothing I can do here
