### ISSUE TITLE
isprint tag has more encoding types than on and off

### ISSUE THREAD

**Issue by christopher-j-liotta-accenture** [SqrTT/prophet#141]
SFRA code has:

`<isprint value=" ${category.url}" encoding="htmldoublequote" />`

**Comment by estebanMex** [comment]
Hello, 
I see in documentation the posibles values for encoding:
context can be one of the following values:

htmlcontent: encodes a given input for use in a general context.
htmlsinglequote: encodes a given input for use in an HTML Attribute guarded by a single quote.
htmldoublequote: encodes a given input for use in an HTML Attribute guarded by a double quote.
htmlunquote: encodes a given input for use in an HTML Attribute left unguarded.
jshtml: encodes a given input for use in JavaScript inside an HTML context.
jsattribute: encodes a given input for use in JavaScript inside an HTML attribute.
jsblock: encodes a given input for use in JavaScript inside an HTML block.
jssource: encodes a given input for use in JavaScript inside a JavaScript source file.
jsonvalue: encodes a given input for use in a JSON Object Value to prevent escaping into a trusted context.
uricomponent: encodes a given input for use as a component of a URI.
uristrict: encodes a given input for use as a component of a URI.
xmlcontent: encodes a given input for use in an XML comments.
xmlsinglequote: encodes a given input for use in an XML attribute guarded by a single quote.
xmldoublequote: encodes a given input for use in an XML attribute guarded by a double quote.
xmlcomment: encodes a given input for use in a general XML context.
