### ISSUE TITLE
Unable to upload node_modules folder

### ISSUE THREAD

**Issue by aduponchel** [SqrTT/prophet#145]
Hi,

I am unable to upload node_modules directories in my sandbox even if I change the configuration `extension.prophet.ignore.list` to allow node_modules to be processed.

It is a real need for our compagny to upload some node_module explicitely because we have made some npm module porting to Salesforce B2C Commerce and our implementation use node_module folder to allow an easier upgrade procedure.

I think the issue come from this line :

https://github.com/SqrTT/prophet/blob/15acafa5b886143a9a8b992cf89f4fa1c57921ae/src/server/WebDav.ts#L236

The walker seems not work with node_modules.

Is there performance related topic to know about this hard coded exclusion ?
I am not familliar with TypeScript and TypeScript transpiller.

**Comment by SqrTT** [comment]
duplicate #120
