### ISSUE TITLE
Link to repo not working for definitions for Commerce Cloud objects

### ISSUE THREAD

**Issue by rdevisser** [SqrTT/prophet#146]
As described in the readme:
_Definitions for Commerce Cloud objects can be downloaded from repo_

Repo doesn't seem to exist anymore. Can we still get it from somewhere?
https://github.com/SalesforceCommerceCloud/dw-api-types

**Comment by SqrTT** [comment]
Hi @rdevisser 
Repo exists, you need access right to able to read it.

You should be a member of SalesforceCommerceCloud organization.
more details here https://xchange.demandware.com/docs/DOC-48237
