### ISSUE TITLE
Watch doesn't work in debbuger

### ISSUE THREAD

**Issue by Melir91** [SqrTT/prophet#149]
When I add some variable to the watch it returns **unresolved** this worked before

**Comment by SqrTT** [comment]
this is working for me. Could you please hare more details?

**Comment by Melir91** [comment]
Hello SqrTT, thanks for your fast reply, I am attaching a screenshot. I added session and request which are returned as **unresolved** which were available before as they are global variables, maybe SFCC changes something from their part

![image](https://user-images.githubusercontent.com/24312134/49732861-9a57d780-fc88-11e8-8dfe-e7e6c02108b5.png)

**Comment by SqrTT** [comment]
API allows getting access (read) only to local scope. 
> which were available before as they are global variables
they were never available, as far I  remember. Only if you save them in a local variable. ie `var sess = session`
