### ISSUE TITLE
Error: EPERM: operation not permitted, stat 

### ISSUE THREAD

**Issue by sellamiyas** [SqrTT/prophet#150]
Hi, any one here use VSCode, :
i get this error : "Error: EPERM: operation not permitted, stat" when i trying to upload my cartridges.

**Comment by SqrTT** [comment]
please check files permissions. I'm not sure this issue of extension.

Or is there a chance some file are deleted/modified during uploading (for instance via grunt/gulp/webpack)?

**Comment by abdullahobaidullah** [comment]
I'm also having the same issue since yesterday. 

it happens once it makes a zip file of some of the cartridge and tries to upload it. 

> Error: Error: EPERM: operation not permitted, stat ../cartridge1.zip

PS: none of the files are modified at the time of upload.

**Comment by SqrTT** [comment]
@abdullahobaidullah 
could you please confirm the file is not blocked by for instance by SourceTree or Antivirus etc.

**Comment by yasellami** [comment]
Hi, I think u have a problem when prophet upload cartridges to your sandbox, it crashes cause ur connection or something like that, so u can restart ur VS Code and delete all .zip file exist in ur project and retry to upload use prophet.
Or u can use WinCSP (is like FileZilla) for upload cartridges with webDav.

**Comment by danielloader** [comment]
Are all of you above using Windows 10? It happens to me too on windows 10 but suspect it could be related to windows file locking, either windows defender or some race condition on trying to delete a file being read.

**Comment by SqrTT** [comment]
One possible way I see here it's avoid writing to disk before upload and implement writing zip directly to network stream. But this will require some time to implement.

**Comment by SqrTT** [comment]
v1.1.0 don't write zip into disk anymore. So issue should be fixed. Could you guys confirm?
