### ISSUE TITLE
Paste Issues

### ISSUE THREAD

**Issue by dlferro** [SqrTT/prophet#156]
Attempting to paste text into an isml file I seem to get some extra spacing(1-2 tabs worth). I've tried toggling other linters and htmlhint from this package, but I'm still running into the issue.

**Comment by SqrTT** [comment]
Could you please add some examples, so I can reproduce this thing?

**Comment by dlferro** [comment]
I've actually gotten around it by turning off format on paste in vscode. Going to close for now.

**Comment by dlferro** [comment]
@SqrTT I'm going to reprise this issue. Here's a quick video of modifying the suggestions.isml file.
https://drive.google.com/file/d/1GH3Mz0aIzafX4HJyjIBzRxuWOiKnAGZ3/view?usp=sharing let me know if there's anything else that might help you identify what would cause this.

**Comment by dlferro** [comment]
@SqrTT do you have any recommendations for how I might be able to determine what is causing this?

**Comment by SqrTT** [comment]
@dlferro 
This is happening because incorrect calculation of indentation in case line already has content.

Let's close this issue and track it in #221.
