### ISSUE TITLE
Sandbox-FileSystem in editor not showing the webdav location 

### ISSUE THREAD

**Issue by shine-thazhava** [SqrTT/prophet#158]
Hi,

It's not an issue. Just want to know any specific reason for not showing the webdav location?

Thanks,

**Comment by SqrTT** [comment]
Hi @shine-thazhava 
I'm not sure what do you mean under 'the webdav location'. Could you please add more details?

**Comment by shine-thazhava** [comment]
Hi @SqrTT 
Am not sure about this belongs to the prophet.
here showing my sandbox file system except webdav folder
![sandbox](https://user-images.githubusercontent.com/46553995/53888199-e1682580-4049-11e9-84a5-050e334bfa74.png)

**Comment by SqrTT** [comment]
yes, this is part of extension, 
But not clear what is `webdav location`.

**Comment by matthewrose** [comment]
@SqrTT This is taking a pre-existing workspace and adding another directory to it which is causing it to show as "Untitled". Then if you save that workspace, and reopen it the Sandbox - FileSystem functionality that has been added in the new version doesn't work any longer.

**Comment by shr1k4nt** [comment]
I am getting this too in the explorer tab. Just opened a previously used workspace, didn't add any new folder to it.

![settings_ _untitled__workspace_](https://user-images.githubusercontent.com/4485699/53951375-99d7ad00-40ce-11e9-9037-4f850a32390c.png)

**Comment by matthewrose** [comment]
@SqrTT 
I made a video so you can see the issues I describe.

- First, after opening the workspace directory in VSCode, it changes to "Untitled" 
- Then I try saving the new untitled workspace as "test" and then closing and reopening it. After that, there is an issue with retrieving the webdav "FileSystem"

https://www.screencast.com/t/sTMM3cxlzN

**Comment by rzaffalon** [comment]
+1 on the issue of having "Untitled" as the Workspace name after prohet adds the `Sandbox-FileSystem`, which breaks the compatibility con other extensions that work with Workspaces, like "Project Manager".

**Comment by SqrTT** [comment]
feel free to disable feature via `extension.prophet.sandbox.filesystem.enabled`

**Comment by rzaffalon** [comment]
@SqrTT thank you for the heads up! Really appreciate it

**Comment by matthewrose** [comment]
@SqrTT By the way, I tried out the latest version again today and saw that if you wait long enough the FileSystem does update the list of files.

However, the warning indicator is still present, so I'm sot sure if there is some way to clear that state after the FileSystem update script is done running.

![image](https://user-images.githubusercontent.com/918428/55200357-c3df3500-518b-11e9-94bc-075a0a158470.png)


Not a big deal but thought you should be aware if you weren't already.

**Comment by SqrTT** [comment]
this should be fixed in v.1.3.3

**Comment by SqrTT** [comment]
closing feel free to reopen if reproduces
