### ISSUE TITLE
Setting to disable Sandbox-FileSystem folder.

### ISSUE THREAD

**Issue by Pronian** [SqrTT/prophet#160]
Hello!

I have several linting tools enabled and adding another folder to my workspace breaks them. I would like to disable this new feature so that I can continue with my current workflow.

Thanks!

**Comment by aduponchel** [comment]
Same here please. I have a shared workspace which could not be versionned.
I don't think you can enable it without using workspace scope, however you should provide an option to disable it.

**Comment by aduponchel** [comment]
But it is a nice feature btw 👍

**Comment by davishen** [comment]
I'm also experiencing this issue. It breaks the stylelint extension :/

**Comment by SqrTT** [comment]
Made configurable via `extension.prophet.sandbox.filesystem.enabled` so feature may be disabled.

PS. stylelint doesn't support remote file systems so it fail to start. Filed issue for this: https://github.com/shinnn/vscode-stylelint/issues/266

**Comment by Pronian** [comment]
Thanks a lot for this feature! Works Great!
