### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by juanpenarandaosf** [SqrTT/prophet#163]
Hello,

I thought it would be nice to have a linter for the code, like `tslint`. I could work on this and open a PR. Would you be interested on it?

**Comment by SqrTT** [comment]
Hi.
Not sure if this is needed since VSCode with built in linter based on TypeScript. All you need add/configure `jsconfig.json` for your project and add types from here: https://github.com/SalesforceCommerceCloud/dw-api-types

PS. by default you get code assistance but if set `checkJS: true` editor will lint the code including linting of types.

**Comment by SqrTT** [comment]
you may check docs https://marketplace.visualstudio.com/items?itemName=SqrTT.prophet and here https://code.visualstudio.com/docs/languages/jsconfig

**Comment by juanpenarandaosf** [comment]
Sorry, I got confused here. I was talking about linting the prophet repository code, like the files on `src`

**Comment by SqrTT** [comment]
yeap, my mistake...
repository code is written on TypeScript so it already is kinda  linted.
Or are you  talking about lint a code style? I see no much benefit from there, I would vote to do some stuff which is more useful and end user will see it or workwith.

**Comment by juanpenarandaosf** [comment]
yes, I'm talking about adding a code style, like using the "recommended" `tslint` rules, but this is of course if you see it has any value to the future development or maintenance. 

I created a branch on my fork and here is an example on what would change: https://github.com/SqrTT/prophet/compare/master...juanpenarandaosf:feature/lint

**Comment by SqrTT** [comment]
this would have a sense is there was a lot people which work on the project. But this is not a case.
