### ISSUE TITLE
Changes to OCAPI and WebDAV -- is SNI supported?

### ISSUE THREAD

**Issue by braincomb** [SqrTT/prophet#164]
Hello,

Salesforce has been sending ACTION REQUIRED emails regarding their changes to the environment, all custom-built OCAPI and WebDAV client applications will need to support Server Name Indication (SNI) to ensure uninterrupted access to the Commerce Cloud service by April 1st, 2019.

Does this affect this extension in anyway, and if so, will it continue to work? Apologies in advance if this is unrelated.

**Comment by SqrTT** [comment]
the extension relays on `request` library which support SNI
