### ISSUE TITLE
prophet debugger upload 

### ISSUE THREAD

**Issue by edelmtl** [SqrTT/prophet#168]
Hello --

Is there a way with this extension to only upload modified file instead of uploadin the entire cartridges all the time?

**Comment by SqrTT** [comment]
hi, the extension uploads only changed files. If it's not true for you please explore logs  there should be a reason for it. There was similar issues please check if they cover your case, for instance https://github.com/SqrTT/prophet/issues/117

**Comment by SqrTT** [comment]
@edelmtl is your issue resolved?

**Comment by edelmtl** [comment]
Yes thanks.

**Comment by DevVIN** [comment]
@SqrTT 
am also facing the same issue can you please provide the solution here it would be really helpful
