### ISSUE TITLE
Feature Request for <!--- ---> comments

### ISSUE THREAD

**Issue by Jakobud** [SqrTT/prophet#169]
SFCC ISML supports both `<comment></comment>` and `<!---``--->` (note 3 dashes not 2) comments. It would be nice if Prophet had a settings where you can choose which type of comment you use when using the comment shortcut (Cmd + /).

**Comment by SqrTT** [comment]
the extension uses `iscomment`. `<!---` is deprecated.

![image](https://user-images.githubusercontent.com/1271300/57084183-80d02e80-6d02-11e9-8e1a-918e2f081e36.png)

**Comment by Jakobud** [comment]
Oh wow I had no idea that was deprecated. Thanks!
