### ISSUE TITLE
Prophet not watching files

### ISSUE THREAD

**Issue by amidongarrett** [SqrTT/prophet#170]
Using VS Code Version 1.32.3 (Mac)
Prophet Version 1.1.2

Config:

<img width="658" alt="Screen Shot 2019-05-06 at 10 43 36 AM" src="https://user-images.githubusercontent.com/10519190/57243806-d9961480-6feb-11e9-81ea-d78d7f10305e.png">

When making changes to files, the only way I can get Prophet to upload is to do a Clean Project/Upload All. 

Thanks!

**Comment by Finrael** [comment]
I have pretty much the same issue, I have to manually update all the files every time I make a change

**Comment by SqrTT** [comment]
Hi, thanks for reporting.
Could you please share an output of uploader?

![image](https://user-images.githubusercontent.com/1271300/57287014-3e6e6f00-70bf-11e9-8faf-54b21cd3cd34.png)

**Comment by amidongarrett** [comment]
Here you go!

![Screen Shot 2019-05-07 at 9 59 01 AM](https://user-images.githubusercontent.com/10519190/57318297-d57efb00-70ae-11e9-995a-59383834edda.png)

**Comment by Melir91** [comment]
Hello, I have the same issue after clean it upload changed files and after that it freeze

**Comment by SqrTT** [comment]
please confirm you haven't configured skipping files form watching. For instance via 
```
"files.watcherExclude": {}
```
PS. the extension relays on VSCode watcher so if files not being uploading means VSCode watcher don't report changes.

**Comment by amidongarrett** [comment]
<img width="1020" alt="Screen Shot 2019-05-21 at 10 17 02 AM" src="https://user-images.githubusercontent.com/10519190/58116634-a50c8600-7bb1-11e9-8917-7e3a2b3f89f4.png">
The only thing I have in my watcher exclude are git related files and node_modules. I don't believe this should be causing an issue.

**Comment by amidongarrett** [comment]
I just updated my VSCode to the latest version (1.34) and it seems that everything is working again. I don't know if this was the root cause, but maybe this will help others as well.

**Comment by SqrTT** [comment]
@Finrael @Melir91 
Guys, could you please check if you have issues in new version?

**Comment by SqrTT** [comment]
also please check if you have `cartridge` option in your `dw.json`. If you have then list all required cartridges or remove option so the extension will automatically figure out list of cartridges.

**Comment by Finrael** [comment]
@SqrTT I downloaded the most recent version of Visual Studio Code and this seems to be resolved now

**Comment by Melir91** [comment]
@SqrTT it works well again, thank you :)
