### ISSUE TITLE
Allow extension.prophet.sandbox.filesystem.enabled to work as a workspace setting

### ISSUE THREAD

**Issue by matthewrose** [SqrTT/prophet#171]
Currently I can't use `extension.prophet.sandbox.filesystem.enabled` as a workspace setting. I must toggle it on the User-level.

Ideally, since I don't just work on Salesforce B2C Projects I would like to have workspaces set up with or without Prophet or this feature enabled. Please let me know if I'm missing some other setting to handle this.

**Comment by SqrTT** [comment]
implemented in 1.2.44

**Comment by SqrTT** [comment]
closing
