### ISSUE TITLE
SFRA debug doesn't show all data in req object

### ISSUE THREAD

**Issue by Melir91** [SqrTT/prophet#175]
Hello, I found that **req** object contains more data than it's visible in prophet debugger. There have to be **req.querystring** which hold incoming parameters. Also session, form and currentCustomer must be there too.
![image](https://user-images.githubusercontent.com/24312134/59430651-8b92de80-8deb-11e9-8434-90df3b4970fb.png)

**Comment by SqrTT** [comment]
Hi @Melir91 
thank you for reporting.
Unfortunately, mentioned properties defined via Object.defineProperty and will be invisible since they do not exist until called (will be visible if enumerable: true) because of they are getters. So this isn't issue of extension,

**Comment by Melir91** [comment]
Okay, thank you @SqrTT for your fast reply, will try to find a solution with SFCC support.
