### ISSUE TITLE
Code uploading failure due to password format

### ISSUE THREAD

**Issue by AndreyPristupa** [SqrTT/prophet#181]
Hey

Issue: when I set up the password like `String=-0000` plugin throwing an error:

`Connection validated successfully
Current active version is: 123
Start uploading cartridges
Cleanup code version...
Error: Error: Not Found `

When I changing the password to `String=-1` - everything goes work*

*Yes, I've tripple checked my password, ten times switched code versions, VSCode was rebooted along with my PC. Code version name 146% same as in dw.json

Thanks.

**Comment by SqrTT** [comment]
Hi @AndreyPristupa 
I believe this is not actual at this point.

please reopen if needed
