### ISSUE TITLE
ISML autocomplete inserts a space at the end of self-closing <is*> tags

### ISSUE THREAD

**Issue by karsov-westum** [SqrTT/prophet#189]
The autocomplete feature inserts an extra space at the end of self closing tags which are not parsed properly by SFCC.

Example:
`<iscontinue />`
`<isbreak />`
Neither of the two is recognized by SFCC

Expected:
`<iscontinue/>`
`<isbreak/>`

**Comment by SqrTT** [comment]
Hi @karsov-westum 
Thanks for reporting, Could you please share version of used extension?

**Comment by karsov-westum** [comment]
Hi @SqrTT,
Mine is: v1.1.9
VS Code: v1.38.1

**Comment by SqrTT** [comment]
Do you use some external formatter? Since extension already handle those cases.
Could you try to reproduce issue with disabled other extensions?

Codebase:
https://github.com/SqrTT/prophet/blob/master/src/server/langServer/services/htmlFormatter.ts#L144-L150

**Comment by karsov-westum** [comment]
I am on Ubuntu 18.04 LTS
VS Code: 1.39.2

![image](https://user-images.githubusercontent.com/42265543/67197937-8895a380-f406-11e9-8ae4-95e1d0f4d9d6.png)
I have disabled all other extensions. Only Prophet v1.2.1 is installed. Restarted VS Code.
And the auto complete still inserts an empty space.
![image](https://user-images.githubusercontent.com/42265543/67198025-be3a8c80-f406-11e9-83c8-3ee10a4cdf3a.png)

Regards,
Kris

**Comment by SqrTT** [comment]
Could you please verify in new version 1.2.2 of extension, please?

**Comment by karsov-westum** [comment]
I confirm that it works correctly with v1.2.2
No extra space is added.

**Comment by SqrTT** [comment]
great, thank you @karsov-westum .
Closing issue. Feel free to reopen if face issue again.
