### ISSUE TITLE
dw.json cartridgeResolution has only default option: "ask" and a typo

### ISSUE THREAD

**Issue by karsov-westum** [SqrTT/prophet#194]
Ubuntu 18.04
VS Code: 1.39.2
Prophet: 1.2.2

Looking at the allowed parameters for dw.json there is: *cartridgeResolution* which could only be *ask*.
However looking at this commit I saw there is a typo:https://github.com/SqrTT/prophet/commit/5c6287365058836f6c1b766af3512e4470f46de8#diff-a49775381243543a4c6352a510dc4394R90

Instead of *cartridgeResolution*, *cartrigeResolution* is used.

Maybe fixing this typo and adding the allowed options in: *syntaxes/dw.schema.json*
- ask
- remove
- leave
will prevent the popup which asks the developer how to treat extra cartridges on the sbox.

Regards,
Kris

**Comment by SqrTT** [comment]
Hi @karsov-westum 
Great catch. Fixed in master (will be delivered in next release)

Thank you.

**Comment by karsov-westum** [comment]
Welcome :)

Could you please update the CHANGELOG.md and the README.md

Thanks
