### ISSUE TITLE
400 Bad Request on "Clean Project/Upload All

### ISSUE THREAD

**Issue by davishd** [SqrTT/prophet#195]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - VSCode version
 - The extension version [e.g. 22]

**Additional context**

**Comment by SqrTT** [comment]
@davishd 
thanks for reporting.
But what should I do with this issue? How to reproduce an error? Since I don't have such...

**Comment by davishd** [comment]
@SqrTT Sorry, I'm not sure how this was draft published. Please see https://github.com/SqrTT/prophet/issues/196 for detailed information on this.
