### ISSUE TITLE
Cartridge modules missing in upload

### ISSUE THREAD

**Issue by challmannsf** [SqrTT/prophet#197]
**Describe the bug**
 cartridges from storefront-reference-architecture are not uploaded within Prophet 1.2.3

**To Reproduce**
Steps to reproduce the behaviour:

Create 2 directories to upload cartridges from

1. commerce-cloud-code
       |
        --- cartridges
            |
            ---- app_client

2. storefront-reference-architecture
       |
        --- cartridges
            |
            ---- app_storefront_base
            ---- modules

Do not enter cartridge property in  `dw.json`

e.g
```
{
    "hostname": "dev02-web-foobar.demandware.net",
    "username": "someuser@somecompany.com",
    "code-version": "code"
}
```

**Expected behavior**
All cartridges are uploaded

**Desktop (please complete the following information):**
 - OS: iOS
 - VSCode version:  1.39.2
 - The extension version: 1.2.3

**Comment by SqrTT** [comment]
Prophet is uploading only cartridges. Cartridge is detected via `.project` file with next content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
    <name>modules</name>
    <comment></comment>
    <projects>
    </projects>
    <buildSpec>
        <buildCommand>
            <name>com.demandware.studio.core.beehiveElementBuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
    </buildSpec>
    <natures>
        <nature>com.demandware.studio.core.beehiveNature</nature>
    </natures>
</projectDescription>
```

Could you, please, confirm you have such file and the file is not in ignore list?

**Comment by challmannsf** [comment]
Yes the .project file exists and within 1.2.1 it is working. I can reproduce it within the latest version

**Comment by hnestmann** [comment]
I can confirm the issue. Maybe our strange repository setup causes this
https://ibb.co/stZjTBt
We keep SFRA and custom cartridges separate so we can exclude it easily from test coverage requirements and ESLint

**Comment by challmannsf** [comment]
I think this is also caused by the fact that the `modules` folder does not include  a `cartridge` folder as the other cartridges does

**Comment by challmannsf** [comment]
@SqrTT my bug is somewhat missleading as I discovered.
Not only the `modules` folder is missing.
It is like @hnestmann said, we have 2 different directories as we use SFRA as a dependency.
`commerce-cloud-code`
`sfra`

On upload only the cartridges in `commerce-cloud-code` remain on webdav but not the cartridges in `sfra`

**Comment by challmannsf** [comment]
@hnestmann @SqrTT I found the error while debugging (again @SqrTT thanks for the fantastic extention)

@hnestmann  the issue is - we are cloning SFRA as a node_module while installing the project.
after this, we are doing an `rsync` but we do not delete the sfra node_modules folder after this.
This causes the same cartridges to be existant twice which will result in unexpected deletion.

I think this is a very project specific error so I will close this issue here

**Comment by SqrTT** [comment]
ok, but still not clear why this appears only in v1.2.3...

**Comment by SqrTT** [comment]
do you have two `modules` cartridges? Could you share uploading log output, related to `modules`, please?

**Comment by challmannsf** [comment]
@SqrTT yes due to the fact the we use sfra as a node_modules dependency.

In the end our structure looked like that

```
node_modules
         |
         |--- sfra
                   |---- modules
                   |---- app_storefront_base
storefront-reference-architecture
         |---- modules
         |---- app_storefront_base

commerce-cloud-code
         |----- app_client_code
```

**Comment by SqrTT** [comment]
in that case you may try to add  `node_modules/sfra` to `files.exclude` as work around...

**Comment by cilusanirakesh** [comment]
HI All,

npm run upload Cartridge - Will upload app_storefront_base, modules and bm_app_storefront_base to the server. I would like to know the process for only uploading the customized cartridges to the server instead of SFRA provided cartridges because we will not be doing any custom changes in the SFRA provided cartridges .We would like to build only custom cartridges to the server please help me here.
