### ISSUE TITLE
[Develop branch] code upload not working

### ISSUE THREAD

**Issue by challmannsf** [SqrTT/prophet#201]
**Describe the bug**
Code upload does not work on develop branch

**To Reproduce**
Run `Prophet: Enable upload`

**Expected behaviour**
Code upload works

It seems there are a lot of code updates in parallel ongoing which causes the error.

<img width="606" alt="Screenshot 2019-10-31 at 12 58 48" src="https://user-images.githubusercontent.com/48258604/67944997-314dbb00-fbde-11e9-8b54-0b3d3e8da156.png">

**Comment by SqrTT** [comment]
please use `master` branch as target for PRs

**Comment by challmannsf** [comment]
@SqrTT thanks so I can basically ignore the `develop` branch mostly?

**Comment by SqrTT** [comment]
correct. `develop` is useful to coordinate bunch of people but this is not our case.
