### ISSUE TITLE
Enhancement for dw.json config detection

### ISSUE THREAD

**Issue by antondyachuk** [SqrTT/prophet#205]
**Problem**: If workspace folder contain more then one dw.json file it takes the first one:
_return configFiles[0].fsPath_
In case if this first file has empty json (for example, paypal [cartridge](https://github.com/SalesforceCommerceCloud/link_paypal/blob/master/dw.json))
it is used and subsequently plugin can't upload cartridges due to missing credentials

**Comment by SqrTT** [comment]
Why would project require more then one `dw.json` for workspace?

What behavior is expected in this case?

**Comment by antondyachuk** [comment]
The project doesn't require it. We just used paypal cartridge as it is from Salesforce github with empty dw.json. At the same time project has custom cartridge with correctly filled dw.json

**Comment by SqrTT** [comment]
please report issue in Salesforce/paypal github

**Comment by SqrTT** [comment]
credentials in repo is never a good idea

**Comment by antondyachuk** [comment]
Totally agree. But it would be nice to validate dw.json in prophet debug on credentials presence.
Also I remember prophet used to show choice if there are few dw.json files in project, now it does not work. Did you change it?

**Comment by SqrTT** [comment]
It still works. But it works in case separate workspaces.
What means validate? Try to connect to sandbox and see they are correct? 
This would be redundant since anyway you figure out incorrect credentials (more over you will have error in upload console already)

**Comment by antondyachuk** [comment]
No, I just mean emptiness check for next case:
![image](https://user-images.githubusercontent.com/43670463/69877611-5744a900-12cb-11ea-8433-09f93931ed8c.png)

**Comment by SqrTT** [comment]
let's imagine we handle this case... and dw.json is invalid want we will do next?
Current behavior will show that credentials is incorrect, already.

**Comment by antondyachuk** [comment]
**Currently it works in next way:**
1. Takes first dw.json 
2. Upload files or show error if dw.json in invalid

**My suggestion:**
1. Filter dw.json files by presence of username, password, hostname
2. Upload files or show error if there is no valid dw.json

**Comment by SqrTT** [comment]
Sorry, presence of username or password doesn't mean configuration is valid but cover only this case with paypal. And there not reason to change code(lookup logic) for it.
