### ISSUE TITLE
Add support for dw.js file so comments can be used

### ISSUE THREAD

**Issue by gkkirilov** [SqrTT/prophet#207]
**Is your feature request related to a problem? Please describe.**
I would love to be able to comment settings out of the dw.json but json format does not support them

**Describe the solution you'd like**
Add support for dw.js file which exports a json and we can use comments within it
Nuxt.js project has a file which is working that way nuxt.config.js [Example](https://github.com/nuxt/nuxt.js/blob/dev/examples/axios/nuxt.config.js)

**Comment by SqrTT** [comment]
hi @gkkirilov 
thanks for idea with JS file. Except comments this probably  may allow to have different logic  in `dw.js`, lets say store password in secure way.

**Comment by gkkirilov** [comment]
Yeah, that's what I am doing in my other projects I have added .env file and fetch the data with [dotenv](https://www.npmjs.com/package/dotenv). It is really handy.

**Comment by SqrTT** [comment]
implemented by @Eneris
