### ISSUE TITLE
Extension is watching .isml.git files

### ISSUE THREAD

**Issue by rmkpatchaasf** [SqrTT/prophet#208]
**Describe the bug**
The extension is listening on .isml.git files.

**To Reproduce**
1. Open a project
2. Open output view
3. Edit a file and watch file uploads.

**Expected behavior**
.isml.git files should not be listened on.

**Screenshots**
<img width="824" alt="Screen Shot 2019-12-16 at 11 48 12 AM" src="https://user-images.githubusercontent.com/52654550/70901115-7006cb80-1ffa-11ea-9d55-49210d7acf5b.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - VSCode version : 1.41
 - The extension version : 1.2.4

**Additional context**

**Comment by SqrTT** [comment]
hi @rmkpatchaasf 
thanks for reporting. The extension watches all files inside your cartridges. If you need to skip some files use `files.watcherExclude` option in VS Code, please.

**Comment by rmkpatchaasf** [comment]
I think it's working now. I didn't have to do it until now. Maybe an update in VSCode.

**Comment by rmkpatchaasf** [comment]
So, I've tried this but not working...

```
"files.watcherExclude": {
      "*.isml.git": true
    },
```

**Comment by jkol** [comment]
This started happening to me as well.

**Comment by fenomchris** [comment]
I have this same issue. I've tried:

	`"files.watcherExclude": {
		"*.git": true
	}`

**Comment by davishd** [comment]
I'm having the same issue as well. I have also tried to update the "watcherExclude" option with no effect.

This causes file watcher to error out frequently and when doing anything git related (stashing files, etc.) 

`Error: Error: ENOENT: no such file or directory, lstat '/Users/user/projects/src/project-name/cartridges/cartridgeA/cartridge/client/default/scss/product/detail.scss.git'`

**Comment by unraveledideas** [comment]
Having the same issue. Tried adding .git and .isml.git to watcherExclude with no luck. Seems after any git related activity the watcher fails and Prophet Uploader follows.

**Comment by ohnoitsfraa** [comment]
Definitely a VS Code issue, rolling back to 1.40.0 (October) did the trick and Prophet now works fine.

**Comment by gkkirilov** [comment]
Got the same problem
Is there an issue raised in the vscode repo? I can't find a similar one to this problem?

**Comment by jkol** [comment]
Searched through the vscode repo issues list and couldn't find anything that seems like it's this issue.

**Comment by andrii-lazarenko** [comment]
It seems like these files "*.git" are generated by Sourcetree, probably new changes that are not compatible with extension.

**Comment by manifestinteractive** [comment]
This is also happening for the majority of the people in my company.  With `.scss` files as well.  Seeing log messages like:

```
Watching files
[U 02:13:25] /app_client_base/cartridge/client/default/scss/modules/hero/_hero-main.scss.git
```

**Comment by suragar** [comment]
This is happening to me as well with all types of file. After which the automatic upload for any other file stops.
![image](https://user-images.githubusercontent.com/17794782/71066765-5059d980-2199-11ea-9861-f53cca9e65eb.png)

**Comment by manifestinteractive** [comment]
Temporary Solution Found:
---

OK, so I played around with a solution and got something working.  There is an `extension.prophet.ignore.list` setting that you can tweak, and adding `\\*.git$` to this list resolves the issues for me.  Tested with ISML, JS & Scss files with success.

You can give this a go to by going to `Code > Preferences > Settings` and searching for `prophetignore`.  Here is a screenshot:

![screenshot 2019-12-18 at 2 56 09 AM](https://user-images.githubusercontent.com/508411/71067428-80c25900-2142-11ea-960f-98654fa64951.png)

Once you've found this section, click the `Edit in settings.json` file, then add the following at the top of the file and Save the file:

```json
"extension.prophet.ignore.list": ["node_modules", "\\.git", "\\.zip$", "\\*.git$"],
```

**NOTE:** I had to restart VS Code after updating this setting to get Prophet Debugger to use these new settings.  You might need to as well.

**Comment by gkkirilov** [comment]
I got a new warning and now it isn't uploading at all
`Cartridges ... does not exist on file system (or not determined as cartridge/s) while added in configuration. It will be ignored, please restart the uploader once this has been resolved.`

**Comment by rmkpatchaasf** [comment]
@manifestinteractive this seems to be working for me.

**Comment by manifestinteractive** [comment]
@gkkirilov any chance you have a malformed `settings.json` file ?

**Comment by gkkirilov** [comment]
@manifestinteractive Yep that is it, I commented the whole file and now it is working. Thanks

**Comment by manifestinteractive** [comment]
Cool, just submitted hopefully a super simple PR to review that should resolve this issue with an extension update ( vs having to manually update the settings file ) https://github.com/SqrTT/prophet/pull/209

**Comment by rmkpatchaasf** [comment]
@manifestinteractive it worked well but when I made a git push, it started happening again. :(

**Comment by rmkpatchaasf** [comment]
For reference, I am not using a single directory. I have a workspace with many cartridges in it.

**Comment by manifestinteractive** [comment]
@rmkpatchaasf ya, I have the same setup.  I had not done a git interaction yet, my test was just making code changes and checking the Prophet Uploader log output.  Before, I was seeing `*.git` files getting uploaded / watched every single time.  After the setting change, those stopped.

I'll see what happens here in a bit when I get to a point where I can commit / push code.

**Comment by rmkpatchaasf** [comment]
@manifestinteractive I've tested on another workspace and same result. Whenever I make a git commit, the extension starts watching .isml.git files again.

**Comment by manifestinteractive** [comment]
Ya, even a `git fetch` retriggers it ... digging into the code to see what is going on.

This looks like the line that should be matching the file pattern:

https://github.com/SqrTT/prophet/blob/master/src/server/WebDav.ts#L270

Currently testing different patterns in the `settings.json` file to see if maybe it's just bad regex on my end.

**Comment by manifestinteractive** [comment]
bummer, looks like according to the docs, that does not work for watching :(

```
* `extension.prophet.ignore.list` - list of regexp for files/folders should be excludes from zipping during clean (not from watching)
```

**Comment by manifestinteractive** [comment]
Ya, seems like the "correct" solution here would be to submit a PR that updates Prophet Debugger to honor the `files.watcherExclude` VS Code preference.  That way devs could specify patterns they know they want to exclude from being watched by this extension.

But as mentioned, this could also just be a weird VS Code bug.  But the attempts to work around the bug ( whatever is causing it ) is failing since the VS code method to exclude watched files was not setup.  I will see if I can take a stab at getting this added if it is desired functionality.

**Comment by SqrTT** [comment]
`watcherExclude` is already honored by VS Code, no need special support from the extension.

the real issue was with request library. Request library do not rise an error in case try to upload file which don't exists on filesystem. Uploader uploads 5 files at time, so 5 files started to upload but never hit callback from request lib (either success nor error) so it hangups in forever waiting..

the issue should be addressed in 1.2.5.

https://github.com/SqrTT/prophet/commit/93f8415acd7c32833f48e0876edb8f40ef47a848#diff-0a78b095cdd0b6f46d77c0361c0ca1d8R16-R26

Could you guys check and confirm it is working for you, please?

**Comment by gkkirilov** [comment]
@SqrTT It is working, thanks for the update

**Comment by rmkpatchaasf** [comment]
@SqrTT it is working. Uploads don't fail, but logs are continuously showing this : 

```
[! 13:16:12] /***/cartridge/templates/default/slots/content/menuItemBrand.isml.git (removed before uploaded)
[! 13:20:13] /***/cartridge/templates/default/slots/content/menuItemPerso.isml.git (removed before uploaded)
[! 13:20:13] /***/cartridge/templates/default/slots/content/menuItemBrand.isml.git (removed before uploaded)
[! 13:20:18] /***/cartridge/templates/default/slots/content/menuItemPerso.isml.git (removed before uploaded)
[! 13:20:18] /***/cartridge/templates/default/slots/content/menuItemBrand.isml.git (removed before uploaded)
```

**Comment by SqrTT** [comment]
correct, I'm assumeing to hide case in logs when file is flickering (created and removed immediately) may be not good idea. So added this message. Probably in feature hide it under verbose switch/flag.

**Comment by fenomchris** [comment]
This fix is working for me, thanks for the quick turnaround!

**Comment by manifestinteractive** [comment]
@SqrTT thanks for getting to the root of this.  Seems to be working :)

Sorry for the multiple posts.  It was my first dive into your extensions code.  Was hoping I could help figure out what was going on... but clearly main contributors know way more about how this extension actually works.  Thanks for tracking down the actual issue.

**Comment by rmkpatchaasf** [comment]
I think this issue can be closed, as extension is working now. I don't have any issue since the update.
