### ISSUE TITLE
Doesn't work on macOS when"cartridgeroot"="auto" 

### ISSUE THREAD

**Issue by IaroslavVerstiukOSF** [SqrTT/prophet#21]
With new update debugger not working when cartridge root set to auto, when enable debug it detect root as current cartridge where I set breakpoint, when I change cartridge to path where all cartridges are it works fine.

Issue happens after this update to pathes https://github.com/SqrTT/prophet/pull/20/files

**Comment by SqrTT** [comment]
Thanks for reporting.

The issue is addressed in v.0.5.4. Could you please confirm that it is fixed for you?

Regards,
Anatolii

**Comment by IaroslavVerstiukOSF** [comment]
hi @SqrTT yes it works ok  now, thanks.
