### ISSUE TITLE
Unable to create 'launch.json'  after upgrade to version 1.2.5

### ISSUE THREAD

**Issue by vsanse** [SqrTT/prophet#211]
**Describe the bug**
 Unable to create 'launch.json' after upgrading Prophet debugger to version 1.2.5 but if I rollback to version 1.2.4 everything works fine and I'm able to create launch.json file
**To Reproduce**
1. Fresh install prophet extension
2. go to debug and click create launch.json file
3. observe the error in below screenshot

**Expected behavior**
I should be able to create launch.json and debug the code

**Screenshots**
![image](https://user-images.githubusercontent.com/14056492/71776953-90a1c000-2fbf-11ea-8233-1fd79931e088.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS Mojave 10.14.6
 - VSCode version: Version: 1.41.1
 - The extension version [e.g. 22]: sqrtt.prophet-1.2.5

**Comment by SqrTT** [comment]
hi @vsanse 
thanks for reporting.
Looks like you (VS Code) are taring to create 'launch.json' on sandbox. Please try on open/focus workspace with codebase.

**Comment by vsanse** [comment]
Still same issue. Version 1.2.4 works fine

**Comment by rpavantica** [comment]
What do you mean "open/focus workspace with codebase." I had to revert back to 1.2.4 as well for it  to work.

**Comment by vsanse** [comment]
In my case 1.2.4 causes issue while watching files to upload.it starts uploading .git files

**Comment by SqrTT** [comment]
could you please disable sandbox filesystem: https://user-images.githubusercontent.com/1271300/71084249-89944880-219d-11ea-8694-30c8abc2e85a.png

and remove it from workspace:
https://user-images.githubusercontent.com/1271300/72244534-28726000-35f7-11ea-866b-459e69247984.png

**Comment by vsanse** [comment]
Thanks, Man that worked!
