### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by payodeleink** [SqrTT/prophet#212]
- Issue Type: `Performance`
- Extension Name: `prophet`
- Extension Version: `1.2.5`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Owner\SqrTT.prophet-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SqrTT** [comment]
hi @payodeleink 
thank you for report.

Unfortunately, I see no way to reproduce the issue. Could you provide more detailed steps, please? 

PS.  *cpuprofile* is missing
