### ISSUE TITLE
no elements in sequence

### ISSUE THREAD

**Issue by balaji0447** [SqrTT/prophet#215]
no elements in sequence

**Comment by balaji0447** [comment]
i am unable to upload cartridges

**Comment by Valpich** [comment]
Hello,
I can confirm the issue:
Using config file '/Users/XXXX/workspace/storefront-reference-architecture/dw.json'
Error: EmptyError: no elements in sequence
Error: undefined

**Comment by JanWalsh91** [comment]
Hello. I confirm the issue. I am completely unable to upload cartridges.

**Comment by benjamin-bprod** [comment]
Hello,
Same problem, impossible to upload cartridges.

**Comment by JanWalsh91** [comment]
Hi. This is my workaround: 

- copy or move your entire project into a different repository.

I am then able to open the new folder in VSC, and upload with prophet.

Let me know if this works for other people.

**Comment by Valpich** [comment]
Easier, you can roll back prophet to the previous version 😄

**Comment by ghgofort** [comment]
I wanted to add some information from my experience with this bug:
- This is occurring to me when attempting to start a debugging session 
- I have options `extension.prophet.sandbox.filesystem.enabled`, `extension.prophet.htmlhint.enabled`, & `extension.prophet.upload.enabled' all set to disabled.
- Removing the extension and re-adding did not resolve the issue.
- Rolling back to version `1.2.11` resolved the issue and I am able to start the debugger again.

**Comment by SqrTT** [comment]
looks like major update of RxJS require more changes than I expected. :(

Could you please update to v1.2.15 and see if it works for you?

**Comment by ghgofort** [comment]
@SqrTT - v1.2.15 is working for me. Thank you for the quick fix, and all the work you put into this extension!

**Comment by balaji0447** [comment]
> 
> 
> Hello,
> Easier, you can roll back prophet to the previous version 😄

you have roll back vs code from latest version to v1.41(november)

Then will start working fine 

Prophet is not supporting latest version of vscode(january release)

**Comment by balaji0447** [comment]
> 
> 
> looks like major update of RxJS require more changes than I expected. :(
> 
> Could you please update to v1.2.15 and see if it works for you?

Prophet is not supporting latest version of vscode(january release)

you have to revert back vscode to november release then it will work fine

**Comment by balaji0447** [comment]
Prophet has to fix for latest version of vscode

**Comment by SqrTT** [comment]
latest version of vscode is 1.42.0

![image](https://user-images.githubusercontent.com/1271300/74420350-f2bdd280-4e53-11ea-926c-23bea1395018.png)

**Comment by SqrTT** [comment]
@balaji0447 can you confirm the issue is fixed for vs code  (latest 1.42.0) and extension (1.2.16), please?

**Comment by Valpich** [comment]
@SqrTT I can confirm, thanks.
![Screen Shot 2020-02-13 at 11 51 42](https://user-images.githubusercontent.com/12086820/74422490-5eee0580-4e57-11ea-91aa-dfacf3d5492f.png)

**Comment by balaji0447** [comment]
> 
> 
> @balaji0447 can you confirm the issue is fixed for vs code (latest 1.42.0) and extension (1.2.16), please?
The above mentioned versions are working fine .
