### ISSUE TITLE
Add .apiversion upload

### ISSUE THREAD

**Issue by AGvin** [SqrTT/prophet#216]
Sometime at projects required to upload .apiversion file to support some old legacy code-version.

It will be great to add support to search (as it can be specific folder structure) and uploading .apiversion file to Sandbox code-version root folder.

**Comment by SqrTT** [comment]
hi @AGvin 
thanks for suggestion. This is first time I hear about `.apiversion`. Not sure how many users will need this feature. Also is not clear even we implement this for extension how it will be deployed to PID (STG/DEV/PROD) instances...

Is good idea to upload system file?

**Comment by AGvin** [comment]
@SqrTT ^
Some time we have different "Compatibility Mode" on sandboxes and PIG, and unable to switch it on sandbox without uploading current file.
For example, on sandbox available only "20.2" but need "18.10" (as on PIG).
It will be helpful to have posibility upload it automaticaly (as cartridges).
In current case, all dev sandboxes can be with same "Compatibility Mode" and it will be always up-to-date
