### ISSUE TITLE
Multiple instance configuration in one dw.json

### ISSUE THREAD

**Issue by gokaygurcan** [SqrTT/prophet#217]
Hi,

Sometimes, we have different project setups and multiple instances within different realms that share some code but not all. In this case, having one `dw.json` is not solving our problem or gives us a chance to upload some specific cartridges to some specific instances. On the other hand, our code versions are not always the same, considering there's an ongoing development on both places, nor our usernames and passwords. 

It'd be really nice if we can have an array or objects in the `dw.json` like,

```js
[
  {
    "hostname": "dev01-eu02-somewhere.demandware.net",
    "username": "username",
    "password": "ultrasecurepassword",
    "code-version": "version1"
  },
  {
    "hostname": "dev01-eu01-somewhereelse.demandware.net",
    "username": "email",
    "password": "unifiedlogin",
    "code-version": "version4",
    "cartridges": [ "cartridge", "list" ]
  }
]
```

Alternatively, we tried multiple project roots but it doesn't solve our mail problem: having a single repository to manage all the sandboxes with different setup.

Eclipse has this option, when you create a new connection, it asks which cartridges will be linked to that instance and you can easily switch between the instances and upload only those cartridges. One caveat though, in that case you need to manually switch code version each time or need to have one code version everywhere. This feature can also fix that problem too :)

/cc @diogopinheiro

**Comment by SqrTT** [comment]
Hi @gokaygurcan 

thanks for submitting idea. Honestly such idea was in air a while ago but there are few unclear points:
* change format of dw.json is not good idea since other tools relay on it.
* totally not clear when and how select/activate configuration.

Also in not clear how many users will use these feature.
Currently you may use `dw.js` as workarround, with few configs and selecting one via some flag, for instance:
 
```javascript
const config = {
    eu02: {
        "hostname": "dev01-eu02-somewhere.demandware.net",
        "username": "username",
        "password": "ultrasecurepassword",
        "code-version": "version1"
    },
    eu01: {
        "hostname": "dev01-eu01-somewhereelse.demandware.net",
        "username": "email",
        "password": "unifiedlogin",
        "code-version": "version4",
        "cartridges": ["cartridge", "list"]
    }
}

module.exports = config['eu02']; // select config by key
```

**Comment by gokaygurcan** [comment]
Aha! That sounds like a plan. Thanks a lot. 

And yes, I understand the desire of keeping `dw.json` as is. 

I'd say we can close the issue since there's some kind of a resolution. 

Thanks again!

**Comment by jlbruno** [comment]
I came to see if there had been an issue about this in the past. I don't want to reopen at this point, but want to point out that IntelliJ SFCC has support for this, and has a defined structure for the dw.json. 
https://smokeelow.visualstudio.com/Intellij%20SFCC/_wiki/wikis/intellij-sfcc.wiki/25/dw.json?anchor=multiple-connections
