### ISSUE TITLE
Code is not uploaded after watching files

### ISSUE THREAD

**Issue by balaji0447** [SqrTT/prophet#218]
Watched file is not uploaded to instances

after restart vscode again i have to upload entire cartridge

**Comment by SqrTT** [comment]
hi @balaji0447 

Could you share a bit more details so I'm able to reproduce an issue, please?

For instance, some logs, errors, etc...

**Comment by SqrTT** [comment]
@balaji0447 
if you still have the issue, please feel free to reopen ticket with additional details.
