### ISSUE TITLE
add options to change logFilePath in launch.json file

### ISSUE THREAD

**Issue by julienphilippe** [SqrTT/prophet#220]
Hello, 

As my normal user have is not admin user of my computer hard drive,  I have this error when i'm using vscode without admin right

> Error creating log file at path: \prophet-debugger.log. Error: Error: EPERM: operation not permitted, open 'C:\prophet-debugger.log'

Can i change the logFilePath path with in the launch.json file and how ? 

Thx

**Comment by SqrTT** [comment]
Hi @julienphilippe 

thank you for rising an issue. Could you check if is issue actual for v1.2.23, please?

**Comment by julienphilippe** [comment]
OK working now :D 
thx
