### ISSUE TITLE
Pasting in ISML is adding whitespace

### ISSUE THREAD

**Issue by Jakobud** [SqrTT/prophet#221]
**Describe the bug**
Whenever I paste something into an ISML file, Prophet is adding whitespace at the beginning of the pasted value that is equivalent to the indented whitespace on that line. For example if I have the following in an ISML file:

```
<div>
    <span></span>
</div>
```

If I paste `hello world` after `</span>` it will look like this:

```
<div>
    <span></span>     hello world
</div>
```

Prophet is adding 4 spaces to the beginning of the pasted value. There are 4 spaces at the indent of the start of the line. Whenever anything is pasted, it takes the indented number of spaces or tabs and is adding them to the front of any pasted value.

**To Reproduce**
1. Just try the above.

**Expected behavior**
It does not add any unexpected white space

**Screenshots**
![Screen Shot 2020-02-19 at 11 36 57 AM](https://user-images.githubusercontent.com/87356/74864084-314c0500-530c-11ea-9fac-d0a9fc999c6f.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.15.1
 - VSCode version: 1.42.1
 - The extension version: 1.2.23

**Additional context**
I have disabled all other extensions except Prophet and get this behavior. Disabling Prophet and the behavior goes away.

**Comment by SqrTT** [comment]
hi @Jakobud 
thank you for your time and great description, the issue really exist (reported already #156). 
This is happening because incorrect calculation of indentation in case line already has content, as workaround you may disable 'format on paste' in VS Code configuration.

![image](https://user-images.githubusercontent.com/1271300/74921409-66248e80-53d6-11ea-961f-36e32c80837f.png)

I'll try to fix the issue, but no ETA, yet.

**Comment by Jakobud** [comment]
Looks like that did the trick. I searched but must have missed the previously reported issue. Thanks,

**Comment by Jakobud** [comment]
FYI in #156 you mentioned that you wanted to track the problem in this ticket, but now both tickets are closed.

**Comment by SqrTT** [comment]
this ticket isn't closed...

**Comment by Jakobud** [comment]
Oh ops I saw the Closed notification above for #156 . My bad. I've been looking through your code trying to figure out where the issue could be. Somewhere in `htmlFormatter.ts`?

**Comment by SqrTT** [comment]
hi @Jakobud & @dlferro 

Could you guys check if issue is actual in v1.2.27, please?
I've been updated language server there.

**Comment by Jakobud** [comment]
Just checked on 1.2.30 and this appears to be working properly now. I just enabled "Editor: Format on Paste" and it does not add weird whitespace to the start of the pasted text.

**Comment by SqrTT** [comment]
thanks for feedback. Closing. Feel free to reopen in case issue is actual.
