### ISSUE TITLE
n.Observable.throw is not a function and ETIMEDOUT when trying to upload cartridges

### ISSUE THREAD

**Issue by zigolis** [SqrTT/prophet#222]
**Describe the bug**
After the latest vscode update, at anytime when a file is updated or when Clean Project / Upload All is used a few errors show up on the output.

**To Reproduce**
1. Go to 'your files / code source'
2. Press 'command + P and select Prophet / Clean Project / Upload All '
3. Check 'your output on the vscode terminal'

**Expected behavior**
It should upload all files to your sandbox.

**Screenshots**
![Screenshot 2020-03-02 12 44 48](https://user-images.githubusercontent.com/2637502/75673692-d3aca680-5c83-11ea-96d0-f1300a534dae.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - VSCode version: 1.42.1
 - The extension version 1.2.30

**Additional context**
I'm placing the logs here as well.

`Connection validated successfully
Current active version is: version1
Start uploading cartridges
Cleanup code version...
Error: TypeError: n.Observable.throw is not a function
Trying to re-upload
Connection validated successfully
Current active version is: version1
Start uploading cartridges
Cleanup code version...
[bm_adyen] Deleting remote zip (if any)
[bm_adyen] Zipping
[bm_adyen] Sending zip to remote
[bm_adyen] Remove remote cartridge before extract
[bm_adyen] Unzipping remote zip
[int_givex] Deleting remote zip (if any)
[int_givex] Zipping
[int_givex] Sending zip to remote
[bc_library] Deleting remote zip (if any)
[bc_library] Zipping
[bc_library] Sending zip to remote
[bm_adyen] Deleting remote zip...
[int_givex] Remove remote cartridge before extract
[int_givex] Unzipping remote zip
[bm_paypal] Deleting remote zip (if any)
[bm_paypal] Zipping
[bm_paypal] Sending zip to remote
[int_givex] Deleting remote zip...
[bc_library] Remove remote cartridge before extract
Error: TypeError: n.Observable.throw is not a function
Trying to re-upload
Connection validated successfully
Current active version is: version1
Start uploading cartridges
Cleanup code version...
[int_givex] Deleting remote zip (if any)
[int_givex] Zipping
[int_givex] Sending zip to remote
[int_givex] Remove remote cartridge before extract
[int_avatax_svcclient] Deleting remote zip (if any)
[int_avatax_svcclient] Zipping
[int_avatax_svcclient] Sending zip to remote
[bm_adyen] Deleting remote zip (if any)
[bm_adyen] Zipping
[bc_library] Deleting remote zip (if any)
[bc_library] Zipping
[bm_adyen] Sending zip to remote
[bc_library] Sending zip to remote
[int_givex] Unzipping remote zip
[int_avatax_svcclient] Remove remote cartridge before extract
[bm_adyen] Remove remote cartridge before extract
[bc_library] Remove remote cartridge before extract
[bc_library] Unzipping remote zip
[int_avatax_svcclient] Unzipping remote zip
[bm_adyen] Unzipping remote zip
[int_avatax_svcclient] Deleting remote zip...
[bm_adyen] Deleting remote zip...
[bc_library] Deleting remote zip...
[bm_paypal] Deleting remote zip (if any)
[bm_paypal] Zipping
[bm_paypal] Sending zip to remote
Error: Error: connect ETIMEDOUT 66.179.99.97:443
Error: Error: connect ETIMEDOUT 66.179.99.97:443
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)`

**Comment by SqrTT** [comment]
hi @zigolis 

Thanks for reporting. Could you please check if issue is actual in v1.2.32? I've fixed issue with `Observable.throw is not a function` and tried to address ETIMEDOUT.

**Comment by zigolis** [comment]
Hey @SqrTT 

I just tried here on v1.2.33 and I got only the ETIMEDOUT error. It should be fine, I guess. 
I am also facing some connection issues at work which turns out to be a block for me in order to really debug and test this fix.

I will let u know as soon as I have a stable connection.

**Comment by SqrTT** [comment]
some people reported that sandbox restart may help in some cases

**Comment by zigolis** [comment]
Hey @SqrTT,

Thanks man, all good now! I am closing the issue btw.
