### ISSUE TITLE
ESOCKETTIMEDOUT Error when trying to upload cartrigdes

### ISSUE THREAD

**Issue by FlorentinaLacatus** [SqrTT/prophet#225]
Hello,
I am getting the following error when trying to upload cartridges. 
Sometimes, cartridges are uploaded, but it takes a lot of time `Upload time: 3 min 14 sec`

![2020-03-09_18h34_16](https://user-images.githubusercontent.com/51082748/76424588-19b6e800-63b1-11ea-928c-ee7fac1fc4d4.png)

**Comment by SqrTT** [comment]
thank you for reporting. Unfortunately this is not extension issue but networking. Nothing I can do here.


PS. right now my colleagues and me facing similar issues, seems there are issue on SFCC side

**Comment by FlorentinaLacatus** [comment]
Ok. :(

Thank you for your response!

**Comment by SqrTT** [comment]
in version 1.2.44 added more retries in case of failure, this should reduce time to upload in cases one of cartridges wan't uploaded.

**Comment by FlorentinaLacatus** [comment]
Thanks! It seems that it works better now :) `Upload time: 1 min 15 sec`
