### ISSUE TITLE
VS Code Search Broken w/ Prophet Extension Enabled

### ISSUE THREAD

**Issue by roxberry** [SqrTT/prophet#229]
**Describe the bug**
Search feature in VS Code appears to be broken in latest release.

**To Reproduce**
1. Open VSCode
2. Open SFCC project
3. Click Search icon on the left sidebar
4. Enter term into search bar

**Expected behavior**
Search completes query

**Screenshots**
![image](https://user-images.githubusercontent.com/761326/78992016-55f07c00-7b08-11ea-9a64-9093a6e5c4d3.png)

**Desktop (please complete the following information):**
 - OS: MACOS 10.15
 - VSCode 1.44.0
 - Prophet Debugger 1.3.1

**Additional context**

**Comment by roxberry** [comment]
Workaround: open a folder above the project in another VS Code instance, exclude any folders that you are not searching.

**Comment by fenomchris** [comment]
I have the same issue, opened it against VSCode repo here:

https://github.com/microsoft/vscode/issues/94924#issuecomment-612092875

Started after the latest macOS 10.15.4 update...

**Comment by SqrTT** [comment]
better workaround would be disable sandbox FileSystem and remove it from your workspace:

![image](https://user-images.githubusercontent.com/1271300/79004332-359edc80-7b5d-11ea-8c17-c4bf3d624dbc.png)

![image](https://user-images.githubusercontent.com/1271300/79004411-60893080-7b5d-11ea-9afa-3d011d848d8c.png)

**Comment by fenomchris** [comment]
The above fix works for me! Thank you for the quick response to this issue 👍

**Comment by SqrTT** [comment]
this is not plugin issue, sandbox file system exists almost two years for now, but issue appears only in latest vscode release

**Comment by SqrTT** [comment]
https://github.com/microsoft/vscode/issues/94928

**Comment by roxberry** [comment]
I don’t have the Sandbox folder on my UI to remove?

**Comment by roxberry** [comment]
Ah, never mind - I re-enabled, it shows, now I’ll remove then unenable.

**Comment by SqrTT** [comment]
the search is fixed in 1.44.2 version of VS Code
