### ISSUE TITLE
upload is not working

### ISSUE THREAD

**Issue by Gektorian** [SqrTT/prophet#23]
```
Starting...
Using config file "d:\DW\workspace\*****\cartridges\dw.json"
Using directory "d:\DW\workspace\*****\cartridges" as cartridges root
Starting
Connection validated successfully

Warn: Current code version is "version1" while uploading is processed into "undefined"

Current active version is: version1
Start uploading cartridges
"TypeError: cartridges.map is not a function"
Error: TypeError: cartridges.map is not a function
```
Any ideas what I've done wrong?

thanks in advance

**Comment by SqrTT** [comment]
Hi @Gektorian ,
Probably you set property `cartridge` as a string... it should be an array of strings.

**Comment by SqrTT** [comment]
Looks like there was a bug. Thanx for reporting. Could you please confirm that now everything is ok (v0.6.2)?

Regards,
Anatolii

**Comment by gkkirilov** [comment]
Can confirm, Its fixed, had the same problem.
Thanks for the fast response @SqrTT Awesome work

**Comment by Gektorian** [comment]
Fixed

**Comment by SqrTT** [comment]
thanx, closing
