### ISSUE TITLE
ISML auto suggestion not working

### ISSUE THREAD

**Issue by aagrawal26** [SqrTT/prophet#234]
I'm unable to get the ISML suggestion when Prophet Uploader is enabled. ctrl+space every time shows Loading... How to fix this issue?

**Comment by SqrTT** [comment]
Please provide details so I can reproduce the issue. Any logs/errors etc. Try to disable other extensions. Also please add version information about your OS/VS Code/The plugin version.

**Comment by aagrawal26** [comment]
There is no error. I tried disabling other extension but still, it's not working. 
OS: Win 7
VS code version: 1.44.2
Plugin Version: 1.3.3

ctrl+space showing as Loading... for .isml files.
![image](https://user-images.githubusercontent.com/46890470/79909569-d4b7b400-843a-11ea-8876-82ff29c19a97.png)

**Comment by BeSublime** [comment]
I am experiencing this issue on a Mac as well. When all extensions are disabled, ctrl+space shows suggestions - but as soon as I enable Prophet only (with all other extensions still disabled), ctrl+space only shows "Loading…". 

**Backing down to version 1.3.0 (or earlier) fixes the issue.**

Version information
OS: macOS Catalina 10.15.4
VS Code: 1.44.2
Prophet: 1.3.3

Only messages in the dev console are as shown:
![image](https://user-images.githubusercontent.com/280533/80732094-70978e80-8ad1-11ea-8481-ad2068b8751f.png)

**Comment by aagrawal26** [comment]
@BeSublime Thanks! downgrading to 1.3.0 worked for me.

@SqrTT Could you check why with the latest update. I'm facing this issue.

Thanks

**Comment by ecRobertEngel** [comment]
@SqrTT I can confirm this issue. But only for multi root projects. 

Some more information: 

- The require suggestions in JS files are also affected
- The suggestions both for JS and ISML are working in the client folders of my project. 

I have disabled all other extensions to rule out a cross extension problem.

Downgrading to 1.30 indeed solved the issue.

Hope this helps

**Comment by SqrTT** [comment]
could you please share example of file which cause an error?
also would be great to see output of ScriptServer:
![image](https://user-images.githubusercontent.com/1271300/81834640-e546e000-9549-11ea-893e-1472ad6fc647.png)

**Comment by ecRobertEngel** [comment]
It is the case for all .js or .isml files in a multi-root project. 

Thê output simply shows the init function. If I type req and press F12 it displays "req definition" and than the file name. But it does not load anything.

**Comment by SqrTT** [comment]
seems I found an issue. multi-root project is not enough. One of project should be SFRA which contain `sgmf-scripts`. If my assumptions is correct next workaround should help:
Need to add `**/node_modules/sgmf-scripts` into files exclude:
![image](https://user-images.githubusercontent.com/1271300/81908682-34d0ee80-95d2-11ea-9733-506e610d7ad7.png)

I'll try to fix issue in the extension soon.

**Comment by aagrawal26** [comment]
Hi @SqrTT,

As mentioned, I have added the following in the files: exclude but still, it didn't work with the newer version. The same loading I'm getting.
![image](https://user-images.githubusercontent.com/46890470/81911754-58546300-95eb-11ea-8345-cc327277bb06.png)

Thanks

**Comment by SqrTT** [comment]
have you tried reload VSCode with new config?

**Comment by SqrTT** [comment]
or do you have several `dw.json/dw.js` files? if yes, please, leave temporary only one.

**Comment by aagrawal26** [comment]
Hi @SqrTT ,

I have only one workspace and only one dw.json. reloaded the VS code config. But, still getting the same issue.
Downgraded to 1.3.0 and it is working.

Thanks

**Comment by ecRobertEngel** [comment]
I have removed the additional dw.json and added the exclude pattern, but it did not solve the problem.

**Comment by ecRobertEngel** [comment]
@SqrTT is there anything I can do to help find the issue?

**Comment by SqrTT** [comment]
at this point looks like my assumption was incorrect so I don't have idea why this happen also I'm not able to reproduce. I'll keep digging. 
I'm always open to PR if you can track down the issue.

**Comment by ecRobertEngel** [comment]
I have found the solution. I took the time to clone the repo, compile the extension myself and debug it step by step. The error is quite easy to solve. 
For the completion to work the cartridges have to be defined in the dw.json file.
This is marked as optional in the ReadMe documentation. But it is in fact required for multi root project it seems. So as soon as it is added the isml completion and the req completions are working again. 

Hope this also helps everyone else with the same issue.

**Comment by SqrTT** [comment]
correct, cartridges or cartridges paths is required to this feature work.The extension tries to find out cartridge path (can resolve if you have site metadata in workspace, `site.xml` file), but if fails shows warning. 
Did you have some warnings during start up?.

this issue should be fixed in 1.3.5. Server will not start in case paths is missing, so no loading should appears.

PS. @ecRobertEngel thank you for investigation.

**Comment by aagrawal26** [comment]
@SqrTT @ecRobertEngel, The issue is fixed with the latest update. Thanks for your time in debugging the root cause.
