### ISSUE TITLE
Prophet causing lint warning annotations for no-global-require no matter what linter settings are.

### ISSUE THREAD

**Issue by ghgofort** [SqrTT/prophet#237]
**Getting linter warning annotations for global require**
When I have the Prophet extension enabled, I am getting linter warning annotations in some JS code files for prohibited global usage of require. When I disable the extension the annotations go away.

I have tried with all other extensions disabled to be sure it was not a combination of extensions causing the issue.

**To Reproduce**
1. Open a project with the storefront-reference-architecture repo included.
2. Open the file **storefront-reference-architecture/cartridges/app_storefront_base/cartridge/models/order.js**
3. Observe the added annotations for the Model class imports:
![image](https://user-images.githubusercontent.com/16811151/80506129-2da7b080-8943-11ea-96b8-28b049109602.png)
4. If you now disable the Prophet extension and reload the VSCode window, the annotations are no longer there.

**Expected behavior**
Because the Prophet extension is not configured as my linter for the project for JS files, I expect that it will not add linting annotations to my code, or at least will offer a way to configure, override, or disable these annotations.

**Screenshots**
__All Other Extensions Disabled__
![image](https://user-images.githubusercontent.com/16811151/80506321-68114d80-8943-11ea-9811-fbd2af5e5dfa.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.4
 - VSCode version: 1.44.2
 - The extension version: 1.3.3

**Additional context**
I have tried numerous things to get the annotations to go away without rolling the extension back or disabling it, but had no luck. I initially didn't think that it would be the Prophet extension that was the cause.
* Disabled all other extensions and used a fresh repo of SFRA with a stock .jsconfig file.
* Added a .eslintrc.json file to the directory and set the `no-global-require` rule to "off"
* Added an `// eslint-disable-next-line` comment to the line above.

Thank you for your time and effort, much appreciated!

**Comment by SqrTT** [comment]
hi @ghgofort 
thanks for reporting. You can't configure this via eslint rules since this is not eslint but is build in extension diagnostics. At this point this is not configurable, but probably I'll add such option as far as have time.

This warning was added to avoid performance issues with globally required custom modules.
[docs](https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2FSFRA%2FSFRAModules.html)
![image](https://user-images.githubusercontent.com/1271300/80510904-09b88f00-8984-11ea-9a07-46dbaebbc61d.png)
Mimics behavior of `no-global-require` -  https://www.npmjs.com/package/eslint-plugin-sitegenesis


PS. similar issue #228

**Comment by ghgofort** [comment]
@SqrTT - I appreciate the information, and the time. This is clearly not blocking me from doing work so it is not a hurry if you do get to it. If not and I find time, maybe I will take a stab at a PR to add a VSCode setting.

I agree that this issue is fairly similar to issue #228 and I don't mind if you close this one and track on that ticket, I just wanted to call this out as it is pretty common practice both in SFRA/SG & in integration cartridges so it would be nice to be able to ignore these when wanted.

**Comment by SqrTT** [comment]
this can be disabled by flag: `extension.prophet.script.server.disable.diagnostics`

in v1.3.5

**Comment by SqrTT** [comment]
closing since flag is implemented
