### ISSUE TITLE
Open isinclude templates via Ctrl+Click doesn't work with file associations

### ISSUE THREAD

**Issue by fleps** [SqrTT/prophet#24]
Hi!

This is more a question than an issue ( I think)

As a FD I have ISML files associated to HTML: 
```
"files.associations": {
        "*.isml": "html"
    }
```

I use this so I could have all perks when writing html like auto-completion, boilerplates, snippets, and so on, but with this enabled the Ctrl + Click for isinclude tags doesn't work (when I disable the association, it works)

Is there any way to get this working while keeping the file association, perhaps via settings?

Thanks!

**Comment by SqrTT** [comment]
Hi.

Currently, I know one way: configure each extension that improves editing to understand `isml` files.

For example, my config is:

```javascript
{
    // Emmet
    "emmet.syntaxProfiles": {
        "isml": "html"
    },
    // Auto Rename Tag - https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag
    "auto-rename-tag.activationOnLanguage": [
        "html", "isml"
    ],
    // Auto Close Tag - https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
    "auto-close-tag.activationOnLanguage": [
         "html", "isml"
    ]
}
```

Probably I'll add such config for Prophet in nearest future too.

Regards,
Anatolii

**Comment by fleps** [comment]
@SqrTT thanks for replying but I have a lot of extensions and also I think there is some additional perks by having ISML associated to HTML that I'm not sure this would cover.

Thanks!

**Comment by SqrTT** [comment]
@fleps 
In v0.6.3 is added property `extension.prophet.ismlServer.activateOn`, this should make quick open works.

Please confirm that is works for you.

**Comment by fleps** [comment]
@SqrTT yes I added the html on that property and now works.

Thanks a lot! =)
