### ISSUE TITLE
How can I ignore globs for watching?

### ISSUE THREAD

**Issue by Jakobud** [SqrTT/prophet#241]
I see that there is a setting to ignore globs when doing a project clean. But no way to do it for watching? You are using chokidar which provides an option to ignore any globs you specify. How come this interface isn't available for Prophet?

FYI a perfect example of things to ignore are build tools and temporary files that are created during SASS and JS compiling for your project. Prophet doesn't need to watch those and/or upload them.

**Comment by SqrTT** [comment]
the Prophet don't use chokidar. You can ignore files by using `files.watcherExclude`:
![image](https://user-images.githubusercontent.com/1271300/85333128-b8d79980-b4e1-11ea-9812-d7d5cd15ae01.png)

**Comment by Jakobud** [comment]
I had no idea that Prophet used the `files.watcherExclude` setting in VSCode. Thank you. I would recommend adding this to the documentation. I see no mention of it. I only see the prophet-specific setting about ignoring.
