### ISSUE TITLE
Validation error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by BunFongUng** [SqrTT/prophet#243]
Hi everyone,

have anyone facing this issue before when we run Clean Project / Upload all with the following error message below

`Using config file '...../dw.json'
Unable validate connection!
Validation error: self signed certificate in certificate chain
Error: Error: self signed certificate in certificate chain
Trying to re-upload
Unable validate connection!
Validation error: self signed certificate in certificate chain
Error: Error: self signed certificate in certificate chain
Trying to re-upload
Unable validate connection!
Validation error: self signed certificate in certificate chain
Error: Error: self signed certificate in certificate chain
Trying to re-upload
Unable validate connection!
Validation error: self signed certificate in certificate chain
Error: Error: self signed certificate in certificate chain
Error: Error: self signed certificate in certificate chain
	at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
	at TLSSocket.emit (events.js:203:13)
	at TLSSocket.EventEmitter.emit (domain.js:476:20)
	at TLSSocket._finishInit (_tls_wrap.js:792:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)`

Thank you,
BunFong

**Comment by SqrTT** [comment]
hi @BunFongUng thanks for reporting.
Question: do you use domain (hostname in dw.json) format with dashes  or with dots?

`https://dev<00>-<zone>-<brand>.demandware.net` (with dashes) or

`https://dev<00>.<zone>.<brand>.demandware.net` (with dots)

Variant with dashes should be working. Could you confirm case with dashes don't work in your case, please?

**Comment by BunFongUng** [comment]
Hi @SqrTT,

for the hostname in the dw.json with dashes.

but please note for the last few months it working fine. it just happened a few days ago.  

Thanks,
BunFong

**Comment by SqrTT** [comment]
thanks for provided info.
Could you update to the extension to v1.3.21, and check if fix is working for you, please?

**Comment by BunFongUng** [comment]
Hi @SqrTT,
Thank you so much for helping. it working fine right now after I have update the extension to v1.3.21 as you suggested.
Regards,
BunFong

**Comment by SqrTT** [comment]
thank you for helping to address down an issue.

Closing it for now. If issue appears again feel free to reopen.
