### ISSUE TITLE
"disable diagnostic" option not applied at startup

### ISSUE THREAD

**Issue by fgiust** [SqrTT/prophet#250]
The setting "extension.prophet.script.server.disable.diagnostics" doesn't seem to be applied properly at startup.

**To Reproduce**
1. enable "extension.prophet.script.server.disable.diagnostics": true
2. no errors on "let" or "const" in js files are displayed anymore as expected
3. restart VS code
4. errors on "let" or "const" in js files are back (KO)
5. reopen VSCode configuration, "extension.prophet.script.server.disable.diagnostics" is still checked. Remove the check and readd it -> now the configuration works as expected again

**Expected behavior**
The setting should be preserved/reapplied after a restart

**Desktop:**
 - OS: MacOs
 - VSCode version: 1.48.0
 - The extension version: 1.3.23

**Comment by SqrTT** [comment]
@fgiust thanks for reporting. I'll take a look on that.

**Comment by fgiust** [comment]
hi @SqrTT,
I've raised a pull request https://github.com/SqrTT/prophet/pull/260 - seems a simple fix, it would be great if you can include it in the next release as it's pretty annoying for teams that are encouraging the usage of let over var in the code..

**Comment by SqrTT** [comment]
@fgiust of course, fix will be included in next release. Thank you for your time.

**Comment by SqrTT** [comment]
released in 1.3.24. Could you confirm fix present and it's working for you, please?
