### ISSUE TITLE
Asking for password if a file in the repository is named dw.js

### ISSUE THREAD

**Issue by jkol** [SqrTT/prophet#252]
**Describe the bug**
The same password prompt from #248 happens if a file in the repository is named dw.js. No prompt is received if the name is changed.

**To Reproduce**
1. Create a file dw.js in a subdirectory with the following contents:
```'use strict';

module.exports = {
    username: '',
    password: '',
    hostname: ''
};
```
2. Close VScode
3. Open VSCode
4. Observe PW prompt on open
5. Attach to sandbox
6. Observe PW prompt
7. Change filename of dw.js to something else, e.g. `test.js`
8. Observe lack of PW prompt

**Expected behavior**
No Prompts should exist if dw.json in root of project has a password field filled out.

**Desktop (please complete the following information):** 
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Prophet version: 1.3.23

**Additional context**
Error message if no password is given:
```"No password provided, for file: c:\\projects\\{{project folder}}\\{{subdirectory}}\\dw.js"```

**Comment by SqrTT** [comment]
this is not a but but feature. implemented in #207

**Comment by jkol** [comment]
Anyway that root-level dw.js or dw.json files can take priority over subdirectory?

**Comment by ComeAlongErica** [comment]
I'm having this issue as well, and can't seem to find anywhere to specify the root of the directory.

**Comment by sergeystoma** [comment]
Prophet looks like is randomly picking a dw.json file - sometimes from the root level, sometimes from subdirectories

**Comment by SqrTT** [comment]
dw.json/js file lookup is re-implemented and now looks for file starting from cartridge root and then sub-folders and so on.
