### ISSUE TITLE
Debug issue with proxy

### ISSUE THREAD

**Issue by LucasReyre** [SqrTT/prophet#255]
**Describe the bug**
Unable to debug with a corporate proxy while upload cartridges to sandbox working fine.
I don't have any error message the debug just stop after a timeout

**To Reproduce**
In settings.json I set http.proxy and https.proxy
Proxy is also set in my environment variables and npm config

**Desktop**
 - OS: Windows 10 Entreprise
 - VSCode version : 1.48.1
 - The extension version : 1.3.23

**Additional context**
Configuration in dw.json is correct because everything works fine when i m on a network without proxy

**Comment by SqrTT** [comment]
Hi @LucasReyre 
thanks for reporting request to support proxy was make a while ago #81 but still not implemented. But there are still workarounds. Could you check if they works for you, please?

**Comment by LucasReyre** [comment]
Hi @SqrTT 
Yes I set HTTP_PROXY and HTTPS_PROXY and it make the cartridge upload work but not the debug

**Comment by SqrTT** [comment]
ah, I see. I'll try to do something with it but still no ETA :(

**Comment by ArthurZob** [comment]
Hi @SqrTT,
I'm facing the same issue on my side, is there a way to improve this part ?
Regards,
Arthur

**Comment by SqrTT** [comment]
I'm pretty busy this time. But I would be happy to merge PR with this feature.

**Comment by SqrTT** [comment]
proxy support requested in #81 let's track there
