### ISSUE TITLE
Prophet Uploader output: include hostname and code-version from dw.json file

### ISSUE THREAD

**Issue by poebrand** [SqrTT/prophet#257]
**Is your feature request related to a problem? Please describe.**
When switching between sandboxes/versions or doing the initial setup, its not uncommon to have the wrong hostname/code-version entered or a typo in it.

**Describe the solution you'd like**
Currently the "Prophet Uploader" output, includes:
> Current active version is: version1

It would be great if it could include hostname and code-version from the dw.json file. Here's an example of what that might look like:
> dw.json hostname: bcpx-099.sandbox.us99.dx.commercecloud.salesforce.com
> dw.json code-version: version2
> Sandbox active version: version1

**Describe alternatives you've considered**
Current alternative is making sure to double-check the file manually when not seeing the expected outcome in a sandbox.

**Additional context**
N/A

**Comment by SqrTT** [comment]
@poebrand indeed this could be useful.
I'll add it in next release.

**Comment by SqrTT** [comment]
added in 1.3.24

**Comment by poebrand** [comment]
Thanks!
