### ISSUE TITLE
Script Language Server

### ISSUE THREAD

**Issue by roxberry** [SqrTT/prophet#259]
**Describe the bug**
When Prophet is enabled, all typing in any file type causes a pop up and the log error:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/761326/93548501-500f8a00-f935-11ea-863d-344a8ab10af9.png">

[Error - 10:25:29 PM] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601 

**To Reproduce**
1. Enable Prophet
2. Type in ANY file type (js, html, scss).

**Expected behavior**
No error message in Script Language Server output
No popup 

**Desktop (please complete the following information):**
 - OS: macOS 10.15.16
 - VSCode version: 1.49.1
 - The extension version 1.3.23

**Additional context**
New project has this symptom.  Older project does not.  Disabled all extensions but Prophet in both workspaces.

New project has "Script Language Server" in the Output.  Older project does not have that Output source.

New Project
<img width="385" alt="image" src="https://user-images.githubusercontent.com/761326/93548876-302c9600-f936-11ea-9136-7fa6e0a6c04b.png">

Older Project
<img width="262" alt="image" src="https://user-images.githubusercontent.com/761326/93548959-58b49000-f936-11ea-8eb9-d913a9bb9fbf.png">

**Comment by SqrTT** [comment]
Hi @roxberry 
thank you for reporting. Could you share output of Script Language Server, please?

also potentially, could you try put cartridge path (just copy-paste path from BM) to `cartridgesPath` your `dw.json`, please?

**Comment by roxberry** [comment]
Script Language Server output (obfuscated client info).  This occurs as I type (and I assume as the watch uploads):

`[Info  - 9:24:21 AM] Client created
[Info  - 9:24:21 AM] Actual cartridges: [{"name":"<cartridge name>","fsPath":"/Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>"}]
[Info  - 9:24:21 AM] Starting client...
Script Server init... 
[{"uri":"file:///Users/roxberry/Workspaces/<project root>","name":"<storefront name>"}]
[Info  - 9:24:22 AM] Server Ready
[Info  - 9:24:22 AM] Files list =>
got cartridges files list
[Info  - 9:24:22 AM] Templates list =>
got cartridges templates list
[Info  - 9:24:22 AM] Controllers list =>
got cartridges controllers list, parse time: 0.01]
[Info  - 9:24:22 AM] Properties list =>
[Info  - 9:24:22 AM] Configuration done
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
controller modified: Change : file:///Users/roxberry/Workspaces/<project root>/cartridges/<cartridge name>/cartridge/controllers/Home.js
**[Error - 9:25:42 AM] Request textDocument/definition failed.
  Message: Unhandled method textDocument/definition
  Code: -32601 
[Error - 9:25:42 AM] Request textDocument/definition failed.
  Message: Unhandled method textDocument/definition
  Code: -32601 `**

**Comment by IaroslavVerstiukOSF** [comment]
I have exactly same issue, but it depends on project, it happens only on one where I have non standard SFRA/SG project, as an example I have only cartridges which contains some scripts to customize OCAPI hooks and nothing more, and there I have this issue. 

On another project which is based on SFRA all works good, maybe there is some dependencies.

**Comment by dennis-ryan** [comment]
i noticed that not setting, or removing any existing setting, for `"extension.prophet.cartridges.path"` from your settings will "fix" the issue. It does so by not starting the Script Language Server in this case.

**Comment by SBlanchon-Viseo** [comment]
Same issue in my SG project. I don't have any setting in "extension.prophet.cartridges.path", though.

```
[Info  - 09:28:51] Client created
[Info  - 09:28:51] Actual cartridges: [{"name":"app_sephora_core","fsPath":"c:\\Users\\StephaneBlanchon\\Workspaces\\SEPHORA\\estore-sfcc-sephora\\cartridges\\app_sephora_core"},{"name":"app_sephora_controllers","fsPath":"c:\\Users\\StephaneBlanchon\\Workspaces\\SEPHORA\\estore-sfcc-sephora\\cartridges\\app_sephora_controllers"},{"name":"app_sephora_extended","fsPath":"c:\\Users\\StephaneBlanchon\\Workspaces\\SEPHORA\\estore-sfcc-sephora\\cartridges\\app_sephora_extended"}]
[Info  - 09:28:51] Starting client...
Script Server init... 
[{"uri":"file:///c%3A/Users/StephaneBlanchon/Workspaces/SEPHORA/estore-sfcc-sephora","name":"estore-sfcc-sephora"},{"uri":"ccfs://current-sandbox/","name":"Sandbox - FileSystem"}]
Diagnostics enabled: false
[Info  - 09:28:52] Server Ready
[Info  - 09:28:52] Files list =>
got cartridges files list
[Info  - 09:28:52] Templates list =>
got cartridges templates list
[Info  - 09:28:52] Controllers list =>
[Info  - 09:28:52] Properties list =>
[Info  - 09:28:52] Configuration done
got cartridges properties list, size: 2
got cartridges properties list, parse time: 1.37]
got cartridges controllers list, parse time: 2.066]
req definition:file:///c%3A/Users/StephaneBlanchon/Workspaces/SEPHORA/estore-sfcc-sephora/cartridges/app_sephora_controllers/cartridge/controllers/OnePageCheckout.js
no definition: 135ms 
no completion: 56ms 
no completion: 44ms 
no completion: 54ms 
no completion: 58ms 
no completion: 41ms 
req definition:file:///c%3A/Users/StephaneBlanchon/Workspaces/SEPHORA/estore-sfcc-sephora/cartridges/app_sephora_core/cartridge/scripts/util/DeliveryUtils.js
no definition: 86ms 
no completion: 25ms 
no completion: 65ms 
```

**Comment by SqrTT** [comment]
Hi @SBlanchon-Viseo 
Thank you for info, but I see no error messages `Unhandled method textDocument/definition` in your log

**Comment by SqrTT** [comment]
please note: setting `extension.prophet.cartridges.path` expected to contain cartridges path like in BM (list of cartridges names), example: `app_storefront_controllers:app_storefront_core:bc_library` (simply copypasted from BM) but not file system path to cartridges root.

**Comment by SBlanchon-Viseo** [comment]
I updated my previous POST... And just thought about it : 
- maybe problem arises when i set a "cartridge" : ["some-cartrige", "another-cartrige"] property in my dw.json !?

**Comment by SqrTT** [comment]
could you update to 1.3.29 (just released) and provide new logs (added few potential places to check)

**Comment by SqrTT** [comment]
any further info?

**Comment by IaroslavVerstiukOSF** [comment]
on my side issue is not reproducing anymore

**Comment by SBlanchon-Viseo** [comment]
Hello @SqrTT , i do not have any problem anymore since i updated Prophet Debugger to 1.3.29 ! Thanks.
