### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by LucasReyre** [SqrTT/prophet#261]
**Describe the bug**
Since a few time I got errors when trying to upload cartridges on my sandbox

Logs are : 
Error: Error: write ECONNRESET
Trying to re-upload cartridge

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version : 1.50.1
 - The extension version: 1.3.28

**Additional context**

**Comment by SqrTT** [comment]
some people has been reported that sandbox restart may help in such cases

**Comment by LucasReyre** [comment]
Yes I already did it but I still got the error

**Comment by SqrTT** [comment]
Could you try to connect another sandbox to see if error persist, please?

**Comment by SqrTT** [comment]
Is the issue still actual?
