### ISSUE TITLE
Debugger conditional breakpoints behave as standard breakpoints

### ISSUE THREAD

**Issue by christophe-bouchy** [SqrTT/prophet#262]
Hi all,

In a loop of thousands of products, I tried to use the conditional breakpoints provided by VS Code to focus on the context I need but the condition seems to be ignored and the breakpoints behave as standard breakpoints.

When I hover a conditional breakpoint, I get the following message :
![image](https://user-images.githubusercontent.com/56033092/97298684-17c46b00-1854-11eb-81c3-2f7640908d96.png)

Is it a bad configuration on my side ?
Or is it a feature that the extension doesn't handle (yet) ?

Thanks for your answers 😄

**Comment by SqrTT** [comment]
Hi @christophe-bouchy 
Yeap. conditional breakpoints is not implemented yet.  VSCode and SDAPI supports conditional breakpoints, only extension support should be added.

**Comment by christophe-bouchy** [comment]
Thx for the answer @SqrTT .

I will wait for this Christmas gift quietly 😋

**Comment by SqrTT** [comment]
this took more then "until Christmas" but 1.4.0  has conditional breakpoints. Please confirm it works for you

**Comment by christophe-bouchy** [comment]
Hi @SqrTT,
Thanks for the update, it's a great and useful feature and I think I wasn't the only one to wait for it :-).

It's OK for me for the few tests I did.
I'll let you know if I discover some related issues.
