### ISSUE TITLE
version VS code-version in dw.json

### ISSUE THREAD

**Issue by christophe-bouchy** [SqrTT/prophet#263]
Hello all,

As said in the title : what is the difference between using "version" or "code-version" in the dw.json file ?

Why is there two ways of defining the same data ?
Which one must be preferred ?

Thanks for your answers 😄

**Comment by SqrTT** [comment]
those are just aliases. The extension use `dw.json` but it's not standardized and it's used by different tools like `dw-upload` or `sgmf-scripts`. some of them use `version` while other `code-version`.

**Comment by christophe-bouchy** [comment]
Ok, thanks for the answer 👍
