### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Zaid-Sarfraz** [SqrTT/prophet#266]
- Issue Type: `Performance`
- Extension Name: `prophet`
- Extension Version: `1.3.29`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.0`

[SqrTT.prophet-unresponsive.cpuprofile.txt](https://github.com/SqrTT/prophet/files/5707090/SqrTT.prophet-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by SqrTT** [comment]
Hi @Zaid-Sarfraz 
I'm not sure what kind of issue it causes to you?
CPU profile is really wired it shows that prophet consumes CPU. But in the same moment self time of execution is  ~250 ms. It looks like disk IO takes much time. Could you try to disable other extension to see if prophet has mentioned issues, please?

PS. Most likely during start-up when many extensions are executed bottleneck is disk IO. But this is just assumption.

**Comment by SqrTT** [comment]
closing since no detailed info about an issue.
