### ISSUE TITLE
Debugger not getting setup due to one cartridge getting uploaded multiple times sfcc

### ISSUE THREAD

**Issue by digitester22** [SqrTT/prophet#267]
**Describe the bug**
For some plugin cartridges like cybersource, there are lot of folders inside which there is a cartridge. The structure looks something like this
![image](https://user-images.githubusercontent.com/76527774/103011824-95f57300-4560-11eb-993b-83ed1dcfc89c.png)

The actual cartridge folder is the LINK_cybersource folder, but when I try to add a debug point I get the below error message and unable to add a breakpoint. It seems that Prophet is thinking of int_cybersource_sfra as a cartridge.

What I also see in the sandbox is 2 cartridges uploaded. One is LINK_cybersource and other is int_cybersource_sfra when ideally, the only cartridge that should be uploaded is int_cybersource_sfra
![image](https://user-images.githubusercontent.com/76527774/103012717-0224a680-4562-11eb-87e7-b6dd1fdb2e59.png)

Using 1.52.1 version of VSCode and 1.3.29 version of prophet.

**Comment by SqrTT** [comment]
Hi @digitester22 

thanks for reporting. The extension has two ways how determinate cartridges
* manually - defined on `dw.json`
* automatically - based on `.project` file

Most likely in your case is used automatic way based on `.project` file. Could you,please, verify if you have `.project` file in `int_cybersource_sfra` which cause false positive cartridge detection (file may be hidden),

By the way you may verify if cartridge detection works fine by verifying list of cartridges (it should match your real cartridges):
![image](https://user-images.githubusercontent.com/1271300/103207566-54214f80-4907-11eb-9b8e-2a15537c0fc8.png)

**Comment by digitester22** [comment]
Hi @SqrTT ,

Thanks for your reply. As you see there is no .project file even if I show the hidden files

![image](https://user-images.githubusercontent.com/76527774/103231769-f148ac00-4938-11eb-8630-ea47e77e44e5.png)

In the cartridges section, it is only showing the correct one. i.e. LINK_cybersource.

Also I don't have anything in the dw.json file. So not sure why is int_cybersource_sfra is getting uploaded as independent cartridge

**Comment by SqrTT** [comment]
@digitester22 
seems I was able to track down an issue and tried to fix in v1.3.32. Could you update and verify if it's works for you, please?

**Comment by digitester22** [comment]
Hi @SqrTT It is still not working. I don't get a "unable match cartridge" error like before but the debugger is still not stopping and all the changes I make go as a new cartridge int_cybersource_sfra instead of those changes happening in LINK_cybersource

When doing a clean build it correctly detects, uploads LINK_cybersource and gives option to delete  int_cybersource_sfra as it is not in cartridge path. The problem comes when we save a file and the prophet uploader uploads a single file

**Comment by SqrTT** [comment]
Indeed there was the same issue with single file upload. It should be fixed in v1.3.33. Could you verify if fixes issue for you, please?

**Comment by SqrTT** [comment]
the issue supposed to be fixed in 1.3.33. If this is not true, please, reopen.
