### ISSUE TITLE
Prophet uploader parse undefined

### ISSUE THREAD

**Issue by alaguzzi17** [SqrTT/prophet#268]
When i open a template (isml), a popup is shown with the following message:
Cannot read property 'parse' of undefined
How can i fix the issue?
Thanks
![prophet_error](https://user-images.githubusercontent.com/58829798/103873140-a44e9d80-50cf-11eb-8851-91e5ad89a1b4.png)

**Comment by SqrTT** [comment]
@alaguzzi17 
Appropriate for reporting. Should be fixed in v1.3.33. Could you verify and confirm if it works for you, please?

**Comment by alaguzzi17** [comment]
Hi @SqrTT 
thank you for your feedback. It's ok now.
Regards
Andrea
