### ISSUE TITLE
Create Cartridge not coming with client folder

### ISSUE THREAD

**Issue by luisfelliperaphael** [SqrTT/prophet#269]
When I use the create cartridge option in the debugger it creates fine but the client folder that the cartridge is supposed to have isn't there, am I doing something wrong or this is correct?

**Comment by SqrTT** [comment]
@luisfelliperaphael 
thank you for spotting this, fixed in v1.3.33. Could you verify and confirm if it works for you, please?

**Comment by luisfelliperaphael** [comment]
Yeah, its fixed, thanks :)
