### ISSUE TITLE
Cartridge array in dw.json is ignored.

### ISSUE THREAD

**Issue by ghgofort** [SqrTT/prophet#27]
When I use the uploader included in the prophet package the cartridges array that is specified in my dw.json file is ignored and all the folders in the project directory are uploaded/watched instead. 

The settings in the dw.json file work without issue when I use the dwupload package from the terminal.

Screen Shot of the Prophet Uploader output:
![image](https://user-images.githubusercontent.com/16811151/28378564-74bdba62-6c65-11e7-8861-75b0f2ec8b09.png)

```json
// dw.json
{
  "hostname": "dw25-web-********.demandware.net", // Modified for Posting
  "username": "*********", // Removed for Posting
  "password": "*********", // Removed for Posting
  "code-version": "VSCode",
  "cartridge": [
    "app_blogparser",
    "app_cssuite_2_0",
    "app_ctr",
    "app_loyalty",
    "app_ordershippingstatus",
    "app_returns",
    "app_spc",
    "app_translation",
    "bc_filemonitoring",
    "bc_integrationframework",
    "bm_adyen",
    "bm_catalogreducer",
    "bm_instore",
    "bm_tools",
    "core_commerce",
    "core_commerce_richUI",
    "core_controllers",
    "core_deckers",
    "int_3DS",
    "int_accertify",
    "int_adyen",
    "int_affiliatewindow",
    "int_bizrate_survey",
    "int_buildmanager",
    "int_channeladvisor",
    "int_CJ",
    "int_csvexport",
    "int_customerexporttool",
    "int_DCD_avatax",
    "int_DPDPickup",
    "int_googleFeed",
    "int_hreflang_sitemap",
    "int_powerreviews",
    "int_QAS",
    "int_simplefeeds",
    "int_sitecatalog",
    "int_taxclass",
    "int_tealium",
    "int_translation",
    "int_truefit",
    "site_hoka_v2",
    "site_koolaburra",
    "site_sanuk",
    "site_services",
    "site_teva_us",
    "site_teva_sanuk",
    "site_ugg_closet",
    "site_ugg_us"
  ]
}
```

Folder Structure:
- dw-gg
  -- .DS_Store
  -- .babelrc
  -- .editorconfig
  -- .eslintignore
  -- .eslintrc.json
  -- .flowconfig
  -- .git/
  -- .gitignore
  -- .idea/
  -- .metadata/
  -- .recommenders/
  -- .stylelintignore
  -- .stylelintrc.json
  -- .vscode/
  -- CONTRIBUTING.md
  -- DemandwareServer/
  -- GitVersion.yml
  -- README.md
  -- RemoteSystemsTempFiles/
  -- app_blogparser/
  -- app_cc/
  -- app_contentizer/
  -- app_cssuite_2_0/
  -- app_ctr/
  -- app_loyalty/
  -- app_ordershippingstatus/
  -- app_proaccount/
  -- app_returns/
  -- app_spc/
  -- app_translation/
  -- bc_csc_customization/
  -- bc_drivecommerceintegration/
  -- bc_filemonitoring/
  -- bc_integrationframework/
  -- bm_adyen/
  -- bm_catalogreducer/
  -- bm_drivecommerce/
  -- bm_instore/
  -- bm_integrationframework/
  -- bm_paypal_v16_1_0/
  -- bm_tools/
  -- core_commerce/
  -- core_commerce_emea/
  -- core_commerce_richUI/
  -- core_controllers/
  -- core_deckers/
  -- **dw.json**
  -- flow-libs/
  -- gulpfile.js
  -- int_3DS/
  -- int_CJ/
  -- int_DCD_avatax/
  -- int_DPDPickup/
  -- int_QAS/
  -- int_accertify/
  -- int_adyen/
  -- int_affiliatewindow/
  -- int_bizrate_survey/
  -- int_buildmanager/
  -- int_channeladvisor/
  -- int_cosmiccart/
  -- int_csvexport/
  -- int_customerexporttool/
  -- int_googleFeed/
  -- int_hreflang_sitemap/
  -- int_janrain/
  -- int_ocapi_ext/
  -- int_ocapi_ext_controllers/
  -- int_ocapi_ext_core/
  -- int_ocapi_ext_test/
  -- int_ocapi_ext_v6/
  -- int_paypal_v16_1_0/
  -- int_paypal_v2_2_0/
  -- int_powerreviews/
  -- int_simplefeeds/
  -- int_sitecatalog/
  -- int_taxclass/
  -- int_tealium/
  -- int_translation/
  -- int_truefit/
  -- int_verifone_dss/
  -- int_verifone_dss_controllers/
  -- int_verifone_dss_core/
  -- int_vwo_plugin/
  -- jsconfig.json
  -- node_modules/
  -- out/
  -- package.json
  -- site_ahnu_v2/
  -- site_hoka_emea_v2/
  -- site_hoka_v2/
  -- site_koolaburra/
  -- site_sanuk/
  -- site_services/
  -- site_teva/
  -- site_teva_sanuk/
  -- site_teva_us/
  -- site_tevaeurope/
  -- site_ugg_closet/
  -- site_ugg_us/
  -- site_ugg_v2/
  -- site_uggeurope/
  -- site_ugguk/
  -- support_order_watcher/
  -- yarn.lock

**Comment by SqrTT** [comment]
thanks for reporting, I'll take a look. Small question: are you on MacOS? (I've heard that MacOS users have such issue)

**Comment by SqrTT** [comment]
the issue should be fixed in v0.7.0. Could you please confirm that issue is fixed?

**Comment by ghgofort** [comment]
@SqrTT - This issue is resolved with the new release.  Thanks for the quick response.  BTW, I am on MAC OSX.

**Comment by SqrTT** [comment]
thanx, closing
