### ISSUE TITLE
List cartridges alphabetically.

### ISSUE THREAD

**Issue by bobthewes** [SqrTT/prophet#271]
Right now the cartridges seem to re-arrange themselves whenever I refresh, and I'm not sure what the order is based on. Can you please add an option to arrange them alphabetically?

**Comment by SqrTT** [comment]
thank you for idea, I'll add such option.

**Comment by bobthewes** [comment]
Thank you!

**Comment by SqrTT** [comment]
this is implemented in 1.4.33

**Comment by bobthewes** [comment]
This makes me extremely happy. Thank you!
