### ISSUE TITLE
Hundreds of warn and error messages in Script Language Server output tab

### ISSUE THREAD

**Issue by christophe-bouchy** [SqrTT/prophet#272]
**Describe the bug**
Hi all,
Since the last update, I (and few colleagues) have a high number of notifications of this kind poping every seconds while coding :

![image](https://user-images.githubusercontent.com/56033092/108543624-9bafd080-72e5-11eb-9a52-46930ee350cc.png)

These notifications are related to the messages in output tab "Script Language Server".
Even if this tab isn't active, it automatically comes in front of other displays to show multiple messages of this kind : 

```
[Error - 17:36:52] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Could not find source file: '[file]'.
  Code: -32603 
[Error - 17:36:52] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Could not find source file: '[file]'.
  Code: -32603 

[Warn  - 18:22:15] resolver: unable detect path "dw.web.URLUtils" for "[file]"
[Warn  - 18:22:15] dw-resolver: unable detect path "~/cartridge/scripts/..." for "[file]"
```

Is it related to the newly added ES6 support for SFCC ?
Is so, could it be possible to have a setting to enable / disable this new support for those of us who currently don't need it and want to keep the previous behavior ?

Thanks in advance :-)

**Desktop :**
 - OS: Windows 8
 - VSCode version: 1.53.2
 - The extension version 1.4.0

**Comment by SqrTT** [comment]
Hi @christophe-bouchy 
This error seems is nit handed by code. I've added sanity check for this cases so you will not see error popup. Please confirm if you have popup in v1.4.1,

But this will not solve issue itself, seems for some reason the extension can't find file. Most likely this is related windows path format (ie `SOME_DIR` is the same `some_dir`). Would be great to have more detail about it.

It's not related to SFCC and ES6 but related to TypeScript server which is part for extension now. This allow to provide better code assist and bundle extension with SFCC classes definition. Currently no way to disable it. Probably I'll add some switch in feature releases.

**Comment by christophe-bouchy** [comment]
Hi @SqrTT ,
Thanks for the quick reply and fix.

With v1.4.1, I didn't receive endless notifications anymore and the output tab "Script Language Server" doesn't show on top of other tabs either (even if warnings and errors are still logged inside).

Maybe the (new) one below could help you ?

```
[Error - 15:04:15] wrapper error: 
Error: Could not find source file: '[file]'.
 Error: Could not find source file: '[file]'.
    at v ([...]\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:2877867)
    at Object.getQuickInfoAtPosition ([...]\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:2887024)
    at [...]\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:212444
```

Thanks for your time :-)

**Comment by SqrTT** [comment]
would be possible to share file path instead of placeholder `[file]` (I believe this is placeholder instead as it appears in log, correct?)?
Of course with removed/replaced private info.

**Comment by christophe-bouchy** [comment]
Yes it's a placeholder for the file I worked on while the error occured.
Caution : the mentioned method is not always the same (**_getCodeFixesAtPosition_** / **_getQuickInfoAtPosition_**), for example : 

```
[Error - 10:39:18] wrapper error: 
Error: Could not find source file: 'int_mycartridge/cartridge/scripts/util/MyUtils.js'.
 Error: Could not find source file: 'int_mycartridge/cartridge/scripts/util/MyUtils.js'.
    at v (c:\Users\myuser\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:2877867)
    at Object.getCodeFixesAtPosition (c:\Users\myuser\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:2894498)
    at c:\Users\myuser\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:199695
[Error - 10:39:19] wrapper error: 
Error: Could not find source file: 'int_mycartridge/cartridge/scripts/util/MyUtils.js'.
 Error: Could not find source file: 'int_mycartridge/cartridge/scripts/util/MyUtils.js'.
    at v (c:\Users\myuser\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:2877867)
    at Object.getQuickInfoAtPosition (c:\Users\myuser\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:2887024)
    at c:\Users\myuser\.vscode\extensions\sqrtt.prophet-1.4.1\dist\scriptServer.js:2:212444
```

To give some more information for warnings logs about path detection, they mostly follow this format : 

```
[Warn  - 10:38:15] resolver: unable detect path "my_mvc" for "app.js"
[Warn  - 10:38:15] resolver: unable detect path "app_core/cartridge/config" for "configuration.js"
[Warn  - 10:38:15] resolver: unable detect path "*/cartridge/scripts/init/serviceInit" for "app_core/cartridge/scripts/util/Geolocation.js"
[Warn  - 10:38:15] resolver: unable detect path "modules/enum.ds" for "int_mycartridge/cartridge/scripts/util/MyUtils.js"
[Warn  - 10:38:15] resolver: unable detect path "dw/campaign/CouponStatusCodes" for "app_core/cartridge/scripts/checkout/CouponUtils.js"
[Warn  - 10:38:15] dw-resolver: unable detect path "../lib/myLib.ds" for "int_mycartridge/cartridge/scripts/init/serviceInit.js"
[Warn  - 10:38:15] dw-resolver: unable detect path "~/cartridge/scripts/lib/anotherLib.ds" for "int_mycartridge/cartridge/scripts/notification/validation.js"
```

You also mentioned the possibility to create a switch to toogle TypeScript Server parsing : it would be great to be able to disable it (at least while this warnings / errors are spamming the console).

Thanks for your time and work :-)

**Comment by thdoan** [comment]
I've encountered the same "wrapper error" as @christophe-bouchy. Since my Prophet works normally (I'm able to debug), I keep the output panel closed and just ignore these errors, but it would be nice to figure why these errors are produced and resolve this.

I'm using Prophet v1.4.12 in this setup:

Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

I have these user settings:
```
    "extension.prophet.cartridges.view.enabled": false,
    "extension.prophet.clean.on.start": false,
```

**Comment by SqrTT** [comment]
@thdoan version 1.4.13 contain fix for your case. Could you please confirm it works for you?

**Comment by SqrTT** [comment]
I believe this can be closed. Feel free to reopen if still actual.

**Comment by christophe-bouchy** [comment]
On my side, I still have these kind of messages in tue "Script Language Server" output tab, but don't know if it's related or not to the initial issue : 

**Errors :** 
> => agregatedForms
(node:11660) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'my-repository\.vscode\system-objecttype-extensions.d.ts'
(node:11660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11660) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'my-repository\.vscode\forms.d.ts'
(node:11660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Warnings :** 
> resolver: unable detect path "XXX" for "YYY"

or

> dw-resolver: unable detect path "XXX" for "YYY"

If more details needed, I think you can find them in the log file I sent you earlier.

Thanks in advance 😃

**Comment by SqrTT** [comment]
I've created #283 to track UnhandledPromiseRejectionWarning

regarding ` unable detect path "XXX" for "YYY"` this is code related staff.
seems you are trying to `require` XXX from file YYY but XXX is unreachable for some reason, it's not `.js` file  or it's not present in cartridge path

**Comment by christophe-bouchy** [comment]
Ok I see, I'll investigate the point about path detection some day if I find time.

Thanks also for the new ticket #283.
