### ISSUE TITLE
when debugger run the error message is show "Unable get cartridges list"

### ISSUE THREAD

**Issue by vinzheng** [SqrTT/prophet#273]
**Describe the bug**
in vs code I want to debug source in commerce cloud project.
when debugger run the error message is show "Unable get cartridges list"

**Screenshots**
![{E815F28D-B550-4113-BBFA-E4E3847C907C} png](https://user-images.githubusercontent.com/79983822/109814429-75851b80-7c69-11eb-84dc-8641f0bc4a48.jpg)
![{172AF79F-C19E-4956-9895-39C18D4E5864} png](https://user-images.githubusercontent.com/79983822/109814605-a8c7aa80-7c69-11eb-9588-b0d9f2311f66.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode version: 1.53.2
 - Prophet Debugger version : 1.4.9

I want to know how fix the question.

**Comment by kapil-srivatsa** [comment]
Hello @vinzheng, I'm facing this same issue. Can you please let me know how did you fix it?

**Comment by SqrTT** [comment]
this may happen if yo u don't have `.project` in your workspace or have it in ignore lists
