### ISSUE TITLE
Debugger won't connect with MFA

### ISSUE THREAD

**Issue by IvayloIvanovTryzens** [SqrTT/prophet#274]
When trying to start the debugger with MFA getting the following trace. Code upload works ok with the provided credentials.

To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":false,"supportsFunctionBreakpoints":false,"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":false,"supportsStepBack":false,"supportsSetVariable":false,"supportsRestartFrame":false,"supportsStepInTargetsRequest":false,"supportsGotoTargetsRequest":false,"supportsCompletionsRequest":false,"supportsRestartRequest":false,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":false,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":false,"supportsLoadedSourcesRequest":false,"supportsLogPoints":false,"supportsTerminateThreadsRequest":false,"supportsSetExpression":false,"supportsTerminateRequest":false,"exceptionBreakpointFilters":[]}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"DebuggerConfig","success":true}
From client: launch({"type":"prophet","request":"launch","name":"Attach to Sandbox","trace":true,"__configurationTarget":5,"__sessionId":"a0c7cca1-e195-4e80-8210-0ea5473f25f2"})
To client: {"seq":0,"type":"event","event":"terminated"}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"500\n undefined"}}
500
 undefined
From client: disconnect({"restart":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Disconnecting...\n"}}
Disconnecting...

**Comment by SqrTT** [comment]
HI @IvayloIvanovTryzens 
Thank you for reporting.

I can't understand a reason fro such behavior. Could you please add `"verbose": true,` to your `dw.json` and provide output, it will show more request details to sandbox.

PS. please remove private data from output before sharing.

**Comment by SqrTT** [comment]
also please double check your credentials, especially words case. Username is case sensitive in debugger.

**Comment by IvayloIvanovTryzens** [comment]
Thanks a lot didn't realize that the username is only case sensitive for the debugger, closing the issue
