### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'my-repository.vscode\system-objecttype-extensions.d.ts'

### ISSUE THREAD

**Issue by SqrTT** [SqrTT/prophet#283]
On my side, I still have these kind of messages in tue "Script Language Server" output tab, but don't know if it's related or not to the initial issue : 

**Errors :** 
> => agregatedForms
(node:11660) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'my-repository\.vscode\system-objecttype-extensions.d.ts'
(node:11660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11660) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'my-repository\.vscode\forms.d.ts'
(node:11660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Warnings :** 
> resolver: unable detect path "XXX" for "YYY"

or

> dw-resolver: unable detect path "XXX" for "YYY"

If more details needed, I think you can find them in the log file I sent you earlier.

Thanks in advance 😃

_Originally posted by @christophe-bouchy in https://github.com/SqrTT/prophet/issues/272#issuecomment-815821268_

**Comment by SqrTT** [comment]
@christophe-bouchy could you please confirm if  `.vscode` missing in your repo?

**Comment by christophe-bouchy** [comment]
@SqrTT you're right !
I never realized this point before but I don't currently have a .vscode folder on my current project.

Maybe related to the fact I'm working with a workspace regrouping several repositories.
I don't know how this folder should behave in this situation.

Sorry if I raised a "false" issue related to a wrong / missing configuration 😞.

**Comment by SqrTT** [comment]
that's good issue :)
I've newer through there is projects where `.vscode` folder may be missed. Should be fixed  in v1.4.16

Thank you for spotting this.

**Comment by christophe-bouchy** [comment]
My project sources are dispatched under 4 repositories and I only have a `.code-workspace` file at the root to be able to see them at once in VS Code explorer.

![image](https://user-images.githubusercontent.com/56033092/114059487-b558a780-9894-11eb-83b1-7db2393a68a4.png)
![image](https://user-images.githubusercontent.com/56033092/114059719-f0f37180-9894-11eb-89f2-05502cfc2012.png)

Not sure if it's the right way to do it (without `.vscode` folder I mean) but it works and I never really looked further 😅  

Thanks for the fix anyway, I'll try it when available 😃
