### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by helloivankorGit** [SqrTT/prophet#287]
**Description**
In process of cartridges uploading I'm getting an error - Error: Error: 413. Request Entity Too Large

**To Reproduce**
1. Cick on 'Prophet: Enable Upload'
2. Uploading process stops on one of the cartridges with message 'Deleting remote zip...'
3. After some minutes of waiting - getting an error. Error: Error: 413. Request Entity Too Large
4. Then "Trying to re-upload cartridge". Again and again

Thanks.

**Comment by SqrTT** [comment]
hi @helloivankorGit 
Thanks for reporting. Is there chance some of your cartridge is to big? Most likely it has more 100Mb... could you try to zip manually and see it's size.

**Comment by helloivankorGit** [comment]
hi @SqrTT 
Yep, it's almost 200mb )

**Comment by SqrTT** [comment]
100Mb is limitation of SFCC's WebDav. Nothing I can do here. Potentially you have redundant files there (redundant means not used by sandbox itself), like images or node_modules folder

**Comment by helloivankorGit** [comment]
Nope, there was too much static images =) I'm already fixed this problem. Thank you. This made my day
