### ISSUE TITLE
Disable auto-formatter

### ISSUE THREAD

**Issue by annoyingmouse** [SqrTT/prophet#288]
Hi there,

is it possible to disable the auto-format on save? And, if so, how would I go about doing so?

Further, though, would I be able to configure the auto-format at some point in the future? I saw there was a discussion of this in a previous issue, but I was unsure how that was implemented.

Thanks in advance

**Comment by SqrTT** [comment]
Hi @annoyingmouse 
auto-format is not the extension feature this is VSCode. Basically, it should be disable via VSCode setting:

![image](https://user-images.githubusercontent.com/1271300/115680611-6282f380-a35c-11eb-8c41-c400b3c7e963.png)

**Comment by annoyingmouse** [comment]
Thanks, @SqrTT you've saved my lovely, if obscure, formatting style :-)
