### ISSUE TITLE
Code uploading again and again

### ISSUE THREAD

**Issue by adiagr4355** [SqrTT/prophet#291]
If I save a file, Complete code/cartridge is uploading again and again. Please help me to resolve this issue.

Prophet version: 1.4.17
VS code version: 1.57.0-insider
Device: MAC

Please let me know if any other details required.

**Comment by SqrTT** [comment]
please investigate prophet output, it may contain answers for such behavior

![image](https://user-images.githubusercontent.com/1271300/119104677-345d0600-ba25-11eb-8e86-63d6854300c3.png)

**Comment by adiagr4355** [comment]
@SqrTT Thanks for the update!!

Those config are fine, Issue is all cartridges are uploading again and again, when I make change to any file. In windows machine it was working fine but in mac it is having issue like uploading all cartridge again and again. I have my project folder in the Desktop. Is that the issue. Do I need to move the Project folder to any other location except desktop in MAC device?

**Comment by adiagr4355** [comment]
@SqrTT Any update on this??

**Comment by SqrTT** [comment]
@adiagr4355  Have look into output?

Could you provide it here (don't forget remove sensitive info)?

**Comment by adiagr4355** [comment]
@SqrTT Please find below output
![image](https://user-images.githubusercontent.com/76766527/120361688-c28b9300-c327-11eb-9733-f83e57615994.png)

**Comment by SqrTT** [comment]
Hi @adiagr4355 
the screenshot is not very useful, would be better to provide all output including moment when the issue happen

**Comment by adiagr4355** [comment]
@SqrTT Thanks!! Issue is resolved now, Issue was happening as desktop folder was uploading to icloud. So, moved the project folder to some other location and Now code is not uploading again and again.

Closing the ticket.
