### ISSUE TITLE
Compatibility mode 21.2

### ISSUE THREAD

**Issue by carey** [SqrTT/prophet#292]
**Is your feature request related to a problem? Please describe.**

As of release 21.2 earlier this year, Salesforce B2C Commerce supports a new compatibility mode which affects the kind of JavaScript that it supports, as described at https://documentation.b2c.commercecloud.salesforce.com/DOC1/topic/com.demandware.dochelp/content/b2c_commerce/topics/site_development/b2c_compatibility_mode_considerations.html.

**Describe the solution you'd like**

I would like to be able to configure the Prophet extension to support ES6 types like `Map`, `Set`, iterables and iterators, as I would by setting the target environment to `ES6` in TypeScript.

**Describe alternatives you've considered**

The Prophet extension still works, but we have to ignore any errors highlighted in the editor about newer JavaScript functionality like the `Map` class, and we don't get any code assistance with them.

**Comment by SqrTT** [comment]
hi @carey 
The extension already support ES6 for backend files. Probably only definitions for `Map`, `Set` are missing. I'll add them once have possibility.

Please note: B2C supports only limited amount of ES6 features and they may work in different way than standard.

**Comment by carey** [comment]
Thanks. The things I've run across myself that work in B2C Commerce but not in VS Code are `Map`, `Set` and `for..of` loops on iterables. In particular, this function:

```javascript
/**
 * @template T
 * @param {dw.util.Collection.<T>} collection
 * @yields {T}
 */
function* iter(collection) {
    var iterator = collection.iterator();
    while (iterator.hasNext()) {
        yield iterator.next();
    }
}
```

when used like `for (item of iter(collection))` displays errors.

(I've since decided that this is very clever but not very maintainable.)

**Comment by SqrTT** [comment]
thank you @carey  for highlighting this.

I've made new release 1.4.18 to address this issue, Could you confirm it's working for you, please?

**Comment by carey** [comment]
Thanks. I've tested the update with my new code and it's working well.
