### ISSUE TITLE
Prophet upload is not working, although sgmf-scripts is working fine with npm run uploadCartrigdges. This is blocking me in the debug process and everytime i need to upload the code manually by sgmf

### ISSUE THREAD

**Issue by anujtyagi10** [SqrTT/prophet#294]
Hi, 

I am new to salesforce commerce cloud, but as part of the training i created a cartridge in addition to the imported app_storefront_base. It was working fine for couple of weeks but since last few days, prophet is not able to detect cartridges even when both app_storefront_base and app_training1 has .project file, in fact i didnt change the project structure, seems it stopped working on its own.

Steps i took to resolve this issue:
1. set-up a new folder and added the files  and tried to upload only app_storefront_base without adding any other cartridge.
2. Reinstalled both visual studio code and prophet and also their previous versions.
3. Added the cartridge in dw.json file as well but no luck.
4. I couldnt find files.exclude as mentioned in the message

Paths set-up in BM:

![image](https://user-images.githubusercontent.com/66786224/120242035-48460a80-c264-11eb-935f-53c6ec5c3ee6.png)

![image](https://user-images.githubusercontent.com/66786224/120242062-4f6d1880-c264-11eb-9455-89cc4e73de2c.png)

![image](https://user-images.githubusercontent.com/66786224/120241577-55aec500-c263-11eb-89fb-7d038d5a85fd.png)

![image](https://user-images.githubusercontent.com/66786224/120241457-13858380-c263-11eb-9e47-96eebe4a96f7.png)

Any help would be greatly appreciated. There is not much documentation on internet.

**Comment by anujtyagi10** [comment]
Can someone please help here?

**Comment by SqrTT** [comment]
Hi @anujtyagi10 
Seems you have `.project` in exclusions.

and you have warning about it
![image](https://user-images.githubusercontent.com/1271300/120310656-479e8a00-c2df-11eb-96ec-b76901dfee2c.png)

Try to remove it.

**Comment by anujtyagi10** [comment]
Thanks @SqrTT .

Yes, i could see that error but didnt know where i can find files.exclude(i checked the file directories), until i check the file preferences and exclude. Yes, there was an entry for .project which is why it was not recognizing my cartridges even the base SFRA.

Thanks once again, we can close this issue.

**Comment by CP-casp** [comment]
> Thanks @SqrTT .
> 
> Yes, i could see that error but didnt know where i can find files.exclude(i checked the file directories), until i check the file preferences and exclude. Yes, there was an entry for .project which is why it was not recognizing my cartridges even the base SFRA.
> 
> Thanks once again, we can close this issue.

@anujtyagi10 I've got the same problem! What a mission to pinpoint why on earth this is not working. I had the same popups as you and selected to remove all cartridges, but then it didn't upload any after removing them all, of course because it couldn't find any.

Where do you see the "File preferences and exclude" ??
