### ISSUE TITLE
Error when starting to upload files to sandboxes

### ISSUE THREAD

**Issue by tylez** [SqrTT/prophet#301]
When I try to upload code to a Sandbox or debug I get an error message and the process ends with an error.

![image](https://user-images.githubusercontent.com/4256656/130941922-55536f6a-d6a4-4c1e-8136-81a01c2ed33b.png)

1. Go to prophet extension
2. Click on 'more actions' -> Prophet: Enable upload on Cartridges section
3. See error on output tab

**Expected behavior**
Prophet should start upload files to sandbox

**Desktop**
 - OS: Ubuntu 20.04.3 LTS
 - VSCode version:  1.59.1
 - The extension version: 1.4.22 and 1.4.23

**Additional context**
Few days agow, the prophet extension was working correcty, but since yesterday  I get this error each time that I try to upload something to the sandbox. I tried to install prophet extension and vs code but still getting the error.

I have and npm run command to upload code with sfcc-ci and with this command it works correctly

Thanks in advance!

**Comment by SqrTT** [comment]
closing since most likely this is not an issue anymore...
