### ISSUE TITLE
Command 'extension.prophet.command.clean.upload' not found

### ISSUE THREAD

**Issue by thisisdg** [SqrTT/prophet#305]
**Describe the bug**
I have setup the workspace once. The prophet uploader is working there. Then our repository was not hosted. Now we have created a new repository and I am trying to setup a new workspace for it. Whenever I do so and I run the Prophet Clean/Upload command, I get the following error:
![image](https://user-images.githubusercontent.com/56014754/144695517-338230a2-cc61-49db-84e1-16570f13cfbe.png)

**To Reproduce**
1. Setup the workspace for the second time. (The first should be the same workspace with no repository. The second one should be the same workspace targeted to the same sandbox which is a repository.)
2. Run Prophet Clean/Upload command

**Expected behavior**
The upload should start to the targeted sandbox mentioned in the dw.json

**Screenshots**
The screenshot has been attached above.

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 
![image](https://user-images.githubusercontent.com/56014754/144695697-32e0ff6c-d811-40bf-8ca7-a6c9a6258f7c.png)

** Need an urgent solution

**Comment by SqrTT** [comment]
this may happen in case you don't have cartridges in your workspace. Extension is not activated:

Refs:
https://github.com/SqrTT/prophet/blob/master/package.json#L75-L80

**Comment by SqrTT** [comment]
cartridge must contain `*.properties` file under `cartridge` folder
![image](https://user-images.githubusercontent.com/1271300/144877720-7b623da9-2cd6-4842-b8c3-c0e951d9f895.png)

**Comment by thisisdg** [comment]
thanks @SqrTT , this resolved my issue. Its working now.
