### ISSUE TITLE
Log Viewer can't find my dw.json

### ISSUE THREAD

**Issue by Jakobud** [SqrTT/prophet#311]
When I use the log viewer and click on a log I get an error: Unable to open .........Unable to find sandbox configuration (dw.{json,jd})

1. Open Log Viewer 
2. Doubleclick a log file

**Desktop (please complete the following information):**
 - OS: OSX 12.1
 - VSCode version 1.63.2
 - The extension version 1.4.25

My dw.json is at the root of my project folder. Prophet is able to connect to my sandbox and upload/sync files just fine using my dw.json. I'm not understanding why only the Log Viewer can't find the dw.json

**Comment by amarcoli** [comment]
Hi,
i had same issue and resolved with enable Sandbox File System workspace.
I hope you find it useful

**Comment by SqrTT** [comment]
this should be fixed in v1.4.33
