### ISSUE TITLE
Debugger showing 500 undefinedDisconnecting...

### ISSUE THREAD

**Issue by puneetverma7218** [SqrTT/prophet#313]
I can upload cartridges, but when trying to start debugger it's not starting and in debug console, it's showing the following error.

**500
undefinedDisconnecting...**

**To Reproduce**
Open VS Code, try to start the debugger.

**Logs**
http-nio-10.0.14.204-10149-exec-73 com.demandware.core.script.dapi.DebuggerServlet - TEMPORARY ScriptDebu 6fef9d89832a5636976ae5db30 2204233655502804992 - Failed to process request '/servlet/s/-/dw/debugger/v2_0/client', responding HTTP 500 INTERNAL_SERVER_ERROR fault message
Stack trace <ref:6e0443a38c7580540e896d8960390713>

https://github.com/SqrTT/prophet/issues/239#issuecomment-644512665
I have checked this comment as well. Still facing the same issue.
Once it's working while changing code version but again I've started facing the same issue this time while changing code version also it's not working.

@SqrTT Can you please help me with suggestions?

**Comment by SqrTT** [comment]
please double check your credentials, username is case sensitive

**Comment by puneetverma7218** [comment]
my username is in camel case something like this Test.Test@test.com 
and we're using an authentication key as a password.

**Comment by SqrTT** [comment]
could you please try to use postman to emulate request to see responce from sandbox?
```
POST http://hostname:port/dw/debugger/v2_0/client
```
with basic authorization
according to
https://documentation.b2c.commercecloud.salesforce.com/DOC1/topic/com.demandware.dochelp/ScriptDebuggerAPI/latest/Resources/Client.html

**Comment by murgasanu** [comment]
Indeed the problem for me was that the e-mail was written with upper case first letter in my Sandbox, in User List. I have changed this as well in the dw.json file and it is working again. It's funny that untl today, this was no issue :)

**Comment by anupsfcc** [comment]
I copied the **_email id_** mentioned under **_credentials_** section in **_user profile_** page of my **_BM_** and pasted it in **_dw.json_** and it worked.

**Comment by KurakulaHemanthKumar** [comment]
> 

Thanks buddy worked for me
