### ISSUE TITLE
Override template and JS file in another cartridge (via context menu).

### ISSUE THREAD

**Issue by Jupally04** [SqrTT/prophet#314]
**Describe the bug**
Override template and JS file in another cartridge not working

**To Reproduce**
1. Go to cartridge
2. right click on a file inside cartridge
3. click on overide script in another cartridge
4. No change happened.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version :1.63.2
 - The extension version v1.4.25

**Comment by ccantarello** [comment]
Hello @Jupally04 I'have the same issue, how did you resolve?

**Comment by SqrTT** [comment]
usage of `cartridgesPath` is preferred (just copy-past cartridges path from BM)
