### ISSUE TITLE
Repository not up to date?

### ISSUE THREAD

**Issue by qga-emakina** [SqrTT/prophet#320]
Hello @SqrTT, I'm using prophet daily at work and it's working great (many thanks for this great extension!).

I'd love to be able to contribute but it seems like the source code is not being updated since version 1.3.22.

Could you push the latest source code to github?

Thanks in advance

**Comment by SqrTT** [comment]
At this moment I don't consider sync with github. Anyway this should not stop you from contributing. The only difference between this an published version is added typescript features. 

Please feel free to publish your changes I'll add them to main stream.

**Comment by qga-emakina** [comment]
Hello @SqrTT,

I just wanted to avoid useless contributions and avoid conflicts (If I contribute to a file that was modified in your private repository for example).

I believe that there are changes outside of the scope of the typescript support (again I'm just looking at the CHANGELOG in the extension files and comparing to the one on github since I only have that to compare):

For example with the debugger (which I wanted to have a look at) with the 1.3.34: [add] support conditional breakpoints

I also wanted to contribute to the typescript d.ts files. I know that the definitions are taken from https://github.com/SalesforceCommerceCloud/dw-api-types but not as a git submodule (files are copied), so if I contribute to the dw-api-types repository, changes might not be reflected in the extension.

Cheers

Quentin

**Comment by SqrTT** [comment]
Hi @qga-emakina 

I would be happy to merge PR and resolve any conflicts.

Correct, types are get from https://github.com/SalesforceCommerceCloud/dw-api-types. Since I'm owner of dw-api-types repository I'll sync changes with Prophet.
