### ISSUE TITLE
Can't open file with cartridges view

### ISSUE THREAD

**Issue by Gektorian** [SqrTT/prophet#33]
`Unable to open '': Invalid file resource (file://d:\dw\workspace\demandware-www-NDA-com\3rd-party\sitegenesis\app_storefront_controllers\cartridge\controllers\abtestevent.js)`
While try to open` ABTestEvent.js` in `D:\DW\workspace\demandware-www-NDA-com\3rd-party\sitegenesis\app_storefront_controllers\cartridge\controllers\ABTestEvent.js
`

in general I can't open any of the files with cartridges view panel

**Comment by taurgis** [comment]
Looking into it

**Comment by taurgis** [comment]
Pull request: https://github.com/SqrTT/prophet/pull/34 open to fix the Windows issue.

**Comment by SqrTT** [comment]
Should be fixed in v0.9.1. Please confirm.

**Comment by Gektorian** [comment]
working, thanks
