### ISSUE TITLE
Publishing the latest version in the GitHub repository

### ISSUE THREAD

**Issue by jsat** [SqrTT/prophet#331]
Hi,
Thank you for providing us with a great extension.

I have one request.

The version of Prophet Debugger offered in Visual Studio Marketplace is 1.4.30.
On the other hand, the version available on GitHub repository, I believe, is 1.3.22.
(as of August 27, 2022)

If possible, I hope you will release the latest version in the GitHub repository in the future.

Sorry if I have misunderstood.

Regards,
jsat

**Comment by SqrTT** [comment]
duplicate of https://github.com/SqrTT/prophet/issues/320

**Comment by jsat** [comment]
I apologize for any inconvenience caused.
Noted.
