### ISSUE TITLE
SFCC Error: webdav timeout while uploading Cartridges

### ISSUE THREAD

**Issue by pedrocapgemini** [SqrTT/prophet#334]
I'm trying to upload the cartridges, but before uploading the last cartridge, this error occurs:

"Error: webdav timeout
Trying to re-upload cartridge"

And then it tries to upload it again, but with no success. After some time, it tries to reupload all cartridges again.

I've seen some posts about increasing webdav timeouts via dw.json file, but I can't find any doc about how to pass this parameter in the dw.json file.

Can anyone help me ?

**Comment by SqrTT** [comment]
@pedrocapgemini Have you tried `timeout` property in `dw.json`? (please note: you should have installed 1.4.30 version or above) 

PS. If 40 second is not enough for your sandbox most likely the issue is not with timeout.

**Comment by pedrocapgemini** [comment]
> @pedrocapgemini Have you tried `timeout` property in `dw.json`? (please note: you should have installed 1.4.30 version or above)
> 
> PS. If 40 second is not enough for your sandbox most likely the issue is not with timeout.

I have not. How can I pass this parameter in dw.json file ?
Also, I checked and the most recent version of prophet I could find is 1.4.18. How can I download 1.4.30 ?

**Comment by SqrTT** [comment]
dw.json
```json
{
"password": "",
"hostname" : "and so on",

"timeout": 60000 <--

}

```

Seems you have old version of VSCode. please update it to latest.

**Comment by pedrocapgemini** [comment]
> dw.json
> 
> ```json
> {
> "password": "",
> "hostname" : "and so on",
> 
> "timeout": 60000 <--
> 
> }
> ```
> 
> Seems you have old version of VSCode. please update it to latest.

In my VS code, when I try to install or update, the latest version found is 1.4.18. Where can I get the 1.4.30 ?

**Comment by SqrTT** [comment]
Please update VSCode to latest version (not a extension but editor/ide), Current version of VSCode is 1.71 ([link](https://code.visualstudio.com/updates/v1_71))

**Comment by pedrocapgemini** [comment]
> Please update VSCode to latest version (not a extension but editor/ide), Current version of VSCode is 1.71 ([link](https://code.visualstudio.com/updates/v1_71))

it worked! Thank you!

**Comment by pedrocapgemini** [comment]
Updating VS code and getting the latest version of prophet worked for me, no more run time error when uploading the cartridges
