### ISSUE TITLE
dw.js isn't working but dw.json is

### ISSUE THREAD

**Issue by Jakobud** [SqrTT/prophet#335]
**Describe the bug**
I have a `dw.json` that works but when I put the same info into a `dw.js` it does not work

**To Reproduce**
The following `dw.json` works for me:

```
{
  "hostname": "xyz-001-sandbox.us01.dx.commercecloud.salesforce.com",
  "username": "me@here.com",
  "password": "123456",
  "code-version": "RefArch"
}
```

But the following `dw.json` does not work:

```
module.export = {
  hostname: "xyz-001-sandbox.us01.dx.commercecloud.salesforce.com",
  username: "me@here.com",
  password: "123456",
  "code-version": "RefArch"
}
```

Error:
```
dw.json hostname: 'xyz-001-sandbox.us01.dx.commercecloud.salesforce.com'
dw.json version: 'undefined'
Unable validate connection!
Please check your credentials (login, password, etc)
Error: Error: 401
```

The information in the files is identical. Not sure what I'm doing wrong.

Also side question: "Do I use `version` or `code-version`? The doc's say `code-version` but `version` seems to work too AND the error says `dw.json version: 'undefined'` no matter which one I use.

What is going on here?

**Comment by aduponchel** [comment]
In `dw.js`, you must use `module.exports` with `s` instead of `module.export`.
I can confirm `dw.js` works on my side. Let me know if you have still the issue after fixing `exports`

**Comment by SqrTT** [comment]
Hi @Jakobud 
Did you have chance to verify if `dw.js` is working with typo fixed?

**Comment by Jakobud** [comment]
Yes that was it. Stupid typo on my part. Thank you!
