### ISSUE TITLE
Error: Please choose configuration first

### ISSUE THREAD

**Issue by monsieurludo** [SqrTT/prophet#336]
I have started using Prophet Debugger for VS Code on Mac (v1.72.2) and I can connect to my sandbox but each time I try to upload (after I created _dw.json_ with the right config at the root of **cartridges**), the output throws 

`Restarting
Error: Please choose configuration first`

I tried enabling logs and additional outputs using 'launch.json' but was unsuccessful in doing so. I can't find any additional documentation on this specific error message and I'm not sure what to do next. Note that there's only 1 dw.json (ie. configuration) in my root folder and there's no popup showing for me where I can choose a configuration.

**Comment by SqrTT** [comment]
Hi @monsieurludo 
The Prophet lookups file in all folders and not just root folder. Also it looks up for `dw.js` files too. Please double check if you have more than one `dw.json` and `dw.js` files

**Comment by monsieurludo** [comment]
Thanks @SqrTT for your help, there was indeed another `dw.json` and suprisingly this morning the popup to choose which dw file displayed but if one clicks away from this popup by mistake, then the console keeps showing the same message and the popup doesn't display anymore - therefore making the choice of dw impossible (other than removing duplicates in any subfolders). 

Perhaps as an improvement the output message can display additional info if the popup doesn't show for other users? (ie. that it found _x_ dw files in all folders and only one must exist).
