### ISSUE TITLE
 the debug starts and then breaks off.

### ISSUE THREAD

**Issue by Kammel-Heib** [SqrTT/prophet#341]
hello I have the problem, the debug starts and then breaks off. the debug console protects me this .
`Unauthorized
 undefinedDisconnecting...
Unauthorized`

the launch.json is correct, workspace is set correctly.

the Prophet works fine

![Capture](https://user-images.githubusercontent.com/36574166/206424279-25c35ed8-0ac2-4c12-891f-cee177b0d150.JPG)

**Comment by lisunovdv** [comment]
Have you tried to restart your sandbox?

**Comment by SqrTT** [comment]
please double check your credentials, username is case sensitive for debugger. probably duplicate of #313

**Comment by Kammel-Heib** [comment]
restart didn't help

**Comment by SqrTT** [comment]
Hi @Kammel-Heib 
Did you have change to verify steps from the issue #313?

**Comment by SqrTT** [comment]
@Kammel-Heib 
Is your issue been fixed?
