### ISSUE TITLE
Debugger throws an error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by ViraOsinaCT** [SqrTT/prophet#342]
When I try to upload all cartridges, Prophet Debugger starts the process, but crashes mid way and throws an error "Client network socket disconnected before secure TLS connection was established".

**To Reproduce**
1. In VS Code click 'Command + Shift + P' or 'Ctrl + Shift + P'
2. Call command 'Prophet: Clean project/Upload all'
3. Scroll down to the Output window. 
4. See error: debugger starts running, uploads several cartridges and then crashes with an error.

**Expected behavior**
All cartridges uploaded successfully. Output shows: Cartridges uploaded successfully

**Screenshots**
Actual output (please see attached screenshot)
<img width="881" alt="image" src="https://user-images.githubusercontent.com/95303580/209836594-171c807e-ae72-469c-9266-af5ea14dc061.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1 
 - VSCode version: Version: 1.62.3 (Universal)
 - The extension version [v1.4.25]

**Additional context**
Credentials for dw.json were double checked;
Laptop was restarted several times as well as VS code;
Pluging prophet debugger was uninstalled and installed again;
Internet connection is stable;

**Comment by SqrTT** [comment]
Hi @ViraOsinaCT 

quick googling shows that issue may be related to configuration of proxy. Could you try to play with config of proxy (disable/enable/change configs) proxy

**Comment by SqrTT** [comment]
Please note you have outdated version of extension current one is `1.4.31` (to be able to update to latest version would be required to update VS Code first, latest version at this moment  is `1.74.3`)

**Comment by SqrTT** [comment]
@ViraOsinaCT Is issue still actual?

**Comment by ViraOsinaCT** [comment]
Thank you everyone for helping, the issue was solved. 
Using proxy or updating VS code did not solve the problem. I removed my cartridge path and added cartridges again one by one, I don't know what was wrong, but the error does not occur anymore.
