### ISSUE TITLE
Facing ETIMEOUTISSUE issue every time when uploading cartridges to sandboxes

### ISSUE THREAD

**Issue by Shubham169-CC** [SqrTT/prophet#348]
whenever trying to upload the files to the sandbox , getting the error _Error!?: Error: connect ETIMEDOUT 3.212.83.232:443_. the behavior is reproducible on various other machines. upload happens for 3-4 cartridges and then this error pops up and after multiple retries to reconnect and upload the cartrdiges , it eventually collapes.

**Comment by SqrTT** [comment]
Hi @Shubham169-CC 
Could you please update the extension version to latest (at this moment this is `1.4.31`) if it's not done yet?

Also on latest version you may play with `timeout` property of `dw.json` to increase timeout (in ms, by default 40 seconds)

**Comment by SqrTT** [comment]
I assume the issue is not actual. Feel free to reopen.
