### ISSUE TITLE
Error: Error: connect ETIMEDOUT XX.XXX.XX.XXX:XXX Trying to re-upload cartridge

### ISSUE THREAD

**Issue by navneetkrD** [SqrTT/prophet#349]
**Describe the bug**
I  know its an older issue but I have been facing this issue since 3 days, it's a network issue for sure, becuase with my mobile hotspot I am able to upload without any issue.
But I can't rely on mobile hotspot, and due to hybrid culture we are also not visiting Office daily, need to figure out the solution with my home network only, if anyone is aware about it please do let me know, apprecite the response.

Note- My ping is also good, below is the response:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 1ms, Average = 1ms

Thanks.

**Desktop (please complete the following information):**
 - OS: Wnidows
 - VSCode version 1.74.3
 - The extension version Prophet Uploader 1.4.31

**Comment by SqrTT** [comment]
Hi @navneetkrD 
thanks for reporting.

Have you tried to increase timeout via `timeout` property of `dw.json` ?
default value is `40000` ms (40 seconds)

**Comment by navneetkrD** [comment]
Hi @SqrTT,

like this right? 
{
  "username": "****",
  "password": "***",
  "hostname": "***",
  "version": "abc",
  "cartridge": [],
  "timeout": 80000
}

I changed it to 80 seconds, still getting that error.

**Comment by SqrTT** [comment]
yes, that's correct. 
Please make sure VS Code is restarted after that change (sometimes restart is required to apply changes)

**Comment by navneetkrD** [comment]
I have changed my network, with different network its working fine. I will close this issue. Not really sure what was  the issue with my previous network.

Anyways thanks for responding @SqrTT.
