### ISSUE TITLE
"Unable detect cartridge" randomly showing up for debugger setup

### ISSUE THREAD

**Issue by federicogiampietro** [SqrTT/prophet#350]
**Describe the bug**
Code upload works fine but randomly i get a "Unable detect cartridge" error when starting the debugger ONLY FOR A SPECIFIC FILE of a cartridge. File might change.

Error is random in the sense that it appears all of a sudden and disappears after a few days. Tried restarting the instance, changing code version, rerunning the debugger, restarting VSC.
The cartridge has the .project file

dw.json has both the cartridgePath and cartridge properties. Code upload **works fine**

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**
![Schermata 2023-01-23 alle 15 23 12](https://user-images.githubusercontent.com/92781198/214063367-62237e30-df2e-45fd-8cf0-4ba36e346a41.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1
 - VSCode Version: 1.74.3 (Universal)
 - Prophet v1.4.31

**Comment by SqrTT** [comment]
Hi @federicogiampietro 

This error is reported  here 
https://github.com/SqrTT/prophet/blob/c635ad5ae3858a703461596930786c9d17977f69/src/mockDebug.ts#L732-L750
and it may happen in case it can't recognize cartridge based on filename. Most likely your cartridge is missing in `cartridgesList` . To see if your carteidge is in that list you may enable more verbose logging for debugger via your `launch.json`. To do so it needed to set `"trace": true`, example:
 
![image](https://user-images.githubusercontent.com/1271300/214526813-8cbfc9e1-c818-4077-82f1-42e5fd7bab82.png)

After this run debugger. So at this point output of debug console should contain more details.
In your case is interested event `DebuggerConfig`. it contains options and has `cartridges` property. Please verify if it contain your cartridge.

**Comment by SqrTT** [comment]
feel free to reopen once have more info
