### ISSUE TITLE
No break point is hit or stop

### ISSUE THREAD

**Issue by longsoft-dev** [SqrTT/prophet#352]
Seems this has been an issue on and off for years. In my case, I'm developing an OCAPI hook and trying to debug it.

Debugger connected to sandbox successfully. Cartridge uploading without issue. Request reached the hook, code ran through without stopping at the break points.

 - OS: Windows 11
 - VSCode version: 1.76.1
 - The extension version: 1.4.31

Pre-checks:

- No .project at parent directory.
- Hook code did run as there were outputs to the log

Trace:

`
From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"prophet","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true})

To client: {"event":"prophet.getdebugger.config","type":"event","seq":1}
From client: DebuggerConfig({"config":{"hostname":"xxx.demandware.net","username":"AAA","password":"xx","code-version":"dev1","verbose":true,"cartridge":["BBB"],"configFilename":"c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\dw.json"},"cartridges":["c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\sg_storefront_richUI","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\sg_storefront_core","c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\app_headless","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\sgc_core","c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\bm_humm","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\sgc_controllers","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\ref_int_strongmail","c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\module_pagedesigner","c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\bm_plugin","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\ref_int_simplefeed_jfw","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\ref_int_bvstory","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\ref_int_bvreview","c:\\Users\\AB\\sfcc\\cartridges\\app\\refapp\\ref_int_bazaarvoice","c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\app_storefront","c:\\Users\\AB\\sfcc\\cartridges\\app\\client\\int_latitude_pipelines",[...]
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":false,"supportsFunctionBreakpoints":false,"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":false,"supportsStepBack":false,"supportsSetVariable":false,"supportsRestartFrame":false,"supportsStepInTargetsRequest":false,"supportsGotoTargetsRequest":false,"supportsCompletionsRequest":false,"supportsRestartRequest":false,"supportsExceptionOptions":false,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":false,"supportTerminateDebuggee":false,"supportsDelayedStackTraceLoading":false,"supportsLoadedSourcesRequest":false,"supportsLogPoints":false,"supportsTerminateThreadsRequest":false,"supportsSetExpression":false,"supportsTerminateRequest":false,"exceptionBreakpointFilters":[]}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"DebuggerConfig","success":true}
From client: launch({"type":"prophet","request":"launch","name":"Attach to Sandbox","trace":true,"__configurationTarget":6,"__sessionId":"c7a46ca5-5fee-42c5-8993-ff9d119328b3"})
req: {"baseUrl":"https://xxx.demandware.net/s/-/dw/debugger/v2_0/","uri":"/","username":"AAA","password":"xx","hostname":"xxx.demandware.net","headers":{"x-dw-client-id":"prophet","Content-Type":"application/json"}}
res: ""
req -> {"uri":"/breakpoints","method":"DELETE"}
req: {"uri":"/breakpoints","method":"DELETE"}
res: ""
To client: {"seq":0,"type":"response","request_seq":3,"command":"launch","success":true}
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"successfully connected\nconsole can be used to evaluate variables\nwaiting for breakpoint hit...\n"}}
successfully connected
console can be used to evaluate variables
waiting for breakpoint hit...
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":4,"command":"configurationDone","success":true}
From client: threads(undefined)
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
To client: {"seq":0,"type":"response","request_seq":5,"command":"threads","success":true,"body":{"threads":[]}}
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads/reset","method":"POST"}
req: {"uri":"/threads/reset","method":"POST"}
res: ""
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
req -> {"uri":"/threads","method":"GET"}
req: {"uri":"/threads","method":"GET"}
res: "{\"_v\":\"2.0\"}"
...
`

**Comment by SqrTT** [comment]
Hi @longsoft-dev 
Thanks for reporting.
I see no POST request to `breakpoints` endpoint are breakpoints setup before debugger launch?

Also could you please share example of path to file which you trying to debug? (without sensitive data of course)

**Comment by longsoft-dev** [comment]
Hi @SqrTT,
Thanks for your speedy response. Yes, breakpoints were set up before debugger launch.

Following your hint, I start the debugger first and set breakpoints thereafter, and it's working now! Thanks again and hope this could be documented for future reference.

**Comment by SqrTT** [comment]
well, in both cases debugger should set breakpoints

**Comment by SqrTT** [comment]
Would you add `"trace": true` to your `launch.json` so log would have records with data send to debugger.

![image](https://user-images.githubusercontent.com/1271300/224666240-51be0eb5-3216-445f-8967-08d79c74cbfa.png)
 
 And provide log with updated info. Thank you.

**Comment by longsoft-dev** [comment]
Hi @SqrTT, the provided log was produced when trace has already been turned on in `launch.json`.
Here is the example of path to file which I was trying to debug:
![image](https://user-images.githubusercontent.com/302347/224850224-665fe6f5-acd2-4ec6-8896-52099e6809ae.png)

**Comment by SqrTT** [comment]
@longsoft-dev 
Indeed, trace is enabled... sorry for confusion. I still can't understand why VSCode is not sending breakpoints to debugger during initialization. Could you as experiment disable all other extensions and see if behavior is changed, please?

**Comment by longsoft-dev** [comment]
@SqrTT
The problem is, once it's working, it's working, i.e., it's not reproducible from my end. So now even if I set breakpoints before starting debugger, it still works.
I suspect if there is some special handling during the first time the debugger was attached to the sandbox, or the state of sandbox changed?
P.S. I did turn off all caching before starting the debugger in the first place.

**Comment by SqrTT** [comment]
so is issue solved?

**Comment by longsoft-dev** [comment]
It still happens sometimes, but the trick of starting the debugger without any breakpoints, then add them later on seems working. So thanks for your time and communication, and we can close the ticket if you like.
