### ISSUE TITLE
Uploading cartridges crushes every 2-3 minutes

### ISSUE THREAD

**Issue by elina-web-magic** [SqrTT/prophet#353]
**Describe the bug**

**To Reproduce**
During development the uploader stops to upload cartridges every 2-3 minutes and it needs to restart uploading ever ytime

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - VSCode version
 - The extension version [e.g. 22]

**Additional context**

**Comment by SqrTT** [comment]
Hi @elinadzhelilovasfcc 
thanks for reporting. Unfortunately there are not details to understand what is happening. Could you add more details, like version of plugin (or it's latest 1.4.31?), some logs etc, please?

PS also please try to disable all other plugins  to exclude issues with them.

**Comment by elina-web-magic** [comment]
Hi, @SqrTT 
The Prophet version is v1.4.31
Can't catch any logs
I'll try to disable other plugins, thanks

**Comment by SqrTT** [comment]
what uploader output shows?

![image](https://user-images.githubusercontent.com/1271300/228585715-a7abbb45-3200-4f0d-9f72-12307b77638f.png)

**Comment by elina-web-magic** [comment]
@SqrTT for that moment disabling all plugins helped. I'll monitor the issue, thanks!
