### ISSUE TITLE
"Override file in another cartridge..." not prompting with cartridge options

### ISSUE THREAD

**Issue by christopherjanzen** [SqrTT/prophet#354]
Despite having declared cartridgesPath with cartridges in dw.json, when right clicking in file and choosing "Override file in another cartridge...", nothing happens. Expected behaviour is command palette dropdown with cartridge list to pick which cartridge to create the override in.

**Comment by SqrTT** [comment]
Hi @christopherjanzen 
Thanks for reporting. The latest version comes with 'site scope selector'. In case SFCC metadata present in workspace it detects cartridges sites and allows to choose site you are working for. Also `cartridgesPath` is used to detect path but by default it require to be selected in menu. 
![image](https://user-images.githubusercontent.com/1271300/231089406-b3b9aa4e-286b-48da-bb4f-0a621287d8c6.png)

PS: probably would be good idea to highlight somehow...

**Comment by christopherjanzen** [comment]
Thank you for clarifying, and agreed it would be great to add it to documentation.
