### ISSUE TITLE
New cartridge not uploading

### ISSUE THREAD

**Issue by duckjones** [SqrTT/prophet#356]
I'm not able to use the Uploader to upload a new SFCC cartridge. I'm currently running v1.4.40. Initially I tried manual creation, added my code to the folder structure and tried to sync, but the new cartridge was not shown in the Prophet Uploader tab of VS Code's Output tab and didn't get uploaded to my sandbox. I verified that it appears in the "Cartridges" view of the extension pane.

Just to test, I created another cartridge using the extension's "Create Cartridge" feature and tried re-syncing. That cartridge also did not make it into the upload. I tried explicitly adding the "cartridgesPath" attribute to my dw.json file and added both new cartridges and still neither one was uploaded.

**Comment by SqrTT** [comment]
Hi @duckjones 
Latest version use cartridge path form site.xml and allow select site you are currently working. Also to reduce size (and time) of zip uploads only cartridges form cartridge path is uploaded.

Having this, could you please add newly created cartridge to site.xml (or `cartridgesPath`) and select context/site on bar panel (or `SFCC Context: dw.json` in case of `cartridgesPath`)


![image](https://user-images.githubusercontent.com/1271300/235607320-3f6a881b-a538-4862-85d0-0b6e2c54863f.png)

**Comment by ValentinGurkov** [comment]
Hello,

Would you consider allowing us an option to upload all cartridges like before?

In use cases where we have multiple sites or an older project where (unfortunately) not all metadata is correct, this can be a burden.

**Comment by SqrTT** [comment]
Hi @ValentinGurkov 

yes, if you select option `SFCC Context: Not selected` all cartridges will be uploaded (as before) but code assistant which rely on cartridge path will be degradated (ie goto via `template` attribute or resolving `requrie('*/etc'`)

**Comment by ValentinGurkov** [comment]
> Hi @ValentinGurkov
> 
> yes, if you select option `SFCC Context: Not selected` all cartridges will be uploaded (as before) but code assistant which rely on cartridge path will be degradated (ie goto via `template` attribute or resolving `requrie('*/etc'`)

Yes, I've tried this as well but at the moment we have to choose between being able to upload all cartridges or having SFCC IntelliSense. Previously we had both.

So I wanted to ask you to reconsider and allow us to have both functionalities like in previous updates. I know this is your plugin and you decide on how things will work, no matter what you do I want to thank you for creating this plugin and sharing it with us.

**Comment by SqrTT** [comment]
> > Hi @ValentinGurkov
> > yes, if you select option `SFCC Context: Not selected` all cartridges will be uploaded (as before) but code assistant which rely on cartridge path will be degradated (ie goto via `template` attribute or resolving `requrie('*/etc'`)
> 
> Yes, I've tried this as well but at the moment we have to choose between being able to upload all cartridges or having SFCC IntelliSense. Previously we had both.
> 
> So I wanted to ask you to reconsider and allow us to have both functionalities like in previous updates. I know this is your plugin and you decide on how things will work, no matter what you do I want to thank you for creating this plugin and sharing it with us.

Unfortunately, previously IntelliSense was not working correctly, that's why is required to use cartridges path. For instance current version generates TS definitions for SFCC forms (ie `session.forms`) but definition depends on cartridges order.
There are few way to specify:
* `cartridgesPath` in `dw.json`
* `site.xml`

Note: `site.xml` may be added in separate folder to workspace so is not required to modify existing meta in project.

Anyway, I will try figure out how to build cartridge path based on cartridge list.

**Comment by SqrTT** [comment]
closing since no further info about initial issue. Please reopen if actual
