### ISSUE TITLE
Prophet Debugger is not working

### ISSUE THREAD

**Issue by mlanchas-pcis** [SqrTT/prophet#359]
Type: <b>Bug</b>

The cartridges are never loaded inside visual studio code, we have a loader but we can't do anything. And the processor of my macbook pro goes to 100%. 

Extension version: 1.4.40
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 66232d63-9b84-4f32-88ac-c680b480c275|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705
pythonnosm12tcf:30757130

```

</details>

**Comment by SqrTT** [comment]
Hi @mlanchas-pcis 
Have you tried disable all extension except Prophet and see if it's working?

**Comment by seki2020** [comment]
Same issue to me from yesterday. 
Even though disable all the others extensions. 
![image](https://github.com/SqrTT/prophet/assets/46511237/65d21dbe-d1d2-4a54-a301-a040402fa213)

**Comment by SqrTT** [comment]
@seki2020 
Do you also have CPU usage 100%?

PS: most likely SFCC have updated your sandbox. Double check your email it's case sensitive to email for debugger. See also https://github.com/SqrTT/prophet/issues/357#issuecomment-1571650784

**Comment by seki2020** [comment]
> @seki2020 Do you also have CPU usage 100%?
> 
> PS: most likely SFCC have updated your sandbox. Double check your email it's case sensitive to email for debugger. See also [#357 (comment)](https://github.com/SqrTT/prophet/issues/357#issuecomment-1571650784)

You are right, email is case sensitive for debugger. 
After using case sensitive email, problem solved. 
Thanks!

**Comment by mlanchas-pcis** [comment]
I think it's not related to Prophet. It's an another extension which block Prophet. 
I will close this topic. 
Thanks :)
