### ISSUE TITLE
SVG resource not found

### ISSUE THREAD

**Issue by ghgofort** [SqrTT/prophet#36]
Each time I load the extension I get an error. It appears that the file name is being left off when trying to load an SVG resource. When I update the log files using the refresh option I get several more of these errors.

## Relevant Screen Shots:
- **Error on load:**
Failed to load resource: net::ERR_FILE_NOT_FOUND
![image](https://user-images.githubusercontent.com/16811151/28726554-7f8e8d3c-7376-11e7-987c-d2cab713e4f9.png)

- **After Refresh of the log files:**
![image](https://user-images.githubusercontent.com/16811151/28726581-a0fe08bc-7376-11e7-83bf-9a4fcb457d8e.png)

- **Expanded example:**
![image](https://user-images.githubusercontent.com/16811151/28726613-bdf098a4-7376-11e7-9255-7705591b0509.png)

### My Setup:
- Mac OS Sierra Version 10.12.6
- VS Code Version 1.14.2
- Prophet Version 0.9.1

**Comment by SqrTT** [comment]
@ghgofort 
The issue should be fixed in v0.9.2. Could you please confirm?

**Comment by ghgofort** [comment]
@SqrTT -- This is fixed in v0.9.2.  Thank you!
