### ISSUE TITLE
Get error when start debug for SFCC Code

### ISSUE THREAD

**Issue by goc-nikul** [SqrTT/prophet#364]
**Describe the bug**
When i put break point and start debugging then it will generate error in Debug Console

**To Reproduce**
1. Open vs connect and connect salesforce commerce cloud org.
2.Upload code to salesforce commerce cloud org using prophet
3. Add break point and Start debugger create launch.json file and add below code
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"type": "prophet",
"request": "launch",
"name": "Attach to Sandbox"
}
]
}
4.  Click on Run and Debug and attach to sandbox.
5. typeError: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:29557
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28332
at new Promise ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
at JSON.parse ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
at new Promise ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
at JSON.parse ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
at new Promise ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
at JSON.parse ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
at new Promise ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
SyntaxError: Unexpected token '<', "<a href="/"... is not valid JSON
at JSON.parse ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28346
at new Promise ()
at .vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:28311
at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Expected behavior**
It should be trigger break point when execute that code.

**Screenshots**
![image](https://github.com/SqrTT/prophet/assets/106730692/9c8fab69-c17c-42d9-b449-778decd05168)

**Desktop (please complete the following information):**
 OS Version:
Version: 1.80.1 (user setup)
Commit: 74f6148
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

 - The extension version [e.g. 22]
Salesforce Commerce Cloud Productivity Pack v1.0.3
Prophet Debugger v1.4.40

**Additional context**

**Comment by SqrTT** [comment]
Hi @goc-nikul 
Thanks for reporting. 
Based on your comment: https://github.com/SqrTT/prophet/issues/92#issuecomment-1639662723
Sandbox returns 301 redirect instead of expected JSON with list of break points or treads... is there any update on SFCC side?

**Comment by goc-nikul** [comment]
Hi SqrTT/prophet

Thank you for the update.
Is there any setting required to do it on the SFCC side ? Because other
people's debuggers work properly.

**Comment by goc-nikul** [comment]
Hi @SqrTT 

It is solved now. that was issue with host name.
