### ISSUE TITLE
Issues when trying to start debugger: "Unable detect cartridge"

### ISSUE THREAD

**Issue by ericsantosbr** [SqrTT/prophet#368]
**Describe the bug**
The bug happens everytime I try to start the debug in the project. I receive a message that says "Unable detect cartridge:", followed by the path for a specific file. This prevents the debugging tool to work.

**To Reproduce**
1. Start debug on F5 key
2. Go to Debug Console tab
3. See error (print below)

**Expected behavior**
Debugging starts and runs fine.

**Screenshots**
![image](https://github.com/SqrTT/prophet/assets/10171110/750e536d-8163-4a18-ae20-2ae9f4148637)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VSCode version: 1.8.1
 - The extension version 1.4.40

**Additional context**
Already tried refreshig cartridges in the Prophet tab, deleting the file reported, uninstall and install Prophet again, delete and refresh dw.json, changing branches. Problem persists. The only workaround for me is to clone the project in another folder and start over again. This is the third time this happens.

**Comment by SqrTT** [comment]
Hi @ericsantosbr 
Is there change that break point was added to `got diff` viewer? Would you try to remove all break point ant then try to run debugger?

**Comment by ericsantosbr** [comment]
> 

Well, removing all breakpoints worked! Thank you! :D
