### ISSUE TITLE
Prophet Start Issue giving 401undefinedDisconnecting

### ISSUE THREAD

**Issue by appyfizz** [SqrTT/prophet#369]
**Describe the bug**
I am able to upload my codes to the sandbox. When starting the Debugger, it is giving 401 Undefined error in the console.
I am using v1.4.40 prophet version and my launch.json looks like this :
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "prophet",
        "request": "launch",
        "name": "Attach to Sandbox"
      }
    ]
}

[](url)

The error log I am getting : 
# ERROR just now (2023-09-18T07:00:20.182Z)  UNKNOWN
 http-nio-10.0.18.201-10182-exec-25 com.demandware.beehive.core.internal.debugger.ScriptDebuggerAuthHandler - TEMPORARY d67c28cf7c 54b5cc53dd5b51c79148d8bbc1 5174959335231218688 - Could not log in user
System Information
------------------
RequestID: 54b5cc53dd5b51c79148d8bbc1
SessionType: TEMPORARY
Truncated SessionID: d67c28cf7c
ServerName: 10.0.18.201
ServerPort: 10182

Request Information
-------------------
URI: /servlet/s/-/dw/debugger/v2_0/client
Method: DELETE
PathInfo: /-/dw/debugger/v2_0/client
Remote Address: 223.235.24.180

Request Parameters
------------------

**To Reproduce**

![image (1)](https://github.com/SqrTT/prophet/assets/89521605/1db5d49e-30ff-4d6b-b6db-89f09068c16f)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - VSCode version
 - The extension version [e.g. 22]

**Additional context**

**Comment by SqrTT** [comment]
Hi @appyfizz 
Most likely in your case username is invalid. Please note: username is case sensitive for debugger while it's not for uploader (yeah, SFCC has weird logic).

**Comment by appyfizz** [comment]
Thanks @SqrTT , It worked like magic. I was considering if the last option is to go back to Eclipse, but super happy that it worked!
