### ISSUE TITLE
Vulnerability report information?

### ISSUE THREAD

**Issue by Bruswei** [SqrTT/prophet#370]
Hello,

After cloning the repository, I performed a security analysis and discovered a critical vulnerability associated with it. For security best practices, I believe it's unwise to disclose the vulnerability details publicly. Since I was unable to locate any information on how to report security issues, could you guide me on the appropriate procedure or provide a secure point of contact to report this finding?

**Comment by SqrTT** [comment]
Hi @Bruswei 

Feel free to reach me out via tolik (at) sqrtt.pro
