### ISSUE TITLE
Debugger throwing error

### ISSUE THREAD

**Issue by MihaelaAndonoaei** [SqrTT/prophet#371]
**Describe the bug**
I have not been able to launch the debugger anymore since yesterday. When I launch I get this error message in the debug console:
```
TypeError 
 Cannot read properties of undefined (reading 'stack') 
 TypeError: Cannot read properties of undefined (reading 'stack')
    at u.catchLog (c:\Users\mihaela.andonoaei\.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:43217)
    at c:\Users\mihaela.andonoaei\.vscode\extensions\sqrtt.prophet-1.4.40\dist\mockDebug.js:1:33938
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I worked on Friday just fine, not sure what happened in the meantime. I tried to install an older version and to uninstall VS Code, sandbox reset also. I have the latest versions. Can you help me fix the issue?

Thank you!

**To Reproduce**
1. Go to 'Run & Debug'
2. Click on 'Attach to Sandbox'
3. See error

**Expected behavior**
The debugger should be attached and ready to hit the breakpoints.

**Screenshots**
![image](https://github.com/SqrTT/prophet/assets/32167978/1c3c8eea-bf09-402a-9e7a-74a063040f6f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode 1.84.1
 - The extension version 1.4.40

**Comment by r-ryabyy** [comment]
I have just updated to 1.84.1 from 1.84.0 today and got no problems.
It seems require additional information

**Comment by MihaelaAndonoaei** [comment]
The issue was solved after reinstalling VS Code and the Prophet extension, after cleaning up the folders. 
Thank you!
