### ISSUE TITLE
Uploader causing VSCode Extension Host crash

### ISSUE THREAD

**Issue by ghgofort** [SqrTT/prophet#38]
## Error Description

About every 1-2 hours I am getting an error stating:
**Extension host terminated unexpectedly. Please reload the window to recover.**
![image](https://user-images.githubusercontent.com/16811151/28848569-4ce1172e-76c8-11e7-8749-5a5204579e0e.png)

If I examine the developer tools I am getting:
**Code: null**
**Signal: SIGBART**
![image](https://user-images.githubusercontent.com/16811151/28849066-302f31e0-76ca-11e7-99b6-aa07bda50a8e.png)

This has been happening since I started using the built-in uploader. If I disable the upload feature then the issue goes away.  I have been using the dw-upload cli tool for the time being, and I have not had an issue with this setup.

All of the other features seem to keep working while the message to reload the window is present, but the uploading stops functioning.

## Steps Taken So Far:

- I have disabled all the other extensions -- The issue still occurred.
- I have re-installed VSCode. -- The issue still occurred.
- I have disabled uploading in Prophet -- This does make the error go away.
- I have run the VSCode with the verbose flag to see if I get any further errors. Here are the results:
![image](https://user-images.githubusercontent.com/16811151/28849014-f0729182-76c9-11e7-897f-84262a3c1d47.png)

## My Setup

- **OS**: Mac OS X Sierra - Version 10.12.6
- **VSCode Version**: 1.14.2
- **Prophet Plugin Version:** 0.9.1
- **Extensions Installed:**
![image](https://user-images.githubusercontent.com/16811151/28848872-62f67738-76c9-11e7-978c-1738d261f33e.png)

**Comment by SqrTT** [comment]
Hi @ghgofort, thanks for reporting I'll take a look on this.

Few questions:
* How large your code base is (amount of files)?
* Is memory usage stable or it is growing over time?

**Comment by ghgofort** [comment]
@SqrTT - It doesn't appear to be caused by a memory leak. The memory usage snapshot is about the sam when it occurs as when if first boots up.  I do have a large number of files in the workspace (45,001).  Not all of these are watched though.  

Do you think it would help if I wasn't watching every cartridge (49 of them) and just watched the ones that I was currently working on?

I have also noticed that the uploader will stop working without giving me an error message and no error is logged in the dev tools either. I would imagine that this is the same issue, but I am not sure.

BTW -- I also run a gulp watch simultaneously from the terminal to build any changes to SASS or JS files.  I am not sure if this could be interfering but I forgot to mention this in the original issue.

**Comment by SqrTT** [comment]
Hi, @ghgofort 
we had release 0.9.2. 
Is the issue still actual?

**Comment by ghgofort** [comment]
@SqrTT - After going through and disabling some extensions, removing some cartridges from the dw.json file, and making changes to my jsconfig.json file includes section I have not had the issue yet today (5 hours or so). I believe that the jsconfig includes may have been the cause of the issue.  I am closing this issue.

**Comment by SqrTT** [comment]
thanks for the feedback.

**Comment by wesdeg** [comment]
I am having the same problem.
