### ISSUE TITLE
Enable upload without clean option.

### ISSUE THREAD

**Issue by dshestopalov** [SqrTT/prophet#44]
Would be great to have an option to enable upload without uploading all cartridges at the start.

**Comment by SqrTT** [comment]
Hi @dshestopalov,

In v0.9.4 added option `extension.prophet.clean.on.start`. Please confirm that it fits your needs.

**Comment by dshestopalov** [comment]
Yep, that works (after reload). Thanks !

**Comment by dshestopalov** [comment]
But "Clean" is not working with this option set to false. I would expect "Clean project/Upload All" should still work in that case.

**Comment by SqrTT** [comment]
sorry missed that.

Should be fixed in 0.9.5. Please confirm.

**Comment by ranveer5289** [comment]
Works fine for me 👍

**Comment by SqrTT** [comment]
@dshestopalov 
closing for now. feel free to reopen if it doesn't work for you

**Comment by dshestopalov** [comment]
Works for me, thank you!
