### ISSUE TITLE
Create a common dependency for code uploading

### ISSUE THREAD

**Issue by SGD1953** [SqrTT/prophet#48]
I'd be very much in favour of creating a single bare-bones dependency for handling code uploads. There is another implementation of this in https://bitbucket.org/demandware/dw-node-code-uploader/src/ea19c425cfcd70f8d530080c09287ca4f8a91098/lib/server.js?at=master&fileviewer=file-view-default and a few more.

The implementation we use here seems to not have any dependencies to vscode which should make this a relatively straight-forward effort.

Thoughts?

**Comment by ufnd** [comment]
@SGD1953 I think we will need to create modules: SFCC WebDav and Upload

**Comment by SGD1953** [comment]
Yes, I mostly mean the WebDAV access handling, i.e. a nodejs API to wrap the HTTP stuff like putting a file, deleting a file etc. All low-level and then applications can put their handling on top (i.e.  if they prefer to check if the folder exists first or if they just upload etc.

**Comment by SqrTT** [comment]
Not sure if I understand correctly. 
Do you mean we should extract WebDAV module to be able to use in other projects?

If yes then WebDAV already is such extraction. Current WebDAV is based on Tri's [dwdav](https://bitbucket.org/demandware/dwdav). The difference is only that WebDAV is wrapped under RxJS that's why isn't used via npm.

Also really not sure if anybody else wants's use Rx based module...

**Comment by SGD1953** [comment]
Maybe you need to explain to me at some point what the benefit of the Rx stuff is. Apparently there are a bunch of uploaders around, I found https://bitbucket.org/demandware/dw-node-code-uploader which I find quite useful.

In the end I'd like to consolidate the landscape of available tools a bit and concentrate efforts to a single one.

**Comment by SqrTT** [comment]
Rx stuff allows processing uploading as concurrent stream (for example upload no more than 5 files on time when 100 was changed - switched branch) that can be canceled at any time by the user or by error.

Or more complex stuff run pipeline: `zip -> upload -> unpack -> remove remote`. step by step in 3 concurrent "threads" (no real thread but 3 pipelines at different steps) which also can be canceled at any time by the user or in case some error happened.

I can't even imagine how would be complex logic without Rx.

**Comment by SGD1953** [comment]
OK, great. Thank you for clarification!

**Comment by SqrTT** [comment]
closing since no action point to me here
