### ISSUE TITLE
Exclude files from upload

### ISSUE THREAD

**Issue by dmersiowsky** [SqrTT/prophet#49]
It would be great to have some kind of "extensions.prophet.upload.filesExclude" setting.

Example: I have a cartridge that would install Node JS modules inside the cartridge folder. I know it's a bad practice, but it would be nice if I would have a chance to exclude it from my upload. Additionally, I'd like to exclude images etc. so my upload is faster while doing development.

Additionally, it would then also be nice to have a "clean & upload all (ignore excluded files)" vs. "clean & upload" command.

**Comment by SqrTT** [comment]
Currently, you might use `files.watcherExclude` to exclude files from watching. The "cleanup" case already [exclude](https://github.com/SqrTT/prophet/blob/master/src/server/WebDav.ts#L292) node_modules and git files but is not configurable via external config. Probably I'll add configuration for this in nearest future.

**Comment by SGD1953** [comment]
Not sure if this is standard but my vs code comes with the following defaults:
```
 "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
  },
```
If you are using the latest version that utilizes the native watcher capabilities it should ignore those folders already.

But maybe not when zipping the cartridges, @SqrTT it might be worth to put the excludes in a central place and also respect `files.watcherExclude`.

**Comment by JohnLouderback** [comment]
@SqrTT I'm experiencing it where on clean the `node_modules` directory is trying to be zipped and uploaded but it kills the upload and then retries uploading all cartridges from scratch again. Because it is never able to upload the `node_modules` directory, it continues to try to upload everything infinitely.

**Comment by SqrTT** [comment]
Hi @JohnLouderback 
Could you please add more details? (ie. folder structure, your configs etc)

This does not happen to me.

**Comment by SqrTT** [comment]
added config `extension.prophet.ignore.list` which allows excluding files from being zipped and uploaded during clean (in `v1.0.1`).

`node_modules`, `.git` are ignored by default

@dmersiowsky could you please confirm it works for you?

**Comment by dmersiowsky** [comment]
Can confirm, thanks very much!

**Comment by SqrTT** [comment]
please reopen if it doesn't work for you
