### ISSUE TITLE
Detailed upload status

### ISSUE THREAD

**Issue by dmersiowsky** [SqrTT/prophet#50]
It would be nice get some more details on the current upload status, e.g. a percentage.

When uploading big cartridges (e.g. I recently worked with a 50MB one), the upload might take some time, so it would be great to have a possibility to get sure whether the upload is running or hanging.

**Comment by SqrTT** [comment]
Detailed status is available in `output` (View -> Output)

![image](https://user-images.githubusercontent.com/1271300/30102967-dfe7ae0a-92f9-11e7-949c-943777365f9e.png)

In realise 0.9.5 added status in StatusBar:

![image](https://user-images.githubusercontent.com/1271300/30103014-0c755576-92fa-11e7-9c44-d9d07dd6a845.png)

Does this fit your needs?

**Comment by dmersiowsky** [comment]
Looks good! In general, as much info as possible ("uploading cartridges: 3 of 5 uploaded") would be great :)

**Comment by SqrTT** [comment]
Added more detailed info in 0.9.8

**Comment by Pepo** [comment]
Great!!!

**Comment by SqrTT** [comment]
you are welcome
