### ISSUE TITLE
Edit Pipelines without Eclipse?

### ISSUE THREAD

**Issue by nicolas-law** [SqrTT/prophet#52]
Hey, I was just wondering if you were planning to implement a way to edit the XML Pipelines without using Eclipse ?
Thanks!

**Comment by Gektorian** [comment]
no way 💯

**Comment by nicolas-law** [comment]
:'(

**Comment by Gektorian** [comment]
you know I'm not official plugin owner or person that can say for 100%, but I'm 99,99% sure it will not be implemented as SFCC moving our from the pipelines, so what is the reason support something that will be removed in the future?

**Comment by SqrTT** [comment]
I don't have a plans to add pipelines support nor time for it. But if anybody makes PR I would be happy to merge it (note: there no way to build a debugger for it).

**Comment by nicolas-law** [comment]
Alright, thanks for answering ;)
