### ISSUE TITLE
Prevent Upload Sensitive Data

### ISSUE THREAD

**Issue by ufnd** [SqrTT/prophet#53]
When you doesn't configure cartridge list in the **dw.json** file or in settings, you will upload all content from project folder, which is not secure.
Folders like **.git** or another can have a lot of private information.
We will need to find all cartridges or upload nothing if we can't detect them.

**Comment by SqrTT** [comment]
Not sure what is the meaning of `Sensitive Data`.
Also, a sandbox is not something public and companies have agreement with NDA...

**Comment by zetxek** [comment]
I think this would be in the line of the "Directories to exclude from upload" setting in the UX Studio plugin:

![image](https://user-images.githubusercontent.com/240085/33079602-589c28fe-ced6-11e7-83e8-c57ffad56949.png)

Or as the "exclude patterns" in dwupload npm package: https://www.npmjs.com/package/dwupload

**Comment by SqrTT** [comment]
the issue should be fixed in `v1.0.0`

**Comment by SqrTT** [comment]
the extension uploads only detected cartridges
