### ISSUE TITLE
[Not an issue] Need some advices

### ISSUE THREAD

**Issue by nicolas-law** [SqrTT/prophet#56]
Hey guys, sorry but I have nowhere to ask this so if someone answers, thank you in advance.

I'm developping a custom payment gateway for DemandWare and I can't figure how to return a JSON response after a calling a Pipeline.

What I'm doing :
- Ajax request with POST parameters to my pipeline url http://example.demandware.net/on/demandware.store/Sites-SiteGenesis-Site/fr_CA/PaymentProcessor-MyPipeline
- myScript.ds is called
- END Node ? Interaction Node ?

On prestashop, I do it this way :
- Ajax request with POST parameters to http://example.com/modules/paymentGateway/example.php
- echo json_encode($myResult)

What would be the equivalent to echoing a JSON response in an ISML template ?
Is there a waying to call a script without using a pipeline ?

EDIT:
I am aware of these functions but I'm not sure how to use them in this context..
`    let r = require('~/cartridge/scripts/util/Response');
    r.renderJSON({
        Message: 'Hello World!'
    });
`
and
`
let ISML = require('dw/template/ISML');
function sayHello() {
    ISML.renderTemplate('helloworld', {
        Message: 'Hello World!'
    });
}
`

Thank you if you can help me ;(

**Comment by SqrTT** [comment]
Well, that's the wrong place for such questions. Would be better addressed to xchange or community channel.

Anyway, you should use end node with template `util/responsejson`.
