### ISSUE TITLE
Feature Request: Formatting options for ISML and DSScript language servers.

### ISSUE THREAD

**Issue by ghgofort** [SqrTT/prophet#57]
It would be great if there was a JSON file for formatting options for the language syntaxes or a good explanation of where the settings are currently being derived from.

After a look through the code it appears that there is a built in version of beautify being used for this feature and perhaps it is just a matter of knowing where these settings need to be placed. Thanks for taking a look at this!

**Comment by SqrTT** [comment]
Hi, 
formatting is available for ISML already. But has limitation because can format only valid XML (formats ISML a bit incorrectly)

The formatter is using standard build-in rules. Configurable via `html.format.<name>` prefs.

**Comment by ghgofort** [comment]
Looks like I am able to do most of what I was hoping for from these options.  If I have specific requests for formatting I will submit those, but it looks good to me.

Closing Issue.
