### ISSUE TITLE
Unable to set breakpoint to non backend file

### ISSUE THREAD

**Issue by nicowernli** [SqrTT/prophet#58]
This is weird, I really don't know how to reproduce this error, but when trying to set a breakpoint in some files I get this error `Unable to set breakpoint to non backend file`. 

I'll add more information if I find out how to replicate.

**Comment by SGD1953** [comment]
I got this too the other day, don't really have any more insights but it is not just you.

**Comment by SqrTT** [comment]
[This](https://github.com/SqrTT/prophet/blob/master/src/mockDebug.ts#L169-L172) conditions must fit to set brackpoint

**Comment by SqrTT** [comment]
Hi @nicowernli 
Is there known steps to reproduce?

**Comment by SqrTT** [comment]
Didn't find reproduce the issue. Are you sure that was in backend file?

**Comment by SqrTT** [comment]
closing since didn't know how to reproduce
