### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Gektorian** [SqrTT/prophet#6]
Please, create wiki/section, how people could contribute. I would be interested in api autocomplete feature that possible could be added to this extension and etc. But would be great to know, how people can help to improve and extend current extension.

**Comment by SqrTT** [comment]
Thanks for the suggestion, I'll add some short info soon.

PS. Regarding autocomplete, I have implemented this feature but I can't share it with public plugin because is contains a lot of information about internal Demaldware classes, so this can have legal issues . (basically, this is `d.ts` files)

**Comment by Gektorian** [comment]
@SqrTT I have private repo with autocomplete for webstorm with jsdocs that use node_modules as a core. Is it possible to create a private repo with autocomplete and give access for those who will let say request it on xchange(create post like sfcc did for mfsg)?

**Comment by ranveer5289** [comment]
Hello,

Maybe in that case ( legal issue ) we can use Demandware bitbucket repo. 

Not sure how that will work.

**Comment by SqrTT** [comment]
> Maybe in that case ( legal issue ) we can use Demandware bitbucket repo

Sounds great, but means that repo should be downloaded and added to each project manually and no auto updates...

**Comment by ranveer5289** [comment]
Yup, that is an issue.

How difficult is to manually add the API auto-complete support. If it is just copying/pasting few files, I don't think DWRE community will mind it ;)
