### ISSUE TITLE
'Clean Project/Upload All' does not delete old old files

### ISSUE THREAD

**Issue by ghgofort** [SqrTT/prophet#60]
When I do a 'Clean Project/Upload All' it does not remove any files that I have deleted from the project.  Is there any way that this could be added, or another type of clean operation could be added to allow for removal of the files in a cartridge or all cartridges before uploading again.

This would be especially helpful to avoid issues with a template that is overriding a template with the same name further down the cartridge lookup path.  This is not a high priority issue , but when I update code from our master branch on a shared repo and it includes updates from other developers, I wouldn't have to go looking through a diff from their commits to figure out why my sandbox is no longer working as expected.

Thanks for considering.

**Comment by SqrTT** [comment]
that makes sense. I will add 'removeAll' step before uploading

**Comment by SqrTT** [comment]
Hi @ghgofort  
the issue should be fixed in `v0.10.3`. Could you please confirm?

**Comment by ghgofort** [comment]
Confirmed fixed. Thanks for your time!
