### ISSUE TITLE
Variables in controllers that are defined with 'let' are not visible in debugger

### ISSUE THREAD

**Issue by ltomov** [SqrTT/prophet#67]
Seems like only variables defined with 'var' can be inspected.

**Comment by SqrTT** [comment]
yes, that is a limitation by platform (SDAPI v1 and same behavior in eclipse) not the plugin itself.

**Comment by ghgofort** [comment]
This is not really the case. The main difference is that 'var' is not scoped within any closure like 'let' or const'.  You can see the difference in the debug screen capture that I posted for 'Main Method Scope' below.  I also included a capture of the inner scope just to show that different declarations can only be inspected within their particular scope.  I hope this helps.

**Inner Scope:**
![image](https://user-images.githubusercontent.com/16811151/32923453-ef52b01e-caf4-11e7-896b-2dff48819946.png)


**Main Method Scope:**
![image](https://user-images.githubusercontent.com/16811151/32923464-fbfe8bf8-caf4-11e7-9f86-76fbc2b1eb53.png)

**Comment by SqrTT** [comment]
this is not a vscode issue. closing.
