### ISSUE TITLE
Uploader to skip missing cartridges referenced in dw.json

### ISSUE THREAD

**Issue by gkkirilov** [SqrTT/prophet#69]
If there is a missing cartridge in file explorer but is referenced in the dw.json file, uploader should skip it instead of trying to upload it and break with an exception and terminate the upload process.

**Comment by shr1k4nt14** [comment]
The error is thrown in the line https://github.com/SqrTT/prophet/blob/fc5437bf43e3d446712502f34f05221b58bfa6be/src/server/WebDav.ts#L400

If you comment out that line, it will not throw an error and will continue uploading the next cartridge.
A better solution would be to log the error message and continue.

**Comment by SqrTT** [comment]
That would disallow user know if some files are not uploaded.
IMHO is better to fail and show the user an error than pretends like everything is ok and not upload something.

**Comment by shr1k4nt14** [comment]
I have faced this situation where you develop a new plugin cartridge in a feature branch, you change the dw.json to add it. When you switch to a different branch, you again have to change the dw.json to remove the new plugin because it is not present in this branch.

**Comment by SGD1953** [comment]
I agree that logging an error prominently would be better. We could leverage the VSC error dialog and show something like "Cartridge XYZ does not exist and will be ignored, please restart the uploader once this has been resolved."

**Comment by SqrTT** [comment]
Hi @gkkirilov 
the issue should be fixed in `v0.10.3`. Could you please confirm?

**Comment by gkkirilov** [comment]
@SqrTT It is fixed Thanks
