### ISSUE TITLE
Uploading breaks at the last cartridge upon init

### ISSUE THREAD

**Issue by marianbida** [SqrTT/prophet#72]
When initially start uploading the cartridges, it breaks at deleting the last cartridge zip from remote.
[int_test] Deleting remote zip...
The upload process is restarting and it breaks again and again and again.

**Comment by SqrTT** [comment]
Could you please add more details, so I am able to reproduce?

For example, a hierarchy of folders and example of dw.json.

**Comment by SqrTT** [comment]
closing since no further info.

@marianbida feel free to reopen once you got more details
