### ISSUE TITLE
Trace enabled all the time

### ISSUE THREAD

**Issue by valterlima** [SqrTT/prophet#75]
Hello,

It looks like after a recent update (probably related to SDAPI v2), the trace log is enabled all the time, even if we set it to false in the configurations.

> req -> {"uri":"/threads/reset","method":"POST"}
> req -> {"uri":"/threads","method":"GET"}
> req: {"uri":"/threads/reset","method":"POST","json":true}
> res: undefined
> req: {"uri":"/threads","method":"GET","json":true}
> res: {"_v":"2.0","script_threads":[{"call_stack":[{"index":0,"location":{"function_name":"show()","line_number":142,"script_path":"/xxx/cartridge/controllers/Search.js"}},{"index":1,"location":{"function_name":"-anonymous-()","line_number":149,"script_path":"/xxx/cartridge/scripts/guard.js"}}],"id":8,"status":"halted"}]}
> From client: disconnect({"restart":false})
> To client: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"successfully disconected\n"}}
> successfully disconected
> To client: {"seq":0,"type":"response","request_seq":82,"command":"disconnect","success":true}

Regards,

**Comment by SqrTT** [comment]
Thank you for filing an issue. The issue will be fixed with next release.

**Comment by SqrTT** [comment]
fixed in v.0.10.1.
Could you please confirm and close the issue if is ok?

**Comment by valterlima** [comment]
The trace log is no more appearing. Thank you!
