### ISSUE TITLE
Debugger doesn't stop on breakpoint in BM extension cartridge

### ISSUE THREAD

**Issue by gkkirilov** [SqrTT/prophet#76]
I am using the customer service center customization cartridge.
It is stopping on the breakpoint in Eclipse

**Comment by SqrTT** [comment]
That's weird. It stops for me (in BM extensions, including CSC).

Could you please add more details?

**Comment by gkkirilov** [comment]
I forgot to reference the cartridge in dw.json so breakpoints weren't updated.
Case closed.
