### ISSUE TITLE
Unable to set breakpoint to non backend file

### ISSUE THREAD

**Issue by spank79** [SqrTT/prophet#77]
Hi, I have a problem letting the debugger stop on breakpoints in our custom /lib folder. Everytime I try to set the breakpoint, the response is "Unable to set breakpoint to non backend file".

The folder structure is like this:

/our_cartridge/
/our_cartridge/cartridge
/our_cartridge/cartridge/controllers
/our_cartridge/cartridge/lib => .js files and subfolders with .js files
/our_cartridge/cartridge/scripts

It does stop on breakpoints in /controllers and /scripts so I'm guessing it doesn't expect a structure like this. How could this be enabled? Or how should we configure the jsconfig.json to make this work?

Kind regards

**Comment by SqrTT** [comment]
unfortunately, I didn't find the better way to detect backend files than check [path of file](https://github.com/SqrTT/prophet/blob/master/src/mockDebug.ts#L178). For now, list of folders is hardcoded.

To solve this issue I could make this configurable but not sure if this is the best solution...

**Comment by spank79** [comment]
this would be very good as not everybody has the structure you have hardcoded. But what is the jsconfig.json for then? I thought this would be the way to enhance the experience and this could be the place then to add your own folders.

**Comment by SqrTT** [comment]
`jsconfig.json` is used by TypeScript Server for code assistance experience (autocomplete, hover info) but not used by the extension directly.

But I agree such configuration should be somewhere in the repo and not personal for developer (so every dev would need to make such config manually)

**Comment by spank79** [comment]
would you concider implementing this in the future? Would be really nice to see this work

**Comment by SqrTT** [comment]
sure, after multiroot workspaces I'll implement this

**Comment by SGD1953** [comment]
@spank79 Feel free to submit a PR, extension is all JS so it should be relatively easy to get up to speed.

**Comment by SqrTT** [comment]
the issue should be fixed in `0.10.2`. 
Could you please check and confirm?

**Comment by SqrTT** [comment]
feel free to reopen if still persist
