### ISSUE TITLE
No longer see variables when debugging

### ISSUE THREAD

**Issue by gkkirilov** [SqrTT/prophet#85]
As the image shows the variables don't show, another colleague is having the same issue
Also my instance freezes and needs a restart after hitting the breakpoint.

![image](https://user-images.githubusercontent.com/8720012/37032098-f7916d82-2149-11e8-9922-f28e14a46101.png)

Maybe it's a bug from my last PR @SqrTT ? I don't have my machine with me to test it on master branch, will check it later today.

**Comment by SqrTT** [comment]
yesterday's PR is not released yet. trying to reproduce

**Comment by SqrTT** [comment]
I'm unable to reproduce the issue. Is there are some errors?

**Comment by gkkirilov** [comment]
Can no longer reproduce it. Closing
