### ISSUE TITLE
Typescript Setup

### ISSUE THREAD

**Issue by fishme** [SqrTT/prophet#88]
thanks for the cool VC plugin, everything works perfect. 
I'm looking for TS support for my code. The code completion works awesome, so everything what is needed for that. Is on place. 

Do you know how to setup it?

**Comment by SqrTT** [comment]
Hi @fishme 

Your question is not clear to me. 
Are you asking to configure TS for SFCC development (develop backend on TS)? If so SFCC doesn't approve such approach (more details [here](https://bitbucket.org/demandware/sitegenesis/pull-requests/980)) also you can found there an example of the configuration.

Or are you talking to configure TS for client-side scripting? In this case, you can find much info on the wild web.

**Comment by fishme** [comment]
That's what I was looking for @SqrTT
