### ISSUE TITLE
Icon stuck in perpetual upload cartriges

### ISSUE THREAD

**Issue by AlexandruDinulescu** [SqrTT/prophet#98]
Hello

The icon for uploading cartridges at the bottom of VSC (in the bar with the GitHub) is perpetually "uploading cartridges" but I checked the prophet debugger log and it's not doing anything other than watching files.

**Comment by SqrTT** [comment]
Hi @AlexandruDinulescu 

thanks for reporting. Could you please share a version of the extension?

**Comment by AlexandruDinulescu** [comment]
Hello,

Sorry mate I was in a holiday. This seems to have fixed itself. I'm closing this.

**Comment by SqrTT** [comment]
I able to reproduce the issue for current version... so keeping opened, yet

**Comment by SqrTT** [comment]
the issue is fixed in `1.0.8` (basically reimplemented via notification window).

Feel free to reopen if still persist.
